//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectFrameCut.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projectFrameCut.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 projectFrameCut(仮) 的本地化字符串。
        /// </summary>
        internal static string AppBrand {
            get {
                return ResourceManager.GetString("AppBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后端延迟{0}ms, 内存占用{1} MB (后端/此电脑) 的本地化字符串。
        /// </summary>
        internal static string RenderPage_BackendStatus {
            get {
                return ResourceManager.GetString("RenderPage_BackendStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已使用内存: {0} 的本地化字符串。
        /// </summary>
        internal static string RenderPage_BackendStatus_MemoryOnly {
            get {
                return ResourceManager.GetString("RenderPage_BackendStatus_MemoryOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后端未响应， 内存占用{0} MB (后端/此电脑) 的本地化字符串。
        /// </summary>
        internal static string RenderPage_BackendStatus_NotRespond {
            get {
                return ResourceManager.GetString("RenderPage_BackendStatus_NotRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作未被应用，因为此操作会导致重叠 的本地化字符串。
        /// </summary>
        internal static string RenderPage_CannotMoveBecauseOfOverlap {
            get {
                return ResourceManager.GetString("RenderPage_CannotMoveBecauseOfOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改已被应用 的本地化字符串。
        /// </summary>
        internal static string RenderPage_ChangesApplied {
            get {
                return ResourceManager.GetString("RenderPage_ChangesApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        internal static string RenderPage_EverythingFine {
            get {
                return ResourceManager.GetString("RenderPage_EverythingFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去渲染 的本地化字符串。
        /// </summary>
        internal static string RenderPage_GoRender {
            get {
                return ResourceManager.GetString("RenderPage_GoRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中... 的本地化字符串。
        /// </summary>
        internal static string RenderPage_Processing {
            get {
                return ResourceManager.GetString("RenderPage_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染已完成 的本地化字符串。
        /// </summary>
        internal static string RenderPage_RenderDone {
            get {
                return ResourceManager.GetString("RenderPage_RenderDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染第{0}帧 ({1})... 的本地化字符串。
        /// </summary>
        internal static string RenderPage_RenderOneFrame {
            get {
                return ResourceManager.GetString("RenderPage_RenderOneFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误：渲染超时 的本地化字符串。
        /// </summary>
        internal static string RenderPage_RenderTimeout {
            get {
                return ResourceManager.GetString("RenderPage_RenderTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选中：{0} 的本地化字符串。
        /// </summary>
        internal static string RenderPage_Selected {
            get {
                return ResourceManager.GetString("RenderPage_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道 #{0} 的本地化字符串。
        /// </summary>
        internal static string RenderPage_Track {
            get {
                return ResourceManager.GetString("RenderPage_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎来到projectFrameCut beta! 的本地化字符串。
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
