// <auto-generated>
// Generated in 2026/1/23 18:39:09
// These code are generated by SimpleLocalizer. Don't modify it directly; modify the 'localized.json' file and regenerate code to apply changes.
// </auto-generated>

#nullable enable
#region usings
using System;
using System.Collections.Concurrent;
using System.CodeDom.Compiler;
using System.Diagnostics;
using projectFrameCut.Helper;
#endregion

#region base interface
/// <summary>
/// This is the base interface for all localizers.
/// </summary>
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
public interface ISimpleLocalizerBase_Helper
{
    /// <summary>
    /// Get the localized string for AppLoading (like '
    /// 加载中...
    ///')
    /// </summary>
    public string AppLoading { get; }
    
    /// <summary>
    /// Get the localized string for CorruptedInstallPrompt (like '
    /// 很抱歉，{HelperProgram.AppTitle} 的安装似乎损坏了。请尝试重新安装应用程序。
    ///')
    /// </summary>
    public string CorruptedInstallPrompt();
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback (like '
    /// 反馈
    ///')
    /// </summary>
    public string CrashForm_Feedback { get; }
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog (like '
    /// 打开日志文件
    ///')
    /// </summary>
    public string CrashForm_OpenLog { get; }
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart (like '
    /// 重启应用程序
    ///')
    /// </summary>
    public string CrashForm_Restart { get; }
    
    /// <summary>
    /// Get the localized string for CrashForm_Title (like '
    /// {HelperProgram.AppTitle} 崩溃报告
    ///')
    /// </summary>
    public string CrashForm_Title();
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright (like '
    /// 版权所有 hexadecimal0x12e 2025-{DateTime.Now.Year}
    ///
    ///')
    /// </summary>
    public string SplashForm_Copyright();
    
    /// <summary>
    /// Get the localized string for SplashForm_License (like '
    ///  
    ///')
    /// </summary>
    public string SplashForm_License();
    
    /// <summary>
    /// Get the localized string for SplashForm_Version (like '
    /// 版本 {HelperProgram.AppVersion}
    ///')
    /// </summary>
    public string SplashForm_Version();
    
    /// <summary>
    /// Get the localized string for UnsupportedOSPrompt (like '
    /// 很抱歉，{HelperProgram.AppTitle} 需要在 Windows 10 2004 / LTSC 2021 (build 19041) 或者更新的版本上运行。
    /// 请考虑升级你的系统。
    ///')
    /// </summary>
    public string UnsupportedOSPrompt();
    
    /// <summary>
    /// Get the current Locale's ID (like 'zh-CN')
    /// </summary>
    public string _LocaleId_ { get; }
    
    public static Dictionary<string, ISimpleLocalizerBase_Helper> GetMapping()
    {
        return new Dictionary<string, ISimpleLocalizerBase_Helper>()
        {
            { "zh-CN", new  __ISimpleLocalizerBase_Helper_zh_CN__() },
            { "en-US", new  __ISimpleLocalizerBase_Helper_en_US__() },
            { "zh-TW", new  __ISimpleLocalizerBase_Helper_zh_TW__() },
            { "ja-JP", new  __ISimpleLocalizerBase_Helper_ja_JP__() },
            { "ko-KR", new  __ISimpleLocalizerBase_Helper_ko_KR__() },
            { "fr-FR", new  __ISimpleLocalizerBase_Helper_fr_FR__() },
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="fallbackValue">The fallback value when the localized string isn't found.</param>
    /// <returns>The localized string you want.</returns>
    public string DynamicLookup(string id, string? fallbackValue = null)
    {
        return id switch
        {
            "AppLoading" => AppLoading,
            "CrashForm_Feedback" => CrashForm_Feedback,
            "CrashForm_OpenLog" => CrashForm_OpenLog,
            "CrashForm_Restart" => CrashForm_Restart,
            _ => fallbackValue ?? $"Can't find the localized string for id '{id}'"
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id with some arguments.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="args">The arguments to format the localized string.</param>
    /// <returns>The localized string with arguments applied.</returns>
    /// <exception cref="KeyNotFoundException">The localized string you want with arguments isn't found.</exception>
    /// <exception cref="IndexOutOfRangeException">The number of arguments provided does not match the expected number for the localized string.</exception>
    public string DynamicLookupWithArgs(string id, params object[] args)
    {
        return id switch
        {
            "CorruptedInstallPrompt" => CorruptedInstallPrompt(),
            "CrashForm_Title" => CrashForm_Title(),
            "SplashForm_Copyright" => SplashForm_Copyright(),
            "SplashForm_License" => SplashForm_License(),
            "SplashForm_Version" => SplashForm_Version(),
            "UnsupportedOSPrompt" => UnsupportedOSPrompt(),
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}' with any argument")
        };
    }
}

#endregion

#region zh_CN
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Helper_zh_CN__ : ISimpleLocalizerBase_Helper
{
    /// <summary>
    /// Get the localized string for AppLoading in zh-CN (like '
    /// 加载中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.AppLoading => AppLoading;
    public const string AppLoading = @"加载中...";
    
    /// <summary>
    /// Get the localized string for CorruptedInstallPrompt in zh-CN (like '
    /// 很抱歉，{HelperProgram.AppTitle} 的安装似乎损坏了。请尝试重新安装应用程序。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CorruptedInstallPrompt() => CorruptedInstallPrompt();
    public string CorruptedInstallPrompt() => @$"很抱歉，{HelperProgram.AppTitle} 的安装似乎损坏了。请尝试重新安装应用程序。";
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback in zh-CN (like '
    /// 反馈
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Feedback => CrashForm_Feedback;
    public const string CrashForm_Feedback = @"反馈";
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog in zh-CN (like '
    /// 打开日志文件
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_OpenLog => CrashForm_OpenLog;
    public const string CrashForm_OpenLog = @"打开日志文件";
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart in zh-CN (like '
    /// 重启应用程序
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Restart => CrashForm_Restart;
    public const string CrashForm_Restart = @"重启应用程序";
    
    /// <summary>
    /// Get the localized string for CrashForm_Title in zh-CN (like '
    /// {HelperProgram.AppTitle} 崩溃报告
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Title() => CrashForm_Title();
    public string CrashForm_Title() => @$"{HelperProgram.AppTitle} 崩溃报告";
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright in zh-CN (like '
    /// 版权所有 hexadecimal0x12e 2025-{DateTime.Now.Year}
    ///
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Copyright() => SplashForm_Copyright();
    public string SplashForm_Copyright() => @$"版权所有 hexadecimal0x12e 2025-{DateTime.Now.Year}";
    
    /// <summary>
    /// Get the localized string for SplashForm_License in zh-CN (like '
    ///  
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_License() => SplashForm_License();
    public string SplashForm_License() => @$" ";
    
    /// <summary>
    /// Get the localized string for SplashForm_Version in zh-CN (like '
    /// 版本 {HelperProgram.AppVersion}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Version() => SplashForm_Version();
    public string SplashForm_Version() => @$"版本 {HelperProgram.AppVersion}";
    
    /// <summary>
    /// Get the localized string for UnsupportedOSPrompt in zh-CN (like '
    /// 很抱歉，{HelperProgram.AppTitle} 需要在 Windows 10 2004 / LTSC 2021 (build 19041) 或者更新的版本上运行。
    /// 请考虑升级你的系统。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.UnsupportedOSPrompt() => UnsupportedOSPrompt();
    public string UnsupportedOSPrompt() => @$"很抱歉，{HelperProgram.AppTitle} 需要在 Windows 10 2004 / LTSC 2021 (build 19041) 或者更新的版本上运行。请考虑升级你的系统。";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase_Helper._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-CN";
    
    
}

#endregion

#region en_US
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Helper_en_US__ : ISimpleLocalizerBase_Helper
{
    /// <summary>
    /// Get the localized string for AppLoading in en-US (like '
    /// Loading...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.AppLoading => AppLoading;
    public const string AppLoading = @"Loading...";
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback in en-US (like '
    /// Feedback
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Feedback => CrashForm_Feedback;
    public const string CrashForm_Feedback = @"Feedback";
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog in en-US (like '
    /// Open log file
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_OpenLog => CrashForm_OpenLog;
    public const string CrashForm_OpenLog = @"Open log file";
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart in en-US (like '
    /// Restart Application
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Restart => CrashForm_Restart;
    public const string CrashForm_Restart = @"Restart Application";
    
    /// <summary>
    /// Get the localized string for CrashForm_Title in en-US (like '
    /// {HelperProgram.AppTitle} Crash Report
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Title() => CrashForm_Title();
    public string CrashForm_Title() => @$"{HelperProgram.AppTitle} Crash Report";
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright in en-US (like '
    /// Copyright hexadecimal0x12e 2025-{DateTime.Now.Year}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Copyright() => SplashForm_Copyright();
    public string SplashForm_Copyright() => @$"Copyright hexadecimal0x12e 2025-{DateTime.Now.Year}";
    
    /// <summary>
    /// Get the localized string for SplashForm_License in en-US (like '
    ///  
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_License() => SplashForm_License();
    public string SplashForm_License() => @$" ";
    
    /// <summary>
    /// Get the localized string for SplashForm_Version in en-US (like '
    /// Version {HelperProgram.AppVersion}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Version() => SplashForm_Version();
    public string SplashForm_Version() => @$"Version {HelperProgram.AppVersion}";
    
    /// <summary>
    /// Get the localized string for UnsupportedOSPrompt in en-US (like '
    /// We&apos;re sorry, {HelperProgram.AppTitle} requires Windows 10 2004 / LTSC 2021 (build 19041) or a newer version to run.
    /// Please consider upgrading your system.
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.UnsupportedOSPrompt() => UnsupportedOSPrompt();
    public string UnsupportedOSPrompt() => @$"We're sorry, {HelperProgram.AppTitle} requires Windows 10 2004 / LTSC 2021 (build 19041) or a newer version to run.
Please consider upgrading your system.";
    
    /// <summary>
    /// Get the localized string for CorruptedInstallPrompt in en-US (like '
    /// We&apos;re sorry, the installation of {HelperProgram.AppTitle} seems to be corrupted. Please try reinstalling the application.
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CorruptedInstallPrompt() => CorruptedInstallPrompt();
    public string CorruptedInstallPrompt() => @$"We're sorry, the installation of {HelperProgram.AppTitle} seems to be corrupted. Please try reinstalling the application.";
    
    /// <summary>
    /// Get the current localized Id (like 'e')
    /// </summary>
    string ISimpleLocalizerBase_Helper._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"en-US";
    
    
}

#endregion

#region zh_TW
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Helper_zh_TW__ : ISimpleLocalizerBase_Helper
{
    /// <summary>
    /// Get the localized string for AppLoading in zh-TW (like '
    /// 載入中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.AppLoading => AppLoading;
    public const string AppLoading = @"載入中...";
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback in zh-TW (like '
    /// 回饋
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Feedback => CrashForm_Feedback;
    public const string CrashForm_Feedback = @"回饋";
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog in zh-TW (like '
    /// 開啟日誌檔案
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_OpenLog => CrashForm_OpenLog;
    public const string CrashForm_OpenLog = @"開啟日誌檔案";
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart in zh-TW (like '
    /// 重新啟動應用程式
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Restart => CrashForm_Restart;
    public const string CrashForm_Restart = @"重新啟動應用程式";
    
    /// <summary>
    /// Get the localized string for CrashForm_Title in zh-TW (like '
    /// {HelperProgram.AppTitle} 崩潰報告
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Title() => CrashForm_Title();
    public string CrashForm_Title() => @$"{HelperProgram.AppTitle} 崩潰報告";
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright in zh-TW (like '
    /// 版權所有 hexadecimal0x12e 2025-{DateTime.Now.Year}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Copyright() => SplashForm_Copyright();
    public string SplashForm_Copyright() => @$"版權所有 hexadecimal0x12e 2025-{DateTime.Now.Year}";
    
    /// <summary>
    /// Get the localized string for SplashForm_License in zh-TW (like '
    ///  
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_License() => SplashForm_License();
    public string SplashForm_License() => @$" ";
    
    /// <summary>
    /// Get the localized string for SplashForm_Version in zh-TW (like '
    /// 版本 {HelperProgram.AppVersion}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Version() => SplashForm_Version();
    public string SplashForm_Version() => @$"版本 {HelperProgram.AppVersion}";
    
    /// <summary>
    /// Get the localized string for UnsupportedOSPrompt in zh-TW (like '
    /// 很抱歉，{HelperProgram.AppTitle} 需要在 Windows 10 2004 / LTSC 2021 (build 19041) 或更新的版本上執行。
    /// 請考慮升級你的系統。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.UnsupportedOSPrompt() => UnsupportedOSPrompt();
    public string UnsupportedOSPrompt() => @$"很抱歉，{HelperProgram.AppTitle} 需要在 Windows 10 2004 / LTSC 2021 (build 19041) 或更新的版本上執行。
請考慮升級你的系統。";
    
    /// <summary>
    /// Get the localized string for CorruptedInstallPrompt in zh-TW (like '
    /// 很抱歉，{HelperProgram.AppTitle} 的安裝似乎損壞了。請嘗試重新安裝應用程式。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CorruptedInstallPrompt() => CorruptedInstallPrompt();
    public string CorruptedInstallPrompt() => @$"很抱歉，{HelperProgram.AppTitle} 的安裝似乎損壞了。請嘗試重新安裝應用程式。";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase_Helper._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-TW";
    
    
}

#endregion

#region ja_JP
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Helper_ja_JP__ : ISimpleLocalizerBase_Helper
{
    /// <summary>
    /// Get the localized string for AppLoading in ja-JP (like '
    /// 読み込み中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.AppLoading => AppLoading;
    public const string AppLoading = @"読み込み中...";
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback in ja-JP (like '
    /// フィードバック
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Feedback => CrashForm_Feedback;
    public const string CrashForm_Feedback = @"フィードバック";
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog in ja-JP (like '
    /// ログファイルを開く
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_OpenLog => CrashForm_OpenLog;
    public const string CrashForm_OpenLog = @"ログファイルを開く";
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart in ja-JP (like '
    /// アプリケーションを再起動
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Restart => CrashForm_Restart;
    public const string CrashForm_Restart = @"アプリケーションを再起動";
    
    /// <summary>
    /// Get the localized string for CrashForm_Title in ja-JP (like '
    /// {HelperProgram.AppTitle} クラッシュレポート
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Title() => CrashForm_Title();
    public string CrashForm_Title() => @$"{HelperProgram.AppTitle} クラッシュレポート";
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright in ja-JP (like '
    /// 著作権 hexadecimal0x12e 2025-{DateTime.Now.Year}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Copyright() => SplashForm_Copyright();
    public string SplashForm_Copyright() => @$"著作権 hexadecimal0x12e 2025-{DateTime.Now.Year}";
    
    /// <summary>
    /// Get the localized string for SplashForm_License in ja-JP (like '
    ///  
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_License() => SplashForm_License();
    public string SplashForm_License() => @$" ";
    
    /// <summary>
    /// Get the localized string for SplashForm_Version in ja-JP (like '
    /// バージョン {HelperProgram.AppVersion}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Version() => SplashForm_Version();
    public string SplashForm_Version() => @$"バージョン {HelperProgram.AppVersion}";
    
    /// <summary>
    /// Get the localized string for UnsupportedOSPrompt in ja-JP (like '
    /// 申し訳ございません、{HelperProgram.AppTitle} は Windows 10 2004 / LTSC 2021 (build 19041) 以降のバージョンで動作する必要があります。
    /// システムのアップグレードをご検討ください。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.UnsupportedOSPrompt() => UnsupportedOSPrompt();
    public string UnsupportedOSPrompt() => @$"申し訳ございません、{HelperProgram.AppTitle} は Windows 10 2004 / LTSC 2021 (build 19041) 以降のバージョンで動作する必要があります。システムのアップグレードをご検討ください。";
    
    /// <summary>
    /// Get the localized string for CorruptedInstallPrompt in ja-JP (like '
    /// 申し訳ございませんが、{HelperProgram.AppTitle} のインストールが破損しているようです。アプリケーションを再インストールしてください。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CorruptedInstallPrompt() => CorruptedInstallPrompt();
    public string CorruptedInstallPrompt() => @$"申し訳ございませんが、{HelperProgram.AppTitle} のインストールが破損しているようです。アプリケーションを再インストールしてください。";
    
    /// <summary>
    /// Get the current localized Id (like 'j')
    /// </summary>
    string ISimpleLocalizerBase_Helper._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"ja-JP";
    
    
}

#endregion

#region ko_KR
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Helper_ko_KR__ : ISimpleLocalizerBase_Helper
{
    /// <summary>
    /// Get the localized string for AppLoading in ko-KR (like '
    /// 로딩 중...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.AppLoading => AppLoading;
    public const string AppLoading = @"로딩 중...";
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback in ko-KR (like '
    /// 피드백
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Feedback => CrashForm_Feedback;
    public const string CrashForm_Feedback = @"피드백";
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog in ko-KR (like '
    /// 로그 파일 열기
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_OpenLog => CrashForm_OpenLog;
    public const string CrashForm_OpenLog = @"로그 파일 열기";
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart in ko-KR (like '
    /// 애플리케이션 다시 시작
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Restart => CrashForm_Restart;
    public const string CrashForm_Restart = @"애플리케이션 다시 시작";
    
    /// <summary>
    /// Get the localized string for CrashForm_Title in ko-KR (like '
    /// {HelperProgram.AppTitle} 충돌 보고서
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Title() => CrashForm_Title();
    public string CrashForm_Title() => @$"{HelperProgram.AppTitle} 충돌 보고서";
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright in ko-KR (like '
    /// © hexadecimal0x12e 2025-{DateTime.Now.Year}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Copyright() => SplashForm_Copyright();
    public string SplashForm_Copyright() => @$"© hexadecimal0x12e 2025-{DateTime.Now.Year}";
    
    /// <summary>
    /// Get the localized string for SplashForm_License in ko-KR (like '
    ///  
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_License() => SplashForm_License();
    public string SplashForm_License() => @$" ";
    
    /// <summary>
    /// Get the localized string for SplashForm_Version in ko-KR (like '
    /// 버전 {HelperProgram.AppVersion}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Version() => SplashForm_Version();
    public string SplashForm_Version() => @$"버전 {HelperProgram.AppVersion}";
    
    /// <summary>
    /// Get the localized string for UnsupportedOSPrompt in ko-KR (like '
    /// 죄송합니다. {HelperProgram.AppTitle}은(는) Windows 10 2004 / LTSC 2021 (build 19041) 이상 버전에서 실행해야 합니다.
    /// 시스템 업그레이드를 고려해 주세요.
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.UnsupportedOSPrompt() => UnsupportedOSPrompt();
    public string UnsupportedOSPrompt() => @$"죄송합니다. {HelperProgram.AppTitle}은(는) Windows 10 2004 / LTSC 2021 (build 19041) 이상 버전에서 실행해야 합니다.시스템 업그레이드를 고려해 주세요.";
    
    /// <summary>
    /// Get the localized string for CorruptedInstallPrompt in ko-KR (like '
    /// 죄송합니다. {HelperProgram.AppTitle} 설치가 손상된 것 같습니다. 애플리케이션을 다시 설치해 보세요.
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CorruptedInstallPrompt() => CorruptedInstallPrompt();
    public string CorruptedInstallPrompt() => @$"죄송합니다. {HelperProgram.AppTitle} 설치가 손상된 것 같습니다. 애플리케이션을 다시 설치해 보세요.";
    
    /// <summary>
    /// Get the current localized Id (like 'k')
    /// </summary>
    string ISimpleLocalizerBase_Helper._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"ko-KR";
    
    
}

#endregion

#region fr_FR
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Helper_fr_FR__ : ISimpleLocalizerBase_Helper
{
    /// <summary>
    /// Get the localized string for AppLoading in fr-FR (like '
    /// Chargement...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.AppLoading => AppLoading;
    public const string AppLoading = @"Chargement...";
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback in fr-FR (like '
    /// Retour d&apos;information
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Feedback => CrashForm_Feedback;
    public const string CrashForm_Feedback = @"Retour d'information";
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog in fr-FR (like '
    /// Ouvrir le fichier journal
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_OpenLog => CrashForm_OpenLog;
    public const string CrashForm_OpenLog = @"Ouvrir le fichier journal";
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart in fr-FR (like '
    /// Redémarrer l&apos;application
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CrashForm_Restart => CrashForm_Restart;
    public const string CrashForm_Restart = @"Redémarrer l'application";
    
    /// <summary>
    /// Get the localized string for CrashForm_Title in fr-FR (like '
    /// {HelperProgram.AppTitle} - Rapport de plantage
    /// ')
    /// </summary>
    /// <remarks>
    /// Titre de la fenêtre de rapport de plantage de l&apos;application. Le nom de l&apos;application est inséré via le paramètre.
    /// </remarks>
    string ISimpleLocalizerBase_Helper.CrashForm_Title() => CrashForm_Title();
    public string CrashForm_Title() => @$"{HelperProgram.AppTitle} - Rapport de plantage";
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright in fr-FR (like '
    /// © hexadecimal0x12e 2025-{DateTime.Now.Year}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Copyright() => SplashForm_Copyright();
    public string SplashForm_Copyright() => @$"© hexadecimal0x12e 2025-{DateTime.Now.Year}";
    
    /// <summary>
    /// Get the localized string for SplashForm_License in fr-FR (like '
    ///  
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_License() => SplashForm_License();
    public string SplashForm_License() => @$" ";
    
    /// <summary>
    /// Get the localized string for SplashForm_Version in fr-FR (like '
    /// Version {HelperProgram.AppVersion}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.SplashForm_Version() => SplashForm_Version();
    public string SplashForm_Version() => @$"Version {HelperProgram.AppVersion}";
    
    /// <summary>
    /// Get the localized string for UnsupportedOSPrompt in fr-FR (like '
    /// Nous sommes désolés, {HelperProgram.AppTitle} nécessite Windows 10 2004 / LTSC 2021 (build 19041) ou une version plus récente pour fonctionner.
    /// Veuillez envisager de mettre à niveau votre système.
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.UnsupportedOSPrompt() => UnsupportedOSPrompt();
    public string UnsupportedOSPrompt() => @$"Nous sommes désolés, {HelperProgram.AppTitle} nécessite Windows 10 2004 / LTSC 2021 (build 19041) ou une version plus récente pour fonctionner.
Veuillez envisager de mettre à niveau votre système.";
    
    /// <summary>
    /// Get the localized string for CorruptedInstallPrompt in fr-FR (like '
    /// Désolé, l&apos;installation de {HelperProgram.AppTitle} semble être corrompue. Veuillez essayer de réinstaller l&apos;application.
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Helper.CorruptedInstallPrompt() => CorruptedInstallPrompt();
    public string CorruptedInstallPrompt() => @$"Désolé, l'installation de {HelperProgram.AppTitle} semble être corrompue. Veuillez essayer de réinstaller l'application.";
    
    /// <summary>
    /// Get the current localized Id (like 'f')
    /// </summary>
    string ISimpleLocalizerBase_Helper._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"fr-FR";
    
    
}

#endregion
public static class SimpleLocalizerBaseGeneratedHelper
{
    /// <summary>
    /// Get the default localizer instance.
    /// </summary>
    /// <remarks>
    /// You need to initialize this property before using it.
    /// </remarks>
    public static ISimpleLocalizerBase_Helper Localized { get; set; } = null!;
}

