// <auto-generated>
// Generated in 2025/12/24 22:44:27
// These code are generated by SimpleLocalizer. Don't modify it directly; modify the 'localized.json' file and regenerate code to apply changes.
// </auto-generated>

#nullable enable
#region usings
using System;
using System.Collections.Concurrent;
using System.CodeDom.Compiler;
using System.Diagnostics;
using projectFrameCut.Helper;
#endregion

#region base interface
/// <summary>
/// This is the base interface for all localizers.
/// </summary>
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
public interface ISimpleLocalizerBase
{
    /// <summary>
    /// Get the localized string for AppLoading (like '
    /// 加载中...
    ///')
    /// </summary>
    public string AppLoading { get; }
    
    /// <summary>
    /// Get the localized string for CrashForm_Title (like '
    /// {HelperProgram.AppTitle} 崩溃报告
    ///')
    /// </summary>
    public string CrashForm_Title();
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart (like '
    /// 重启应用程序
    ///')
    /// </summary>
    public string CrashForm_Restart { get; }
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback (like '
    /// 反馈
    ///')
    /// </summary>
    public string CrashForm_Feedback { get; }
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog (like '
    /// 打开日志文件
    ///')
    /// </summary>
    public string CrashForm_OpenLog { get; }
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright (like '
    /// 版权所有 hexadecimal0x12e 2025-{DateTime.Now.Year}
    ///
    ///')
    /// </summary>
    public string SplashForm_Copyright();
    
    /// <summary>
    /// Get the localized string for SplashForm_Version (like '
    /// 版本 {HelperProgram.AppVersion}
    ///')
    /// </summary>
    public string SplashForm_Version();
    
    /// <summary>
    /// Get the localized string for SplashForm_License (like '
    /// 此版本的 {HelperProgram.AppTitle} 只可用于非商用场景。
    ///')
    /// </summary>
    public string SplashForm_License();
    
    /// <summary>
    /// Get the current Locale's ID (like 'zh-CN')
    /// </summary>
    public string _LocaleId_ { get; }
    
    public static Dictionary<string, ISimpleLocalizerBase> GetMapping()
    {
        return new Dictionary<string, ISimpleLocalizerBase>()
        {
            { "zh-CN", new  __ISimpleLocalizerBase_zh_CN__() },
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="fallbackValue">The fallback value when the localized string isn't found.</param>
    /// <returns>The localized string you want.</returns>
    public string DynamicLookup(string id, string? fallbackValue = null)
    {
        return id switch
        {
            "AppLoading" => AppLoading,
            "CrashForm_Restart" => CrashForm_Restart,
            "CrashForm_Feedback" => CrashForm_Feedback,
            "CrashForm_OpenLog" => CrashForm_OpenLog,
            _ => fallbackValue ?? $"Can't find the localized string for id '{id}'"
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id with some arguments.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="args">The arguments to format the localized string.</param>
    /// <returns>The localized string with arguments applied.</returns>
    /// <exception cref="KeyNotFoundException">The localized string you want with arguments isn't found.</exception>
    /// <exception cref="IndexOutOfRangeException">The number of arguments provided does not match the expected number for the localized string.</exception>
    public string DynamicLookupWithArgs(string id, params object[] args)
    {
        return id switch
        {
            "CrashForm_Title" => CrashForm_Title(),
            "SplashForm_Copyright" => SplashForm_Copyright(),
            "SplashForm_Version" => SplashForm_Version(),
            "SplashForm_License" => SplashForm_License(),
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}' with any argument")
        };
    }
}

#endregion

#region zh_CN
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_zh_CN__ : ISimpleLocalizerBase
{
    /// <summary>
    /// Get the localized string for AppLoading in zh-CN (like '
    /// 加载中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.AppLoading => AppLoading;
    public const string AppLoading = @"加载中...";
    
    /// <summary>
    /// Get the localized string for CrashForm_Title in zh-CN (like '
    /// {HelperProgram.AppTitle} 崩溃报告
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.CrashForm_Title() => CrashForm_Title();
    public string CrashForm_Title() => @$"{HelperProgram.AppTitle} 崩溃报告";
    
    /// <summary>
    /// Get the localized string for CrashForm_Restart in zh-CN (like '
    /// 重启应用程序
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.CrashForm_Restart => CrashForm_Restart;
    public const string CrashForm_Restart = @"重启应用程序";
    
    /// <summary>
    /// Get the localized string for CrashForm_Feedback in zh-CN (like '
    /// 反馈
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.CrashForm_Feedback => CrashForm_Feedback;
    public const string CrashForm_Feedback = @"反馈";
    
    /// <summary>
    /// Get the localized string for CrashForm_OpenLog in zh-CN (like '
    /// 打开日志文件
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.CrashForm_OpenLog => CrashForm_OpenLog;
    public const string CrashForm_OpenLog = @"打开日志文件";
    
    /// <summary>
    /// Get the localized string for SplashForm_Copyright in zh-CN (like '
    /// 版权所有 hexadecimal0x12e 2025-{DateTime.Now.Year}
    ///
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.SplashForm_Copyright() => SplashForm_Copyright();
    public string SplashForm_Copyright() => @$"版权所有 hexadecimal0x12e 2025-{DateTime.Now.Year}";
    
    /// <summary>
    /// Get the localized string for SplashForm_Version in zh-CN (like '
    /// 版本 {HelperProgram.AppVersion}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.SplashForm_Version() => SplashForm_Version();
    public string SplashForm_Version() => @$"版本 {HelperProgram.AppVersion}";
    
    /// <summary>
    /// Get the localized string for SplashForm_License in zh-CN (like '
    /// 此版本的 {HelperProgram.AppTitle} 只可用于非商用场景。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase.SplashForm_License() => SplashForm_License();
    public string SplashForm_License() => @$"此版本的 {HelperProgram.AppTitle} 只可用于非商用场景。";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-CN";
    
    
}

#endregion
public static class SimpleLocalizerBaseGeneratedHelper
{
    /// <summary>
    /// Get the default localizer instance.
    /// </summary>
    /// <remarks>
    /// You need to initialize this property before using it.
    /// </remarks>
    public static ISimpleLocalizerBase Localized { get; set; } = null!;
}

