param(
  [string]$EffectsRoot = "..\projectFrameCut.Render\Effect\",
  [string]$OutDir = ".\Generated",
  [string]$SolutionPath = "..\projectFrameCut.sln"
)

Set-StrictMode -Version Latest
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

function Resolve-Abs([string]$p) {
    try { return (Resolve-Path -Path (Join-Path $scriptDir $p)).ProviderPath } catch { return $null }
}

function Get-ClassFullName([string]$root, [string]$name) {
  # Try common locations to find the .cs file for the effect
  $pathsToTry = @()
  $fileAtRoot = Join-Path $root ($name + '.cs')
  if (Test-Path $fileAtRoot) { $pathsToTry += $fileAtRoot }
  $dirPath = Join-Path $root $name
  if (Test-Path $dirPath) { $pathsToTry += (Get-ChildItem -Path $dirPath -Filter *.cs -File -Recurse -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName) }
  if ($pathsToTry.Count -eq 0) {
    $pathsToTry += (Get-ChildItem -Path $root -Filter *.cs -File -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.BaseName -ieq $name } | Select-Object -ExpandProperty FullName)
  }
  if ($pathsToTry.Count -eq 0) { return $name }

  foreach ($f in $pathsToTry) {
    if (-not (Test-Path $f)) { continue }
    try {
      $txt = Get-Content -Path $f -Raw -ErrorAction Stop
    } catch { continue }

    # find namespace (last one before class)
    $ns = $null
    $nsMatch = [regex]::Match($txt, 'namespace\s+([\w\.]+)')
    if ($nsMatch.Success) { $ns = $nsMatch.Groups[1].Value }

    # prefer public class with same name; otherwise first public class; otherwise first class
    $className = $null
    $m = [regex]::Matches($txt, 'public\s+class\s+([A-Za-z_][A-Za-z0-9_]*)')
    if ($m.Count -gt 0) {
      foreach ($mm in $m) {
        if ($mm.Groups[1].Value -ieq $name) { $className = $mm.Groups[1].Value; break }
      }
      if (-not $className) { $className = $m[0].Groups[1].Value }
    } else {
      $m2 = [regex]::Match($txt, 'class\s+([A-Za-z_][A-Za-z0-9_]*)')
      if ($m2.Success) { $className = $m2.Groups[1].Value }
    }

    if ($className) {
      if ($ns) { return "$ns.$className" } else { return $className }
    }
  }

  return $name
}

$effectsRootAbs = Resolve-Abs $EffectsRoot
if (-not $effectsRootAbs) {
    Write-Host "Effects 根目录未找到: $EffectsRoot"
    exit 0
}

$outDirAbs = Join-Path $scriptDir $OutDir
if (-not (Test-Path $outDirAbs)) { New-Item -Path $outDirAbs -ItemType Directory -Force | Out-Null }

$renderProj = Resolve-Abs "..\projectFrameCut.Render\projectFrameCut.Render.csproj"
$windowsRenderProj = Resolve-Abs "..\projectFrameCut.Render.WindowsRender\projectFrameCut.Render.WindowsRender.csproj"

$effects = @()
Get-ChildItem -Path $effectsRootAbs -Directory -ErrorAction SilentlyContinue | ForEach-Object { $effects += $_.Name }
Get-ChildItem -Path $effectsRootAbs -File -Filter *.cs -ErrorAction SilentlyContinue | ForEach-Object { $effects += ([System.IO.Path]::GetFileNameWithoutExtension($_.Name)) }
$effects = $effects | Sort-Object -Unique

foreach ($name in $effects) {
  $safeName = $name -replace '[^a-zA-Z0-9_.-]','_'
  $projFilename = "projectFrameCut.Benchmarker.$safeName.cs"
  $projPath = Join-Path $outDirAbs $projFilename
  $projDir = Split-Path -Parent $projPath
  $rel = ''
  $rel2 = ''
  if (!(Test-Path $projDir)) { New-Item -Path $projDir -ItemType Directory -Force | Out-Null }

  $projXml = @"
  <Project Sdk="MSTest.Sdk/4.0.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
    <AssemblyName>projectFrameCut.Benchmarker.$safeName</AssemblyName>
    <RootNamespace>projectFrameCut.Benchmarker.$safeName</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
"@

  if ($renderProj) {
    $rel = [System.IO.Path]::GetRelativePath($projDir, $renderProj) -replace '/','\\'
    $projXml += "    <ProjectReference Include='$($rel)' />`r`n"
  }
  if ($windowsRenderProj) {
    $rel2 = [System.IO.Path]::GetRelativePath($projDir, $windowsRenderProj) -replace '/','\\'
    $projXml += "    <ProjectReference Include='$($rel2)' />`r`n"
  }

  $projXml += @"
  </ItemGroup>

</Project>
"@

  # $projXml | Set-Content -Path $projPath -Encoding UTF8

  # create simple test stub

  $testDir = Join-Path $projDir "Tests"
  if (!(Test-Path $testDir)) { New-Item -Path $testDir -ItemType Directory -Force | Out-Null }
  $testFile = Join-Path $testDir ($safeName + "Tests.cs")
  if (!(Test-Path $testFile)) {
    $classFullName = Get-ClassFullName $effectsRootAbs $name
    if ($classFullName -ne "projectFrameCut.Render.Effect.EffectHelper") {
      $testContent = @"
// <auto-generated>
#nullable enable
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace projectFrameCut.Benchmarker.$safeName.Tests
{
    [TestClass]
    public class ${safeName}Tests
    {
        [TestMethod]
        public void Bench()
        {
            new projectFrameCut.Benchmarker.TestRunner<$classFullName>().Run();
        }
    }
}
"@
      $testContent | Set-Content -Path $testFile -Encoding UTF8
    } 
    
  }

  # # add to solution if available
  # $solutionAbs = Resolve-Abs $SolutionPath
  # if ($solutionAbs) {
  #   try {
  #     & dotnet sln $solutionAbs add $projPath | Out-Null
  #   } catch {
  #     Write-Host "dotnet sln add 出错 (可能已存在)： $($_.Exception.Message)"
  #   }
  # } else {
  #   Write-Host "未找到解决方案文件，跳过 sln add: $SolutionPath"
  # }

  Write-Host "生成 $projPath"
}

Write-Host "生成完成：$($effects.Count) 个 Effect 处理完毕."
