<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net11.0;net11.0-android</TargetFrameworks>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net11.0-ios;net11.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net11.0-windows10.0.19041.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' != '' And '$(TargetFramework)' != 'net11.0'">
		<UseMaui>true</UseMaui>
	</PropertyGroup>

	<PropertyGroup Condition="'$(UseMaui)' == ''">
		<UseMaui>false</UseMaui>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\projectFrameCut.ApplicationAPIBase\projectFrameCut.ApplicationAPIBase.csproj" Condition="'$(UseMaui)' == 'true'" />
		<ProjectReference Include="..\projectFrameCut.Render.RenderAPIBase\projectFrameCut.Render.RenderAPIBase.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(UseMaui)' == 'true'">
		<PackageReference Include="Microsoft.Extensions.Logging" Version="$(ExtensionsVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Xaml" Version="$(MauiVersion)" />
		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.1" />
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="10.0.0" />
	</ItemGroup>

</Project>
