// <auto-generated>
// Generated in 2025/11/23 0:38:07
// These code are generated by SimpleLocalizer. Don't modify it directly; modify the 'localized.json' file and regenerate code to apply changes.
// </auto-generated>

#nullable enable
#region usings
using System;
using System.Collections.Concurrent;
using System.CodeDom.Compiler;
using System.Diagnostics;
#endregion

#region base interface
/// <summary>
/// This is the base interface for all localizers.
/// </summary>
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
public interface ISimpleLocalizerBase_Settings
{
    /// <summary>
    /// Get the localized string for CommonStr_Go (like '
    /// 前往页面
    ///')
    /// </summary>
    public string CommonStr_Go { get; }
    
    /// <summary>
    /// Get the localized string for CommonStr_Make (like '
    /// 生成...
    ///')
    /// </summary>
    public string CommonStr_Make { get; }
    
    /// <summary>
    /// Get the localized string for CommonStr_RebootRequired (like '
    /// 要应用这些更改，你需要重启 {Localized.AppBrand}。要现在重启吗？
    ///')
    /// </summary>
    public string CommonStr_RebootRequired();
    
    /// <summary>
    /// Get the localized string for CommonStr_Reset (like '
    /// 重置...
    ///')
    /// </summary>
    public string CommonStr_Reset { get; }
    
    /// <summary>
    /// Get the localized string for CommonStr_Select (like '
    /// 选择...
    ///')
    /// </summary>
    public string CommonStr_Select { get; }
    
    /// <summary>
    /// Get the localized string for CommonStr_Sure (like '
    /// 此操作({name})存在风险，要继续吗?
    ///')
    /// </summary>
    public string CommonStr_Sure(string name);
    
    /// <summary>
    /// Get the localized string for General_Language (like '
    /// 语言/Language
    ///')
    /// </summary>
    /// <remarks>
    /// 翻译时请始终保留他的/Language后缀
    /// </remarks>
    public string General_Language { get; }
    
    /// <summary>
    /// Get the localized string for General_UserData (like '
    /// 数据与配置管理
    ///')
    /// </summary>
    public string General_UserData { get; }
    
    /// <summary>
    /// Get the localized string for General_UserData_ManagePageOpen (like '
    /// 管理用户数据
    ///')
    /// </summary>
    public string General_UserData_ManagePageOpen { get; }
    
    /// <summary>
    /// Get the localized string for General_UserData_Path (like '
    /// 用户数据目录
    ///')
    /// </summary>
    public string General_UserData_Path { get; }
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_Confirm (like '
    /// 确认要把用户数据目录设置为「{path}」吗？
    ///')
    /// </summary>
    public string General_UserData_SelectFolder_Confirm(string path);
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmButton (like '
    /// 点击这里选择，或者选择边上的“取消”来恢复到默认路径
    ///')
    /// </summary>
    public string General_UserData_SelectFolder_ConfirmButton { get; }
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmMigrateData (like '
    /// 是否要迁移已有的数据？
    ///')
    /// </summary>
    public string General_UserData_SelectFolder_ConfirmMigrateData { get; }
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmReset (like '
    /// 确认要把用户数据恢复为默认值吗？
    ///')
    /// </summary>
    public string General_UserData_SelectFolder_ConfirmReset { get; }
    
    /// <summary>
    /// Get the localized string for Misc_DebugMode (like '
    /// 开发者模式
    ///')
    /// </summary>
    public string Misc_DebugMode { get; }
    
    /// <summary>
    /// Get the localized string for Misc_MakeDiagReport (like '
    /// 生成诊断报告
    ///')
    /// </summary>
    public string Misc_MakeDiagReport { get; }
    
    /// <summary>
    /// Get the localized string for Misc_ResetSettings (like '
    /// 重置所有的设置
    ///')
    /// </summary>
    public string Misc_ResetSettings { get; }
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsNotSupported (like '
    /// 抱歉，你的平台不支持配置硬件加速。
    ///')
    /// </summary>
    public string Render_AccelOptsNotSupported { get; }
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsSubTitle (like '
    /// 管理硬件加速的配置
    ///')
    /// </summary>
    public string Render_AccelOptsSubTitle { get; }
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsTitle (like '
    /// 硬件加速
    ///')
    /// </summary>
    public string Render_AccelOptsTitle { get; }
    
    /// <summary>
    /// Get the localized string for Render_EnableMultiAccel (like '
    /// 启用多加速器（仅限渲染）
    ///')
    /// </summary>
    public string Render_EnableMultiAccel { get; }
    
    /// <summary>
    /// Get the localized string for Render_LoadingAccels (like '
    /// 获取可用的加速器中...
    ///')
    /// </summary>
    public string Render_LoadingAccels { get; }
    
    /// <summary>
    /// Get the localized string for Render_SelectAccel (like '
    /// 选择用于渲染/编辑时硬件加速的GPU
    ///')
    /// </summary>
    public string Render_SelectAccel { get; }
    
    /// <summary>
    /// Get the current Locale's ID (like 'zh-CN')
    /// </summary>
    public string _LocaleId_ { get; }
    
    public static Dictionary<string, ISimpleLocalizerBase_Settings> GetMapping()
    {
        return new Dictionary<string, ISimpleLocalizerBase_Settings>()
        {
            { "zh-CN", new  __ISimpleLocalizerBase_Settings_zh_CN__() },
            { "en-US", new  __ISimpleLocalizerBase_Settings_en_US__() },
            { "zh-TW", new  __ISimpleLocalizerBase_Settings_zh_TW__() },
            { "ja-JP", new  __ISimpleLocalizerBase_Settings_ja_JP__() },
            { "ko-KR", new  __ISimpleLocalizerBase_Settings_ko_KR__() },
            { "fr-FR", new  __ISimpleLocalizerBase_Settings_fr_FR__() },
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <returns>The localized string you want.</returns>
    /// <exception cref="KeyNotFoundException">The localized string you want with no argument isn't found.</exception>
    public string DynamicLookup(string id)
    {
        return id switch
        {
            "CommonStr_Go" => CommonStr_Go,
            "CommonStr_Make" => CommonStr_Make,
            "CommonStr_Reset" => CommonStr_Reset,
            "CommonStr_Select" => CommonStr_Select,
            "General_Language" => General_Language,
            "General_UserData" => General_UserData,
            "General_UserData_ManagePageOpen" => General_UserData_ManagePageOpen,
            "General_UserData_Path" => General_UserData_Path,
            "General_UserData_SelectFolder_ConfirmButton" => General_UserData_SelectFolder_ConfirmButton,
            "General_UserData_SelectFolder_ConfirmMigrateData" => General_UserData_SelectFolder_ConfirmMigrateData,
            "General_UserData_SelectFolder_ConfirmReset" => General_UserData_SelectFolder_ConfirmReset,
            "Misc_DebugMode" => Misc_DebugMode,
            "Misc_MakeDiagReport" => Misc_MakeDiagReport,
            "Misc_ResetSettings" => Misc_ResetSettings,
            "Render_AccelOptsNotSupported" => Render_AccelOptsNotSupported,
            "Render_AccelOptsSubTitle" => Render_AccelOptsSubTitle,
            "Render_AccelOptsTitle" => Render_AccelOptsTitle,
            "Render_EnableMultiAccel" => Render_EnableMultiAccel,
            "Render_LoadingAccels" => Render_LoadingAccels,
            "Render_SelectAccel" => Render_SelectAccel,
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}'")
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id with some arguments.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="args">The arguments to format the localized string.</param>
    /// <returns>The localized string with arguments applied.</returns>
    /// <exception cref="KeyNotFoundException">The localized string you want with arguments isn't found.</exception>
    /// <exception cref="IndexOutOfRangeException">The number of arguments provided does not match the expected number for the localized string.</exception>
    public string DynamicLookupWithArgs(string id, params object[] args)
    {
        return id switch
        {
            "CommonStr_RebootRequired" => CommonStr_RebootRequired(),
            "CommonStr_Sure" => CommonStr_Sure((string)args[0]),
            "General_UserData_SelectFolder_Confirm" => General_UserData_SelectFolder_Confirm((string)args[0]),
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}' with any argument")
        };
    }
}

#endregion

#region zh_CN
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Settings_zh_CN__ : ISimpleLocalizerBase_Settings
{
    /// <summary>
    /// Get the localized string for CommonStr_Go in zh-CN (like '
    /// 前往页面
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Go => CommonStr_Go;
    public const string CommonStr_Go = @"前往页面";
    
    /// <summary>
    /// Get the localized string for CommonStr_Make in zh-CN (like '
    /// 生成...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Make => CommonStr_Make;
    public const string CommonStr_Make = @"生成...";
    
    /// <summary>
    /// Get the localized string for CommonStr_RebootRequired in zh-CN (like '
    /// 要应用这些更改，你需要重启 {Localized.AppBrand}。要现在重启吗？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_RebootRequired() => CommonStr_RebootRequired();
    public string CommonStr_RebootRequired() => @$"要应用这些更改，你需要重启 {Localized.AppBrand}。要现在重启吗？";
    
    /// <summary>
    /// Get the localized string for CommonStr_Reset in zh-CN (like '
    /// 重置...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Reset => CommonStr_Reset;
    public const string CommonStr_Reset = @"重置...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Select in zh-CN (like '
    /// 选择...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Select => CommonStr_Select;
    public const string CommonStr_Select = @"选择...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Sure in zh-CN (like '
    /// 此操作({name})存在风险，要继续吗?
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Sure(string name) => CommonStr_Sure(name);
    public string CommonStr_Sure(string name) => @$"此操作({name})存在风险，要继续吗?";
    
    /// <summary>
    /// Get the localized string for General_Language in zh-CN (like '
    /// 语言/Language
    /// ')
    /// </summary>
    /// <remarks>
    /// 翻译时请始终保留他的/Language后缀
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_Language => General_Language;
    public const string General_Language = @"语言/Language";
    
    /// <summary>
    /// Get the localized string for General_UserData in zh-CN (like '
    /// 数据与配置管理
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData => General_UserData;
    public const string General_UserData = @"数据与配置管理";
    
    /// <summary>
    /// Get the localized string for General_UserData_ManagePageOpen in zh-CN (like '
    /// 管理用户数据
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_ManagePageOpen => General_UserData_ManagePageOpen;
    public const string General_UserData_ManagePageOpen = @"管理用户数据";
    
    /// <summary>
    /// Get the localized string for General_UserData_Path in zh-CN (like '
    /// 用户数据目录
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_Path => General_UserData_Path;
    public const string General_UserData_Path = @"用户数据目录";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_Confirm in zh-CN (like '
    /// 确认要把用户数据目录设置为「{path}」吗？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_Confirm(string path) => General_UserData_SelectFolder_Confirm(path);
    public string General_UserData_SelectFolder_Confirm(string path) => @$"确认要把用户数据目录设置为「{path}」吗？";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmButton in zh-CN (like '
    /// 点击这里选择，或者选择边上的“取消”来恢复到默认路径
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmButton => General_UserData_SelectFolder_ConfirmButton;
    public const string General_UserData_SelectFolder_ConfirmButton = @"点击这里选择，或者选择边上的“取消”来恢复到默认路径";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmMigrateData in zh-CN (like '
    /// 是否要迁移已有的数据？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmMigrateData => General_UserData_SelectFolder_ConfirmMigrateData;
    public const string General_UserData_SelectFolder_ConfirmMigrateData = @"是否要迁移已有的数据？";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmReset in zh-CN (like '
    /// 确认要把用户数据恢复为默认值吗？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmReset => General_UserData_SelectFolder_ConfirmReset;
    public const string General_UserData_SelectFolder_ConfirmReset = @"确认要把用户数据恢复为默认值吗？";
    
    /// <summary>
    /// Get the localized string for Misc_DebugMode in zh-CN (like '
    /// 开发者模式
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_DebugMode => Misc_DebugMode;
    public const string Misc_DebugMode = @"开发者模式";
    
    /// <summary>
    /// Get the localized string for Misc_MakeDiagReport in zh-CN (like '
    /// 生成诊断报告
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_MakeDiagReport => Misc_MakeDiagReport;
    public const string Misc_MakeDiagReport = @"生成诊断报告";
    
    /// <summary>
    /// Get the localized string for Misc_ResetSettings in zh-CN (like '
    /// 重置所有的设置
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_ResetSettings => Misc_ResetSettings;
    public const string Misc_ResetSettings = @"重置所有的设置";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsNotSupported in zh-CN (like '
    /// 抱歉，你的平台不支持配置硬件加速。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsNotSupported => Render_AccelOptsNotSupported;
    public const string Render_AccelOptsNotSupported = @"抱歉，你的平台不支持配置硬件加速。";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsSubTitle in zh-CN (like '
    /// 管理硬件加速的配置
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsSubTitle => Render_AccelOptsSubTitle;
    public const string Render_AccelOptsSubTitle = @"管理硬件加速的配置";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsTitle in zh-CN (like '
    /// 硬件加速
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsTitle => Render_AccelOptsTitle;
    public const string Render_AccelOptsTitle = @"硬件加速";
    
    /// <summary>
    /// Get the localized string for Render_EnableMultiAccel in zh-CN (like '
    /// 启用多加速器（仅限渲染）
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_EnableMultiAccel => Render_EnableMultiAccel;
    public const string Render_EnableMultiAccel = @"启用多加速器（仅限渲染）";
    
    /// <summary>
    /// Get the localized string for Render_LoadingAccels in zh-CN (like '
    /// 获取可用的加速器中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_LoadingAccels => Render_LoadingAccels;
    public const string Render_LoadingAccels = @"获取可用的加速器中...";
    
    /// <summary>
    /// Get the localized string for Render_SelectAccel in zh-CN (like '
    /// 选择用于渲染/编辑时硬件加速的GPU
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_SelectAccel => Render_SelectAccel;
    public const string Render_SelectAccel = @"选择用于渲染/编辑时硬件加速的GPU";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase_Settings._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-CN";
    
    
}

#endregion

#region en_US
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Settings_en_US__ : ISimpleLocalizerBase_Settings
{
    /// <summary>
    /// Get the localized string for CommonStr_Go in en-US (like '
    /// Go to page
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Go => CommonStr_Go;
    public const string CommonStr_Go = @"Go to page";
    
    /// <summary>
    /// Get the localized string for CommonStr_Make in en-US (like '
    /// Generating...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Make => CommonStr_Make;
    public const string CommonStr_Make = @"Generating...";
    
    /// <summary>
    /// Get the localized string for CommonStr_RebootRequired in en-US (like '
    /// To apply these changes, you need to restart {Localized.AppBrand}. Restart now?
    /// ')
    /// </summary>
    /// <remarks>
    /// Prompt asking user to restart the application to apply changes
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_RebootRequired() => CommonStr_RebootRequired();
    public string CommonStr_RebootRequired() => @$"To apply these changes, you need to restart {Localized.AppBrand}. Restart now?";
    
    /// <summary>
    /// Get the localized string for CommonStr_Reset in en-US (like '
    /// Resetting...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Reset => CommonStr_Reset;
    public const string CommonStr_Reset = @"Resetting...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Select in en-US (like '
    /// Select...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Select => CommonStr_Select;
    public const string CommonStr_Select = @"Select...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Sure in en-US (like '
    /// This operation ({name}) involves risks. Would you like to continue?
    /// ')
    /// </summary>
    /// <remarks>
    /// Warning text for risk confirmation dialog
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_Sure(string name) => CommonStr_Sure(name);
    public string CommonStr_Sure(string name) => @$"This operation ({name}) involves risks. Would you like to continue?";
    
    /// <summary>
    /// Get the localized string for General_Language in en-US (like '
    /// Language/Language
    /// ')
    /// </summary>
    /// <remarks>
    /// Translated the Chinese part while preserving the &apos;/Language&apos; suffix as instructed
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_Language => General_Language;
    public const string General_Language = @"Language/Language";
    
    /// <summary>
    /// Get the localized string for General_UserData in en-US (like '
    /// Data and Configuration Management
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData => General_UserData;
    public const string General_UserData = @"Data and Configuration Management";
    
    /// <summary>
    /// Get the localized string for General_UserData_ManagePageOpen in en-US (like '
    /// Manage User Data
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_ManagePageOpen => General_UserData_ManagePageOpen;
    public const string General_UserData_ManagePageOpen = @"Manage User Data";
    
    /// <summary>
    /// Get the localized string for General_UserData_Path in en-US (like '
    /// User Data Directory
    /// ')
    /// </summary>
    /// <remarks>
    /// Refers to the directory where user data is stored
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_Path => General_UserData_Path;
    public const string General_UserData_Path = @"User Data Directory";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_Confirm in en-US (like '
    /// Confirm setting the user data directory to &quot;{path}&quot;?
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_Confirm(string path) => General_UserData_SelectFolder_Confirm(path);
    public string General_UserData_SelectFolder_Confirm(string path) => 
$""""
Confirm setting the user data directory to "{path}"?
"""";

    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmButton in en-US (like '
    /// Click here to select, or choose &quot;Cancel&quot; nearby to revert to the default path
    /// ')
    /// </summary>
    /// <remarks>
    /// Instruction for folder selection confirmation button
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmButton => General_UserData_SelectFolder_ConfirmButton;
    public const string General_UserData_SelectFolder_ConfirmButton = """"Click here to select, or choose "Cancel" nearby to revert to the default path"""";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmMigrateData in en-US (like '
    /// Do you want to migrate existing data?
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmMigrateData => General_UserData_SelectFolder_ConfirmMigrateData;
    public const string General_UserData_SelectFolder_ConfirmMigrateData = @"Do you want to migrate existing data?";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmReset in en-US (like '
    /// Are you sure you want to reset user data to default values?
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmReset => General_UserData_SelectFolder_ConfirmReset;
    public const string General_UserData_SelectFolder_ConfirmReset = @"Are you sure you want to reset user data to default values?";
    
    /// <summary>
    /// Get the localized string for Misc_DebugMode in en-US (like '
    /// Developer Mode
    /// ')
    /// </summary>
    /// <remarks>
    /// Translation of &apos;开发者模式&apos; to indicate a special mode for developers with debugging features.
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Misc_DebugMode => Misc_DebugMode;
    public const string Misc_DebugMode = @"Developer Mode";
    
    /// <summary>
    /// Get the localized string for Misc_MakeDiagReport in en-US (like '
    /// Generate Diagnostic Report
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_MakeDiagReport => Misc_MakeDiagReport;
    public const string Misc_MakeDiagReport = @"Generate Diagnostic Report";
    
    /// <summary>
    /// Get the localized string for Misc_ResetSettings in en-US (like '
    /// Reset all settings
    /// ')
    /// </summary>
    /// <remarks>
    /// Button/label text for restoring all configurations to default values
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Misc_ResetSettings => Misc_ResetSettings;
    public const string Misc_ResetSettings = @"Reset all settings";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsSubTitle in en-US (like '
    /// Manage hardware acceleration configurations
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsSubTitle => Render_AccelOptsSubTitle;
    public const string Render_AccelOptsSubTitle = @"Manage hardware acceleration configurations";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsTitle in en-US (like '
    /// Hardware Acceleration
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsTitle => Render_AccelOptsTitle;
    public const string Render_AccelOptsTitle = @"Hardware Acceleration";
    
    /// <summary>
    /// Get the localized string for Render_EnableMultiAccel in en-US (like '
    /// Enable Multi-Accelerator (Render Only)
    /// ')
    /// </summary>
    /// <remarks>
    /// Activates multiple accelerators specifically for rendering purposes
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_EnableMultiAccel => Render_EnableMultiAccel;
    public const string Render_EnableMultiAccel = @"Enable Multi-Accelerator (Render Only)";
    
    /// <summary>
    /// Get the localized string for Render_SelectAccel in en-US (like '
    /// Select GPU for hardware acceleration during rendering/editing
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_SelectAccel => Render_SelectAccel;
    public const string Render_SelectAccel = @"Select GPU for hardware acceleration during rendering/editing";
    
    /// <summary>
    /// Get the localized string for Render_LoadingAccels in en-US (like '
    /// Loading available accelerators...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_LoadingAccels => Render_LoadingAccels;
    public const string Render_LoadingAccels = @"Loading available accelerators...";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsNotSupported in en-US (like '
    /// Sorry, your platform does not support hardware acceleration configuration.
    /// ')
    /// </summary>
    /// <remarks>
    /// Informs the user that their system cannot enable hardware acceleration options
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsNotSupported => Render_AccelOptsNotSupported;
    public const string Render_AccelOptsNotSupported = @"Sorry, your platform does not support hardware acceleration configuration.";
    
    /// <summary>
    /// Get the current localized Id (like 'e')
    /// </summary>
    string ISimpleLocalizerBase_Settings._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"en-US";
    
    
}

#endregion

#region zh_TW
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Settings_zh_TW__ : ISimpleLocalizerBase_Settings
{
    /// <summary>
    /// Get the localized string for CommonStr_Go in zh-TW (like '
    /// 前往頁面
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Go => CommonStr_Go;
    public const string CommonStr_Go = @"前往頁面";
    
    /// <summary>
    /// Get the localized string for CommonStr_Make in zh-TW (like '
    /// 產生中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Make => CommonStr_Make;
    public const string CommonStr_Make = @"產生中...";
    
    /// <summary>
    /// Get the localized string for CommonStr_RebootRequired in zh-TW (like '
    /// 要套用這些變更，您需要重新啟動 {Localized.AppBrand}。是否立即重新啟動？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_RebootRequired() => CommonStr_RebootRequired();
    public string CommonStr_RebootRequired() => @$"要套用這些變更，您需要重新啟動 {Localized.AppBrand}。是否立即重新啟動？";
    
    /// <summary>
    /// Get the localized string for CommonStr_Reset in zh-TW (like '
    /// 重置...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Reset => CommonStr_Reset;
    public const string CommonStr_Reset = @"重置...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Select in zh-TW (like '
    /// 選擇...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Select => CommonStr_Select;
    public const string CommonStr_Select = @"選擇...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Sure in zh-TW (like '
    /// 此操作({name})存在風險，要繼續嗎？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Sure(string name) => CommonStr_Sure(name);
    public string CommonStr_Sure(string name) => @$"此操作({name})存在風險，要繼續嗎？";
    
    /// <summary>
    /// Get the localized string for General_Language in zh-TW (like '
    /// 語言/Language
    /// ')
    /// </summary>
    /// <remarks>
    /// 保持原文的后缀格式，仅转换简体中文部分为繁体中文
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_Language => General_Language;
    public const string General_Language = @"語言/Language";
    
    /// <summary>
    /// Get the localized string for General_UserData in zh-TW (like '
    /// 數據與配置管理
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData => General_UserData;
    public const string General_UserData = @"數據與配置管理";
    
    /// <summary>
    /// Get the localized string for General_UserData_ManagePageOpen in zh-TW (like '
    /// 管理使用者資料
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_ManagePageOpen => General_UserData_ManagePageOpen;
    public const string General_UserData_ManagePageOpen = @"管理使用者資料";
    
    /// <summary>
    /// Get the localized string for General_UserData_Path in zh-TW (like '
    /// 使用者資料目錄
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_Path => General_UserData_Path;
    public const string General_UserData_Path = @"使用者資料目錄";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_Confirm in zh-TW (like '
    /// 確認要把使用者資料目錄設定為「{path}」嗎？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_Confirm(string path) => General_UserData_SelectFolder_Confirm(path);
    public string General_UserData_SelectFolder_Confirm(string path) => @$"確認要把使用者資料目錄設定為「{path}」嗎？";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmButton in zh-TW (like '
    /// 點選這裡選擇，或是選擇旁邊的「取消」來還原到預設路徑
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmButton => General_UserData_SelectFolder_ConfirmButton;
    public const string General_UserData_SelectFolder_ConfirmButton = @"點選這裡選擇，或是選擇旁邊的「取消」來還原到預設路徑";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmMigrateData in zh-TW (like '
    /// 是否要遷移現有的資料？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmMigrateData => General_UserData_SelectFolder_ConfirmMigrateData;
    public const string General_UserData_SelectFolder_ConfirmMigrateData = @"是否要遷移現有的資料？";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmReset in zh-TW (like '
    /// 確認要把用戶資料恢復為預設值嗎？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmReset => General_UserData_SelectFolder_ConfirmReset;
    public const string General_UserData_SelectFolder_ConfirmReset = @"確認要把用戶資料恢復為預設值嗎？";
    
    /// <summary>
    /// Get the localized string for Misc_DebugMode in zh-TW (like '
    /// 開發者模式
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_DebugMode => Misc_DebugMode;
    public const string Misc_DebugMode = @"開發者模式";
    
    /// <summary>
    /// Get the localized string for Misc_MakeDiagReport in zh-TW (like '
    /// 生成診斷報告
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_MakeDiagReport => Misc_MakeDiagReport;
    public const string Misc_MakeDiagReport = @"生成診斷報告";
    
    /// <summary>
    /// Get the localized string for Misc_ResetSettings in zh-TW (like '
    /// 重設所有的設定
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_ResetSettings => Misc_ResetSettings;
    public const string Misc_ResetSettings = @"重設所有的設定";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsSubTitle in zh-TW (like '
    /// 管理硬體加速的配置
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsSubTitle => Render_AccelOptsSubTitle;
    public const string Render_AccelOptsSubTitle = @"管理硬體加速的配置";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsTitle in zh-TW (like '
    /// 硬體加速
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsTitle => Render_AccelOptsTitle;
    public const string Render_AccelOptsTitle = @"硬體加速";
    
    /// <summary>
    /// Get the localized string for Render_EnableMultiAccel in zh-TW (like '
    /// 啟用多加速器（僅限渲染）
    /// ')
    /// </summary>
    /// <remarks>
    /// 將簡體中文術語轉換為繁體中文，保持技術術語準確性。「渲染」為計算機圖形學標準譯名，「加速器」在此上下文指硬體加速功能。
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_EnableMultiAccel => Render_EnableMultiAccel;
    public const string Render_EnableMultiAccel = @"啟用多加速器（僅限渲染）";
    
    /// <summary>
    /// Get the localized string for Render_SelectAccel in zh-TW (like '
    /// 選取用於渲染/編輯時硬體加速的GPU
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_SelectAccel => Render_SelectAccel;
    public const string Render_SelectAccel = @"選取用於渲染/編輯時硬體加速的GPU";
    
    /// <summary>
    /// Get the localized string for Render_LoadingAccels in zh-TW (like '
    /// 正在取得可用的加速器中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_LoadingAccels => Render_LoadingAccels;
    public const string Render_LoadingAccels = @"正在取得可用的加速器中...";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsNotSupported in zh-TW (like '
    /// 對不起，你的平台不支援配置硬體加速。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsNotSupported => Render_AccelOptsNotSupported;
    public const string Render_AccelOptsNotSupported = @"對不起，你的平台不支援配置硬體加速。";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase_Settings._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-TW";
    
    
}

#endregion

#region ja_JP
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Settings_ja_JP__ : ISimpleLocalizerBase_Settings
{
    /// <summary>
    /// Get the localized string for CommonStr_Go in ja-JP (like '
    /// ページに進む
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Go => CommonStr_Go;
    public const string CommonStr_Go = @"ページに進む";
    
    /// <summary>
    /// Get the localized string for CommonStr_Make in ja-JP (like '
    /// 生成中...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Make => CommonStr_Make;
    public const string CommonStr_Make = @"生成中...";
    
    /// <summary>
    /// Get the localized string for CommonStr_RebootRequired in ja-JP (like '
    /// これらの変更を適用するには、{Localized.AppBrand}を再起動する必要があります。今すぐ再起動しますか？
    /// ')
    /// </summary>
    /// <remarks>
    /// Changes require restart - asking user to confirm immediate restart
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_RebootRequired() => CommonStr_RebootRequired();
    public string CommonStr_RebootRequired() => @$"これらの変更を適用するには、{Localized.AppBrand}を再起動する必要があります。今すぐ再起動しますか？";
    
    /// <summary>
    /// Get the localized string for CommonStr_Reset in ja-JP (like '
    /// リセット...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Reset => CommonStr_Reset;
    public const string CommonStr_Reset = @"リセット...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Select in ja-JP (like '
    /// 選択...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Select => CommonStr_Select;
    public const string CommonStr_Select = @"選択...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Sure in ja-JP (like '
    /// この操作({name})にはリスクがあります。続行しますか？
    /// ')
    /// </summary>
    /// <remarks>
    /// Risk warning for operation confirmation
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_Sure(string name) => CommonStr_Sure(name);
    public string CommonStr_Sure(string name) => @$"この操作({name})にはリスクがあります。続行しますか？";
    
    /// <summary>
    /// Get the localized string for General_Language in ja-JP (like '
    /// 言語/Language
    /// ')
    /// </summary>
    /// <remarks>
    /// Translation of &apos;Language&apos; with preserved &apos;/Language&apos; suffix as requested
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_Language => General_Language;
    public const string General_Language = @"言語/Language";
    
    /// <summary>
    /// Get the localized string for General_UserData in ja-JP (like '
    /// データと設定の管理
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData => General_UserData;
    public const string General_UserData = @"データと設定の管理";
    
    /// <summary>
    /// Get the localized string for General_UserData_ManagePageOpen in ja-JP (like '
    /// ユーザーデータの管理
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_ManagePageOpen => General_UserData_ManagePageOpen;
    public const string General_UserData_ManagePageOpen = @"ユーザーデータの管理";
    
    /// <summary>
    /// Get the localized string for General_UserData_Path in ja-JP (like '
    /// ユーザーデータディレクトリ
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_Path => General_UserData_Path;
    public const string General_UserData_Path = @"ユーザーデータディレクトリ";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_Confirm in ja-JP (like '
    /// ユーザーデータディレクトリを「{path}」に設定しますか？
    /// ')
    /// </summary>
    /// <remarks>
    /// User data directory setting confirmation prompt
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_Confirm(string path) => General_UserData_SelectFolder_Confirm(path);
    public string General_UserData_SelectFolder_Confirm(string path) => @$"ユーザーデータディレクトリを「{path}」に設定しますか？";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmButton in ja-JP (like '
    /// ここをクリックして選択、または隣の「キャンセル」で既定のパスに戻ります
    /// ')
    /// </summary>
    /// <remarks>
    /// フォルダ選択確認ボタンの操作説明
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmButton => General_UserData_SelectFolder_ConfirmButton;
    public const string General_UserData_SelectFolder_ConfirmButton = @"ここをクリックして選択、または隣の「キャンセル」で既定のパスに戻ります";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmMigrateData in ja-JP (like '
    /// 既存のデータを移行しますか？
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmMigrateData => General_UserData_SelectFolder_ConfirmMigrateData;
    public const string General_UserData_SelectFolder_ConfirmMigrateData = @"既存のデータを移行しますか？";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmReset in ja-JP (like '
    /// ユーザーデータをデフォルト値に復元しますか？
    /// ')
    /// </summary>
    /// <remarks>
    /// Confirm resetting user data to default values
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmReset => General_UserData_SelectFolder_ConfirmReset;
    public const string General_UserData_SelectFolder_ConfirmReset = @"ユーザーデータをデフォルト値に復元しますか？";
    
    /// <summary>
    /// Get the localized string for Misc_DebugMode in ja-JP (like '
    /// 開発者モード
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_DebugMode => Misc_DebugMode;
    public const string Misc_DebugMode = @"開発者モード";
    
    /// <summary>
    /// Get the localized string for Misc_MakeDiagReport in ja-JP (like '
    /// 診断レポートを生成
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_MakeDiagReport => Misc_MakeDiagReport;
    public const string Misc_MakeDiagReport = @"診断レポートを生成";
    
    /// <summary>
    /// Get the localized string for Misc_ResetSettings in ja-JP (like '
    /// すべての設定をリセット
    /// ')
    /// </summary>
    /// <remarks>
    /// Reset all settings to their default values
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Misc_ResetSettings => Misc_ResetSettings;
    public const string Misc_ResetSettings = @"すべての設定をリセット";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsSubTitle in ja-JP (like '
    /// ハードウェアアクセラレーション設定の管理
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsSubTitle => Render_AccelOptsSubTitle;
    public const string Render_AccelOptsSubTitle = @"ハードウェアアクセラレーション設定の管理";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsTitle in ja-JP (like '
    /// ハードウェアアクセラレーション
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsTitle => Render_AccelOptsTitle;
    public const string Render_AccelOptsTitle = @"ハードウェアアクセラレーション";
    
    /// <summary>
    /// Get the localized string for Render_EnableMultiAccel in ja-JP (like '
    /// マルチアクセラレータを有効化（レンダリングのみ）
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_EnableMultiAccel => Render_EnableMultiAccel;
    public const string Render_EnableMultiAccel = @"マルチアクセラレータを有効化（レンダリングのみ）";
    
    /// <summary>
    /// Get the localized string for Render_SelectAccel in ja-JP (like '
    /// レンダリング/編集時のハードウェアアクセラレーションに使用するGPUを選択
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_SelectAccel => Render_SelectAccel;
    public const string Render_SelectAccel = @"レンダリング/編集時のハードウェアアクセラレーションに使用するGPUを選択";
    
    /// <summary>
    /// Get the localized string for Render_LoadingAccels in ja-JP (like '
    /// 利用可能なアクセラレーターを取得中...
    /// ')
    /// </summary>
    /// <remarks>
    /// Loading available accelerators
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_LoadingAccels => Render_LoadingAccels;
    public const string Render_LoadingAccels = @"利用可能なアクセラレーターを取得中...";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsNotSupported in ja-JP (like '
    /// 申し訳ございませんが、お使いのプラットフォームはハードウェアアクセラレーションの設定をサポートしていません。
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsNotSupported => Render_AccelOptsNotSupported;
    public const string Render_AccelOptsNotSupported = @"申し訳ございませんが、お使いのプラットフォームはハードウェアアクセラレーションの設定をサポートしていません。";
    
    /// <summary>
    /// Get the current localized Id (like 'j')
    /// </summary>
    string ISimpleLocalizerBase_Settings._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"ja-JP";
    
    
}

#endregion

#region ko_KR
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Settings_ko_KR__ : ISimpleLocalizerBase_Settings
{
    /// <summary>
    /// Get the localized string for CommonStr_Go in ko-KR (like '
    /// 페이지로 이동
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Go => CommonStr_Go;
    public const string CommonStr_Go = @"페이지로 이동";
    
    /// <summary>
    /// Get the localized string for CommonStr_Make in ko-KR (like '
    /// 생성 중...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Make => CommonStr_Make;
    public const string CommonStr_Make = @"생성 중...";
    
    /// <summary>
    /// Get the localized string for CommonStr_RebootRequired in ko-KR (like '
    /// 이 변경 사항을 적용하려면 {Localized.AppBrand}를 재시작해야 합니다. 지금 재시작하시겠습니까?
    /// ')
    /// </summary>
    /// <remarks>
    /// App rebooting prompt for applying changes
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_RebootRequired() => CommonStr_RebootRequired();
    public string CommonStr_RebootRequired() => @$"이 변경 사항을 적용하려면 {Localized.AppBrand}를 재시작해야 합니다. 지금 재시작하시겠습니까?";
    
    /// <summary>
    /// Get the localized string for CommonStr_Reset in ko-KR (like '
    /// 재설정 중...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Reset => CommonStr_Reset;
    public const string CommonStr_Reset = @"재설정 중...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Select in ko-KR (like '
    /// 선택...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Select => CommonStr_Select;
    public const string CommonStr_Select = @"선택...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Sure in ko-KR (like '
    /// 이 작업({name})에는 위험이 있습니다. 계속하시겠습니까?
    /// ')
    /// </summary>
    /// <remarks>
    /// Risk warning prompt for user confirmation
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_Sure(string name) => CommonStr_Sure(name);
    public string CommonStr_Sure(string name) => @$"이 작업({name})에는 위험이 있습니다. 계속하시겠습니까?";
    
    /// <summary>
    /// Get the localized string for General_Language in ko-KR (like '
    /// 언어/Language
    /// ')
    /// </summary>
    /// <remarks>
    /// Translation of &apos;Language&apos; while preserving the &apos;/Language&apos; suffix as requested
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_Language => General_Language;
    public const string General_Language = @"언어/Language";
    
    /// <summary>
    /// Get the localized string for General_UserData in ko-KR (like '
    /// 데이터 및 설정 관리
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData => General_UserData;
    public const string General_UserData = @"데이터 및 설정 관리";
    
    /// <summary>
    /// Get the localized string for General_UserData_ManagePageOpen in ko-KR (like '
    /// 사용자 데이터 관리
    /// ')
    /// </summary>
    /// <remarks>
    /// 사용자 데이터 관리 페이지를 나타내는 제목
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_ManagePageOpen => General_UserData_ManagePageOpen;
    public const string General_UserData_ManagePageOpen = @"사용자 데이터 관리";
    
    /// <summary>
    /// Get the localized string for General_UserData_Path in ko-KR (like '
    /// 사용자 데이터 디렉토리
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_Path => General_UserData_Path;
    public const string General_UserData_Path = @"사용자 데이터 디렉토리";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_Confirm in ko-KR (like '
    /// 사용자 데이터 폴더를 &apos;{path}&apos;로 설정하시겠습니까?
    /// ')
    /// </summary>
    /// <remarks>
    /// Asks for confirmation to set the user data directory to the specified path
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_Confirm(string path) => General_UserData_SelectFolder_Confirm(path);
    public string General_UserData_SelectFolder_Confirm(string path) => @$"사용자 데이터 폴더를 '{path}'로 설정하시겠습니까?";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmButton in ko-KR (like '
    /// 여기를 클릭하여 선택하거나 옆의 &apos;취소&apos;를 선택하여 기본 경로로 복원하세요
    /// ')
    /// </summary>
    /// <remarks>
    /// Folder selection interface guidance text
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmButton => General_UserData_SelectFolder_ConfirmButton;
    public const string General_UserData_SelectFolder_ConfirmButton = @"여기를 클릭하여 선택하거나 옆의 '취소'를 선택하여 기본 경로로 복원하세요";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmMigrateData in ko-KR (like '
    /// 기존 데이터를 마이그레이션할까요?
    /// ')
    /// </summary>
    /// <remarks>
    /// Confirm whether to migrate existing user data
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmMigrateData => General_UserData_SelectFolder_ConfirmMigrateData;
    public const string General_UserData_SelectFolder_ConfirmMigrateData = @"기존 데이터를 마이그레이션할까요?";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmReset in ko-KR (like '
    /// 사용자 데이터를 기본값으로 복원하시겠습니까?
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmReset => General_UserData_SelectFolder_ConfirmReset;
    public const string General_UserData_SelectFolder_ConfirmReset = @"사용자 데이터를 기본값으로 복원하시겠습니까?";
    
    /// <summary>
    /// Get the localized string for Misc_DebugMode in ko-KR (like '
    /// 개발자 모드
    /// ')
    /// </summary>
    /// <remarks>
    /// Indicates the software is running in developer/debug mode
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Misc_DebugMode => Misc_DebugMode;
    public const string Misc_DebugMode = @"개발자 모드";
    
    /// <summary>
    /// Get the localized string for Misc_MakeDiagReport in ko-KR (like '
    /// 진단 보고서 생성
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_MakeDiagReport => Misc_MakeDiagReport;
    public const string Misc_MakeDiagReport = @"진단 보고서 생성";
    
    /// <summary>
    /// Get the localized string for Misc_ResetSettings in ko-KR (like '
    /// 모든 설정 초기화
    /// ')
    /// </summary>
    /// <remarks>
    /// Reset all settings to default values
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Misc_ResetSettings => Misc_ResetSettings;
    public const string Misc_ResetSettings = @"모든 설정 초기화";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsSubTitle in ko-KR (like '
    /// 하드웨어 가속 설정 관리
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsSubTitle => Render_AccelOptsSubTitle;
    public const string Render_AccelOptsSubTitle = @"하드웨어 가속 설정 관리";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsTitle in ko-KR (like '
    /// 하드웨어 가속
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsTitle => Render_AccelOptsTitle;
    public const string Render_AccelOptsTitle = @"하드웨어 가속";
    
    /// <summary>
    /// Get the localized string for Render_EnableMultiAccel in ko-KR (like '
    /// 다중 가속기 사용 (렌더링 전용)
    /// ')
    /// </summary>
    /// <remarks>
    /// Enable multi-accelerator for rendering only
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_EnableMultiAccel => Render_EnableMultiAccel;
    public const string Render_EnableMultiAccel = @"다중 가속기 사용 (렌더링 전용)";
    
    /// <summary>
    /// Get the localized string for Render_SelectAccel in ko-KR (like '
    /// 렌더링/편집 시 하드웨어 가속에 사용할 GPU 선택
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_SelectAccel => Render_SelectAccel;
    public const string Render_SelectAccel = @"렌더링/편집 시 하드웨어 가속에 사용할 GPU 선택";
    
    /// <summary>
    /// Get the localized string for Render_LoadingAccels in ko-KR (like '
    /// 사용 가능한 가속기 가져오는 중...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_LoadingAccels => Render_LoadingAccels;
    public const string Render_LoadingAccels = @"사용 가능한 가속기 가져오는 중...";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsNotSupported in ko-KR (like '
    /// 죄송합니다. 사용 중인 플랫폼에서 하드웨어 가속 구성을 지원하지 않습니다.
    /// ')
    /// </summary>
    /// <remarks>
    /// Hardware acceleration configuration not supported on current platform
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsNotSupported => Render_AccelOptsNotSupported;
    public const string Render_AccelOptsNotSupported = @"죄송합니다. 사용 중인 플랫폼에서 하드웨어 가속 구성을 지원하지 않습니다.";
    
    /// <summary>
    /// Get the current localized Id (like 'k')
    /// </summary>
    string ISimpleLocalizerBase_Settings._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"ko-KR";
    
    
}

#endregion

#region fr_FR
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_Settings_fr_FR__ : ISimpleLocalizerBase_Settings
{
    /// <summary>
    /// Get the localized string for CommonStr_Go in fr-FR (like '
    /// Aller à la page
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Go => CommonStr_Go;
    public const string CommonStr_Go = @"Aller à la page";
    
    /// <summary>
    /// Get the localized string for CommonStr_Make in fr-FR (like '
    /// Génération...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Make => CommonStr_Make;
    public const string CommonStr_Make = @"Génération...";
    
    /// <summary>
    /// Get the localized string for CommonStr_RebootRequired in fr-FR (like '
    /// Pour appliquer ces modifications, vous devez redémarrer {Localized.AppBrand}. Voulez-vous redémarrer maintenant ?
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_RebootRequired() => CommonStr_RebootRequired();
    public string CommonStr_RebootRequired() => @$"Pour appliquer ces modifications, vous devez redémarrer {Localized.AppBrand}. Voulez-vous redémarrer maintenant ?";
    
    /// <summary>
    /// Get the localized string for CommonStr_Reset in fr-FR (like '
    /// Réinitialiser...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.CommonStr_Reset => CommonStr_Reset;
    public const string CommonStr_Reset = @"Réinitialiser...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Select in fr-FR (like '
    /// Sélectionner...
    /// ')
    /// </summary>
    /// <remarks>
    /// Texte par défaut pour les menus déroulants ou les zones de sélection
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_Select => CommonStr_Select;
    public const string CommonStr_Select = @"Sélectionner...";
    
    /// <summary>
    /// Get the localized string for CommonStr_Sure in fr-FR (like '
    /// L&apos;opération {name} présente un risque. Voulez-vous continuer ?
    /// ')
    /// </summary>
    /// <remarks>
    /// Warning dialog for risky operation confirmation
    /// </remarks>
    string ISimpleLocalizerBase_Settings.CommonStr_Sure(string name) => CommonStr_Sure(name);
    public string CommonStr_Sure(string name) => @$"L'opération {name} présente un risque. Voulez-vous continuer ?";
    
    /// <summary>
    /// Get the localized string for General_Language in fr-FR (like '
    /// Langue/Language
    /// ')
    /// </summary>
    /// <remarks>
    /// Keep the /Language suffix as specified in the comment
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_Language => General_Language;
    public const string General_Language = @"Langue/Language";
    
    /// <summary>
    /// Get the localized string for General_UserData in fr-FR (like '
    /// Gestion des données et configurations
    /// ')
    /// </summary>
    /// <remarks>
    /// Translation of &apos;数据与配置管理&apos; maintaining the formal software UI tone while adapting to French technical terminology conventions
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData => General_UserData;
    public const string General_UserData = @"Gestion des données et configurations";
    
    /// <summary>
    /// Get the localized string for General_UserData_ManagePageOpen in fr-FR (like '
    /// Gérer les données utilisateur
    /// ')
    /// </summary>
    /// <remarks>
    /// Traduction directe de &apos;管理用户数据&apos; en français, correspondant à l&apos;action d&apos;administration des données d&apos;utilisateur dans une interface logicielle.
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_ManagePageOpen => General_UserData_ManagePageOpen;
    public const string General_UserData_ManagePageOpen = @"Gérer les données utilisateur";
    
    /// <summary>
    /// Get the localized string for General_UserData_Path in fr-FR (like '
    /// Répertoire des données utilisateur
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_Path => General_UserData_Path;
    public const string General_UserData_Path = @"Répertoire des données utilisateur";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_Confirm in fr-FR (like '
    /// Confirmez-vous que le répertoire de données utilisateur doit être défini sur « {path} » ?
    /// ')
    /// </summary>
    /// <remarks>
    /// Dialog de confirmation pour changer le répertoire des données utilisateur
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_Confirm(string path) => General_UserData_SelectFolder_Confirm(path);
    public string General_UserData_SelectFolder_Confirm(string path) => @$"Confirmez-vous que le répertoire de données utilisateur doit être défini sur « {path} » ?";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmButton in fr-FR (like '
    /// Cliquez ici pour sélectionner, ou sur &quot;Annuler&quot; à côté pour revenir au chemin par défaut
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmButton => General_UserData_SelectFolder_ConfirmButton;
    public const string General_UserData_SelectFolder_ConfirmButton = """"Cliquez ici pour sélectionner, ou sur "Annuler" à côté pour revenir au chemin par défaut"""";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmMigrateData in fr-FR (like '
    /// Voulez-vous migrer les données existantes ?
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmMigrateData => General_UserData_SelectFolder_ConfirmMigrateData;
    public const string General_UserData_SelectFolder_ConfirmMigrateData = @"Voulez-vous migrer les données existantes ?";
    
    /// <summary>
    /// Get the localized string for General_UserData_SelectFolder_ConfirmReset in fr-FR (like '
    /// Confirmer la réinitialisation des données utilisateur aux valeurs par défaut ?
    /// ')
    /// </summary>
    /// <remarks>
    /// Confirmation prompt for resetting user data to default values
    /// </remarks>
    string ISimpleLocalizerBase_Settings.General_UserData_SelectFolder_ConfirmReset => General_UserData_SelectFolder_ConfirmReset;
    public const string General_UserData_SelectFolder_ConfirmReset = @"Confirmer la réinitialisation des données utilisateur aux valeurs par défaut ?";
    
    /// <summary>
    /// Get the localized string for Misc_DebugMode in fr-FR (like '
    /// Mode développeur
    /// ')
    /// </summary>
    /// <remarks>
    /// Translation of &apos;开发者模式&apos; to French, maintaining the formal software UI context
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Misc_DebugMode => Misc_DebugMode;
    public const string Misc_DebugMode = @"Mode développeur";
    
    /// <summary>
    /// Get the localized string for Misc_MakeDiagReport in fr-FR (like '
    /// Générer un rapport de diagnostic
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_MakeDiagReport => Misc_MakeDiagReport;
    public const string Misc_MakeDiagReport = @"Générer un rapport de diagnostic";
    
    /// <summary>
    /// Get the localized string for Misc_ResetSettings in fr-FR (like '
    /// Réinitialiser tous les paramètres
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Misc_ResetSettings => Misc_ResetSettings;
    public const string Misc_ResetSettings = @"Réinitialiser tous les paramètres";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsSubTitle in fr-FR (like '
    /// Gestion de la configuration de l&apos;accélération matérielle
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsSubTitle => Render_AccelOptsSubTitle;
    public const string Render_AccelOptsSubTitle = @"Gestion de la configuration de l'accélération matérielle";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsTitle in fr-FR (like '
    /// Accélération matérielle
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsTitle => Render_AccelOptsTitle;
    public const string Render_AccelOptsTitle = @"Accélération matérielle";
    
    /// <summary>
    /// Get the localized string for Render_EnableMultiAccel in fr-FR (like '
    /// Activer multi-accélérateur (rendu uniquement)
    /// ')
    /// </summary>
    /// <remarks>
    /// Option pour activer la prise en charge de plusieurs accélérateurs, limitée au rendu
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_EnableMultiAccel => Render_EnableMultiAccel;
    public const string Render_EnableMultiAccel = @"Activer multi-accélérateur (rendu uniquement)";
    
    /// <summary>
    /// Get the localized string for Render_SelectAccel in fr-FR (like '
    /// Sélectionnez le GPU pour l&apos;accélération matérielle lors du rendu/édition
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_Settings.Render_SelectAccel => Render_SelectAccel;
    public const string Render_SelectAccel = @"Sélectionnez le GPU pour l'accélération matérielle lors du rendu/édition";
    
    /// <summary>
    /// Get the localized string for Render_LoadingAccels in fr-FR (like '
    /// Récupération des accélérateurs disponibles...
    /// ')
    /// </summary>
    /// <remarks>
    /// Indicateur de chargement pendant la récupération des accélérateurs
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_LoadingAccels => Render_LoadingAccels;
    public const string Render_LoadingAccels = @"Récupération des accélérateurs disponibles...";
    
    /// <summary>
    /// Get the localized string for Render_AccelOptsNotSupported in fr-FR (like '
    /// Désolé, votre plateforme ne prend pas en charge la configuration de l&apos;accélération matérielle.
    /// ')
    /// </summary>
    /// <remarks>
    /// Error message indicating that hardware acceleration configuration is not supported on the user&apos;s platform
    /// </remarks>
    string ISimpleLocalizerBase_Settings.Render_AccelOptsNotSupported => Render_AccelOptsNotSupported;
    public const string Render_AccelOptsNotSupported = @"Désolé, votre plateforme ne prend pas en charge la configuration de l'accélération matérielle.";
    
    /// <summary>
    /// Get the current localized Id (like 'f')
    /// </summary>
    string ISimpleLocalizerBase_Settings._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"fr-FR";
    
    
}

#endregion
