<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../projectFrameCut.Render.Contracts/projectFrameCut.Render.Contracts.csproj" />
		<Using Remove="projectFrameCut.Drawing.Base.IPicture"/>
		<Using Remove="projectFrameCut.Drawing.Base.PictureExtensions"/>
		<Using Remove="projectFrameCut.Shared.Logger"/>
  </ItemGroup>
</Project>
