// <auto-generated>
// Generated in 2026/2/14 22:16:14
// These code are generated by SimpleLocalizer. Don't modify it directly; modify the 'localized.json' file and regenerate code to apply changes.
// </auto-generated>

#nullable enable
#region usings
using System;
using System.Collections.Concurrent;
using System.CodeDom.Compiler;
using System.Diagnostics;
#endregion

#region base interface
/// <summary>
/// This is the base interface for all localizers.
/// </summary>
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
public interface ApplicationAPIBaseLocalizerBase
{
    /// <summary>
    /// Get the localized string for _Info (like '
    /// 提示
    ///')
    /// </summary>
    public string _Info { get; }
    
    /// <summary>
    /// Get the localized string for _OK (like '
    /// 好的
    ///')
    /// </summary>
    public string _OK { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Close (like '
    /// 关闭
    ///')
    /// </summary>
    public string MultiWindowView_Close { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt (like '
    /// 当你关闭此独立窗口时，此窗口将会回到原先的容器里。
    ///')
    /// </summary>
    public string MultiWindowView_DockPrompt { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_NotPromptAgain (like '
    /// 不再提示我
    ///')
    /// </summary>
    public string MultiWindowView_DockPrompt_NotPromptAgain { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Maximize (like '
    /// 最大化
    ///')
    /// </summary>
    public string MultiWindowView_Maximize { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Minimize (like '
    /// 最小化
    ///')
    /// </summary>
    public string MultiWindowView_Minimize { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_PopOut (like '
    /// 作为独立窗口
    ///')
    /// </summary>
    public string MultiWindowView_PopOut { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Dock (like '
    /// 回到容器
    ///')
    /// </summary>
    public string MultiWindowView_Dock { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_GoBack (like '
    /// 向后导航
    ///')
    /// </summary>
    public string MultiWindowView_GoBack { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_GoForward (like '
    /// 向前导航
    ///')
    /// </summary>
    public string MultiWindowView_GoForward { get; }
    
    /// <summary>
    /// Get the current Locale's ID (like 'zh-CN')
    /// </summary>
    public string _LocaleId_ { get; }
    
    public static Dictionary<string, ApplicationAPIBaseLocalizerBase> GetMapping()
    {
        return new Dictionary<string, ApplicationAPIBaseLocalizerBase>()
        {
            { "zh-CN", new  __ApplicationAPIBaseLocalizerBase_zh_CN__() },
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="fallbackValue">The fallback value when the localized string isn't found.</param>
    /// <returns>The localized string you want.</returns>
    public string DynamicLookup(string id, string? fallbackValue = null)
    {
        return id switch
        {
            "_Info" => _Info,
            "_OK" => _OK,
            "MultiWindowView_Close" => MultiWindowView_Close,
            "MultiWindowView_DockPrompt" => MultiWindowView_DockPrompt,
            "MultiWindowView_DockPrompt_NotPromptAgain" => MultiWindowView_DockPrompt_NotPromptAgain,
            "MultiWindowView_Maximize" => MultiWindowView_Maximize,
            "MultiWindowView_Minimize" => MultiWindowView_Minimize,
            "MultiWindowView_PopOut" => MultiWindowView_PopOut,
            "MultiWindowView_Dock" => MultiWindowView_Dock,
            "MultiWindowView_GoBack" => MultiWindowView_GoBack,
            "MultiWindowView_GoForward" => MultiWindowView_GoForward,
            _ => fallbackValue ?? $"Can't find the localized string for id '{id}'"
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id with some arguments.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="args">The arguments to format the localized string.</param>
    /// <returns>The localized string with arguments applied.</returns>
    /// <exception cref="KeyNotFoundException">The localized string you want with arguments isn't found.</exception>
    /// <exception cref="IndexOutOfRangeException">The number of arguments provided does not match the expected number for the localized string.</exception>
    public string DynamicLookupWithArgs(string id, params object[] args)
    {
        return id switch
        {
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}' with any argument")
        };
    }
}

#endregion

#region zh_CN
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ApplicationAPIBaseLocalizerBase_zh_CN__ : ApplicationAPIBaseLocalizerBase
{
    string ApplicationAPIBaseLocalizerBase._Info => _Info;
    /// <summary>
    /// Get the localized string for _Info in zh-CN (like '
    /// 提示
    /// ')
    /// </summary>
    public static string _Info => $"提示";
    
    string ApplicationAPIBaseLocalizerBase._OK => _OK;
    /// <summary>
    /// Get the localized string for _OK in zh-CN (like '
    /// 好的
    /// ')
    /// </summary>
    public static string _OK => $"好的";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Close => MultiWindowView_Close;
    /// <summary>
    /// Get the localized string for MultiWindowView_Close in zh-CN (like '
    /// 关闭
    /// ')
    /// </summary>
    public static string MultiWindowView_Close => $"关闭";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_DockPrompt => MultiWindowView_DockPrompt;
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt in zh-CN (like '
    /// 当你关闭此独立窗口时，此窗口将会回到原先的容器里。
    /// ')
    /// </summary>
    public static string MultiWindowView_DockPrompt => $"当你关闭此独立窗口时，此窗口将会回到原先的容器里。";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_DockPrompt_NotPromptAgain => MultiWindowView_DockPrompt_NotPromptAgain;
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_NotPromptAgain in zh-CN (like '
    /// 不再提示我
    /// ')
    /// </summary>
    public static string MultiWindowView_DockPrompt_NotPromptAgain => $"不再提示我";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Maximize => MultiWindowView_Maximize;
    /// <summary>
    /// Get the localized string for MultiWindowView_Maximize in zh-CN (like '
    /// 最大化
    /// ')
    /// </summary>
    public static string MultiWindowView_Maximize => $"最大化";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Minimize => MultiWindowView_Minimize;
    /// <summary>
    /// Get the localized string for MultiWindowView_Minimize in zh-CN (like '
    /// 最小化
    /// ')
    /// </summary>
    public static string MultiWindowView_Minimize => $"最小化";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_PopOut => MultiWindowView_PopOut;
    /// <summary>
    /// Get the localized string for MultiWindowView_PopOut in zh-CN (like '
    /// 作为独立窗口
    /// ')
    /// </summary>
    public static string MultiWindowView_PopOut => $"作为独立窗口";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Dock => MultiWindowView_Dock;
    /// <summary>
    /// Get the localized string for MultiWindowView_Dock in zh-CN (like '
    /// 回到容器
    /// ')
    /// </summary>
    public static string MultiWindowView_Dock => $"回到容器";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_GoBack => MultiWindowView_GoBack;
    /// <summary>
    /// Get the localized string for MultiWindowView_GoBack in zh-CN (like '
    /// 向后导航
    /// ')
    /// </summary>
    public static string MultiWindowView_GoBack => $"向后导航";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_GoForward => MultiWindowView_GoForward;
    /// <summary>
    /// Get the localized string for MultiWindowView_GoForward in zh-CN (like '
    /// 向前导航
    /// ')
    /// </summary>
    public static string MultiWindowView_GoForward => $"向前导航";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ApplicationAPIBaseLocalizerBase._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-CN";
    
    
}

#endregion
namespace projectFrameCut.ApplicationAPIBase.LocalizedResources
{
    public static class APIBaseLocalizedResources
    {
        /// <summary>
        /// Get the default localizer instance.
        /// </summary>
        /// <remarks>
        /// You need to initialize this property before using it.
        /// </remarks>
        public static ApplicationAPIBaseLocalizerBase Localized { get; set; } = null!;
    }
    
}
