// <auto-generated>
// Generated in 2026/6/8 0:15:06
// These code are generated by SimpleLocalizer. Don't modify it directly; modify the 'locate.json' file and regenerate code to apply changes.
// </auto-generated>

#nullable enable
#region usings
using System;
using System.Collections.Concurrent;
using System.CodeDom.Compiler;
using System.Diagnostics;
#endregion

#region base interface
/// <summary>
/// This is the base interface for all localizers.
/// </summary>
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
public interface ApplicationAPIBaseLocalizerBase
{
    /// <summary>
    /// Get the localized string for _Error (like '
    /// 错误
    ///')
    /// </summary>
    public string _Error { get; }
    
    /// <summary>
    /// Get the localized string for _Info (like '
    /// 提示
    ///')
    /// </summary>
    public string _Info { get; }
    
    /// <summary>
    /// Get the localized string for _OK (like '
    /// 好的
    ///')
    /// </summary>
    public string _OK { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Canceled (like '
    /// 任务已取消
    ///')
    /// </summary>
    public string DraftPage_Tasks_Status_Canceled { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Cancelling (like '
    /// 尝试取消任务...
    ///')
    /// </summary>
    public string DraftPage_Tasks_Status_Cancelling { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Completed (like '
    /// 任务成功的完成了
    ///')
    /// </summary>
    public string DraftPage_Tasks_Status_Completed { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Fail (like '
    /// 任务执行失败
    ///')
    /// </summary>
    public string DraftPage_Tasks_Status_Fail { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Running (like '
    /// 任务正在执行
    ///')
    /// </summary>
    public string DraftPage_Tasks_Status_Running { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Unknown (like '
    /// 任务状态位置
    ///')
    /// </summary>
    public string DraftPage_Tasks_Status_Unknown { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_Favorite_Add (like '
    /// 收藏字体
    ///')
    /// </summary>
    public string FontPicker_Favorite_Add { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_Favorite_Remove (like '
    /// 取消收藏字体
    ///')
    /// </summary>
    public string FontPicker_Favorite_Remove { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Close (like '
    /// 关闭
    ///')
    /// </summary>
    public string MultiWindowView_Close { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Dock (like '
    /// 回到容器
    ///')
    /// </summary>
    public string MultiWindowView_Dock { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt (like '
    /// 使用最小化按钮边上的 &apos;↙&apos; 来使窗口回到原先的容器里。
    /// 当你直接关闭此独立窗口时，此窗口将会被彻底关闭。
    ///')
    /// </summary>
    public string MultiWindowView_DockPrompt { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_Android (like '
    /// 你可能需要把此窗口设置为小窗模式来让他和应用程序同时显示。
    /// 使用右侧的 &apos;↙&apos; 按钮来使窗口回到原先的容器里。
    /// 直接关闭此窗口会导致窗口被彻底关闭。
    ///')
    /// </summary>
    public string MultiWindowView_DockPrompt_Android { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_iPadOS (like '
    /// 点击窗口顶上的&apos;···&apos;，然后选择‘关闭’来使窗口回到原先的容器里。
    ///')
    /// </summary>
    public string MultiWindowView_DockPrompt_iPadOS { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_NotPromptAgain (like '
    /// 不再提示我
    ///')
    /// </summary>
    public string MultiWindowView_DockPrompt_NotPromptAgain { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_GoBack (like '
    /// 向后导航
    ///')
    /// </summary>
    public string MultiWindowView_GoBack { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_GoForward (like '
    /// 向前导航
    ///')
    /// </summary>
    public string MultiWindowView_GoForward { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Maximize (like '
    /// 最大化
    ///')
    /// </summary>
    public string MultiWindowView_Maximize { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_Minimize (like '
    /// 最小化
    ///')
    /// </summary>
    public string MultiWindowView_Minimize { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_PopOut (like '
    /// 作为独立窗口
    ///')
    /// </summary>
    public string MultiWindowView_PopOut { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_PopOut_NotSupport (like '
    /// 你的设备不支持多窗口功能。
    /// 此功能在支持台前调度的iPad和大部分安卓平板上，以及电脑上可用。
    ///')
    /// </summary>
    public string MultiWindowView_PopOut_NotSupport { get; }
    
    /// <summary>
    /// Get the localized string for MultiWindowView_StageManagerUnsupportedWarn (like '
    /// 你的iPad似乎不支持台前调度，多窗口体验可能受影响。
    ///')
    /// </summary>
    public string MultiWindowView_StageManagerUnsupportedWarn { get; }
    
    /// <summary>
    /// Get the localized string for TabView_Error (like '
    /// 很抱歉，由于一个异常，我们无法显示标签页「{tab}」的内容。
    /// 你可以再试一次，或者向我们反馈这个问题。
    ///')
    /// </summary>
    public string TabView_Error(string tab);
    
    /// <summary>
    /// Get the localized string for FontPicker_CategoryPicker_Any (like '
    /// 所有
    ///')
    /// </summary>
    public string FontPicker_CategoryPicker_Any { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Regular (like '
    /// 常规
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Regular { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Bold (like '
    /// 粗体
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Bold { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Italic (like '
    /// 斜体
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Italic { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Light (like '
    /// 细体
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Light { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Medium (like '
    /// 中等
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Medium { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_SemiBold (like '
    /// 半粗
    ///')
    /// </summary>
    public string FontPicker_FontStyle_SemiBold { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_ExtraBold (like '
    /// 特粗
    ///')
    /// </summary>
    public string FontPicker_FontStyle_ExtraBold { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Thin (like '
    /// 极细
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Thin { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_ExtraLight (like '
    /// 特细
    ///')
    /// </summary>
    public string FontPicker_FontStyle_ExtraLight { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Heavy (like '
    /// 特黑
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Heavy { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Book (like '
    /// 标准
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Book { get; }
    
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Normal (like '
    /// 标准
    ///')
    /// </summary>
    public string FontPicker_FontStyle_Normal { get; }
    
    /// <summary>
    /// Get the current Locale's ID (like 'zh-CN')
    /// </summary>
    public string _LocaleId_ { get; }
    
    /// <summary>
    /// Get all available locales.
    /// </summary>
    public static Dictionary<string, ApplicationAPIBaseLocalizerBase> GetMapping()
    {
        return new Dictionary<string, ApplicationAPIBaseLocalizerBase>()
        {
            { "zh-CN", new  __ApplicationAPIBaseLocalizerBase_zh_CN__() },
        };
    }
    /// <summary>
    /// Get all localized item exists in the current locale.
    /// </summary>
    /// <param name="id">The key of the localized item you want to test.</param>
    /// <returns>True if the item exists in the current locale; otherwise false.</returns>
    public static string[] _LocalizedItems_ = new string[]
    {
        "_Error", 
        "_Info", 
        "_OK", 
        "DraftPage_Tasks_Status_Canceled", 
        "DraftPage_Tasks_Status_Cancelling", 
        "DraftPage_Tasks_Status_Completed", 
        "DraftPage_Tasks_Status_Fail", 
        "DraftPage_Tasks_Status_Running", 
        "DraftPage_Tasks_Status_Unknown", 
        "FontPicker_Favorite_Add", 
        "FontPicker_Favorite_Remove", 
        "MultiWindowView_Close", 
        "MultiWindowView_Dock", 
        "MultiWindowView_DockPrompt", 
        "MultiWindowView_DockPrompt_Android", 
        "MultiWindowView_DockPrompt_iPadOS", 
        "MultiWindowView_DockPrompt_NotPromptAgain", 
        "MultiWindowView_GoBack", 
        "MultiWindowView_GoForward", 
        "MultiWindowView_Maximize", 
        "MultiWindowView_Minimize", 
        "MultiWindowView_PopOut", 
        "MultiWindowView_PopOut_NotSupport", 
        "MultiWindowView_StageManagerUnsupportedWarn", 
        "TabView_Error", 
        "FontPicker_CategoryPicker_Any", 
        "FontPicker_FontStyle_Regular", 
        "FontPicker_FontStyle_Bold", 
        "FontPicker_FontStyle_Italic", 
        "FontPicker_FontStyle_Light", 
        "FontPicker_FontStyle_Medium", 
        "FontPicker_FontStyle_SemiBold", 
        "FontPicker_FontStyle_ExtraBold", 
        "FontPicker_FontStyle_Thin", 
        "FontPicker_FontStyle_ExtraLight", 
        "FontPicker_FontStyle_Heavy", 
        "FontPicker_FontStyle_Book", 
        "FontPicker_FontStyle_Normal", 
    };
    
    /// <summary>
    /// Check whether a localization item exists in the current locale.
    /// </summary>
    /// <param name="id">The key of the localized item you want to test.</param>
    /// <returns>True if the item exists in the current locale; otherwise false.</returns>
    public bool IsItemExist(string id, IEqualityComparer<string>? comparer = null) => _LocalizedItems_.Contains(id, comparer ?? StringComparer.Ordinal);
    
    /// <summary>
    /// Dynamically lookup the localized string by the given id.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="fallbackValue">The fallback value when the localized string isn't found.</param>
    /// <returns>The localized string you want.</returns>
    public string DynamicLookup(string id, string? fallbackValue = null)
    {
        return id switch
        {
            "_Error" => _Error,
            "_Info" => _Info,
            "_OK" => _OK,
            "DraftPage_Tasks_Status_Canceled" => DraftPage_Tasks_Status_Canceled,
            "DraftPage_Tasks_Status_Cancelling" => DraftPage_Tasks_Status_Cancelling,
            "DraftPage_Tasks_Status_Completed" => DraftPage_Tasks_Status_Completed,
            "DraftPage_Tasks_Status_Fail" => DraftPage_Tasks_Status_Fail,
            "DraftPage_Tasks_Status_Running" => DraftPage_Tasks_Status_Running,
            "DraftPage_Tasks_Status_Unknown" => DraftPage_Tasks_Status_Unknown,
            "FontPicker_Favorite_Add" => FontPicker_Favorite_Add,
            "FontPicker_Favorite_Remove" => FontPicker_Favorite_Remove,
            "MultiWindowView_Close" => MultiWindowView_Close,
            "MultiWindowView_Dock" => MultiWindowView_Dock,
            "MultiWindowView_DockPrompt" => MultiWindowView_DockPrompt,
            "MultiWindowView_DockPrompt_Android" => MultiWindowView_DockPrompt_Android,
            "MultiWindowView_DockPrompt_iPadOS" => MultiWindowView_DockPrompt_iPadOS,
            "MultiWindowView_DockPrompt_NotPromptAgain" => MultiWindowView_DockPrompt_NotPromptAgain,
            "MultiWindowView_GoBack" => MultiWindowView_GoBack,
            "MultiWindowView_GoForward" => MultiWindowView_GoForward,
            "MultiWindowView_Maximize" => MultiWindowView_Maximize,
            "MultiWindowView_Minimize" => MultiWindowView_Minimize,
            "MultiWindowView_PopOut" => MultiWindowView_PopOut,
            "MultiWindowView_PopOut_NotSupport" => MultiWindowView_PopOut_NotSupport,
            "MultiWindowView_StageManagerUnsupportedWarn" => MultiWindowView_StageManagerUnsupportedWarn,
            "FontPicker_CategoryPicker_Any" => FontPicker_CategoryPicker_Any,
            "FontPicker_FontStyle_Regular" => FontPicker_FontStyle_Regular,
            "FontPicker_FontStyle_Bold" => FontPicker_FontStyle_Bold,
            "FontPicker_FontStyle_Italic" => FontPicker_FontStyle_Italic,
            "FontPicker_FontStyle_Light" => FontPicker_FontStyle_Light,
            "FontPicker_FontStyle_Medium" => FontPicker_FontStyle_Medium,
            "FontPicker_FontStyle_SemiBold" => FontPicker_FontStyle_SemiBold,
            "FontPicker_FontStyle_ExtraBold" => FontPicker_FontStyle_ExtraBold,
            "FontPicker_FontStyle_Thin" => FontPicker_FontStyle_Thin,
            "FontPicker_FontStyle_ExtraLight" => FontPicker_FontStyle_ExtraLight,
            "FontPicker_FontStyle_Heavy" => FontPicker_FontStyle_Heavy,
            "FontPicker_FontStyle_Book" => FontPicker_FontStyle_Book,
            "FontPicker_FontStyle_Normal" => FontPicker_FontStyle_Normal,
            _ => fallbackValue ?? $"Can't find the localized string for id '{id}'"
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id with some arguments.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="args">The arguments to format the localized string.</param>
    /// <returns>The localized string with arguments applied.</returns>
    /// <exception cref="KeyNotFoundException">The localized string you want with arguments isn't found.</exception>
    /// <exception cref="IndexOutOfRangeException">The number of arguments provided does not match the expected number for the localized string.</exception>
    /// <exception cref="InvalidCastException">One or more arguments cannot be cast to the expected type for the localized string.</exception>
    public string DynamicLookupWithArgs(string id, params object[] args)
    {
        return id switch
        {
            "TabView_Error" => TabView_Error((string)args[0]),
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}' with any argument")
        };
    }
}

#endregion

#region zh_CN
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ApplicationAPIBaseLocalizerBase_zh_CN__ : ApplicationAPIBaseLocalizerBase
{
    string ApplicationAPIBaseLocalizerBase._Error => _Error;
    /// <summary>
    /// Get the localized string for _Error in zh-CN (like '
    /// 错误
    /// ')
    /// </summary>
    public static string _Error => $"错误";
    
    string ApplicationAPIBaseLocalizerBase._Info => _Info;
    /// <summary>
    /// Get the localized string for _Info in zh-CN (like '
    /// 提示
    /// ')
    /// </summary>
    public static string _Info => $"提示";
    
    string ApplicationAPIBaseLocalizerBase._OK => _OK;
    /// <summary>
    /// Get the localized string for _OK in zh-CN (like '
    /// 好的
    /// ')
    /// </summary>
    public static string _OK => $"好的";
    
    string ApplicationAPIBaseLocalizerBase.DraftPage_Tasks_Status_Canceled => DraftPage_Tasks_Status_Canceled;
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Canceled in zh-CN (like '
    /// 任务已取消
    /// ')
    /// </summary>
    public static string DraftPage_Tasks_Status_Canceled => $"任务已取消";
    
    string ApplicationAPIBaseLocalizerBase.DraftPage_Tasks_Status_Cancelling => DraftPage_Tasks_Status_Cancelling;
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Cancelling in zh-CN (like '
    /// 尝试取消任务...
    /// ')
    /// </summary>
    public static string DraftPage_Tasks_Status_Cancelling => $"尝试取消任务...";
    
    string ApplicationAPIBaseLocalizerBase.DraftPage_Tasks_Status_Completed => DraftPage_Tasks_Status_Completed;
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Completed in zh-CN (like '
    /// 任务成功的完成了
    /// ')
    /// </summary>
    public static string DraftPage_Tasks_Status_Completed => $"任务成功的完成了";
    
    string ApplicationAPIBaseLocalizerBase.DraftPage_Tasks_Status_Fail => DraftPage_Tasks_Status_Fail;
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Fail in zh-CN (like '
    /// 任务执行失败
    /// ')
    /// </summary>
    public static string DraftPage_Tasks_Status_Fail => $"任务执行失败";
    
    string ApplicationAPIBaseLocalizerBase.DraftPage_Tasks_Status_Running => DraftPage_Tasks_Status_Running;
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Running in zh-CN (like '
    /// 任务正在执行
    /// ')
    /// </summary>
    public static string DraftPage_Tasks_Status_Running => $"任务正在执行";
    
    string ApplicationAPIBaseLocalizerBase.DraftPage_Tasks_Status_Unknown => DraftPage_Tasks_Status_Unknown;
    /// <summary>
    /// Get the localized string for DraftPage_Tasks_Status_Unknown in zh-CN (like '
    /// 任务状态位置
    /// ')
    /// </summary>
    public static string DraftPage_Tasks_Status_Unknown => $"任务状态位置";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_Favorite_Add => FontPicker_Favorite_Add;
    /// <summary>
    /// Get the localized string for FontPicker_Favorite_Add in zh-CN (like '
    /// 收藏字体
    /// ')
    /// </summary>
    public static string FontPicker_Favorite_Add => $"收藏字体";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_Favorite_Remove => FontPicker_Favorite_Remove;
    /// <summary>
    /// Get the localized string for FontPicker_Favorite_Remove in zh-CN (like '
    /// 取消收藏字体
    /// ')
    /// </summary>
    public static string FontPicker_Favorite_Remove => $"取消收藏字体";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Close => MultiWindowView_Close;
    /// <summary>
    /// Get the localized string for MultiWindowView_Close in zh-CN (like '
    /// 关闭
    /// ')
    /// </summary>
    public static string MultiWindowView_Close => $"关闭";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Dock => MultiWindowView_Dock;
    /// <summary>
    /// Get the localized string for MultiWindowView_Dock in zh-CN (like '
    /// 回到容器
    /// ')
    /// </summary>
    public static string MultiWindowView_Dock => $"回到容器";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_DockPrompt => MultiWindowView_DockPrompt;
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt in zh-CN (like '
    /// 使用最小化按钮边上的 &apos;↙&apos; 来使窗口回到原先的容器里。
    /// 当你直接关闭此独立窗口时，此窗口将会被彻底关闭。
    /// ')
    /// </summary>
    public static string MultiWindowView_DockPrompt => $"使用最小化按钮边上的 '↙' 来使窗口回到原先的容器里。{Environment.NewLine}当你直接关闭此独立窗口时，此窗口将会被彻底关闭。";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_DockPrompt_Android => MultiWindowView_DockPrompt_Android;
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_Android in zh-CN (like '
    /// 你可能需要把此窗口设置为小窗模式来让他和应用程序同时显示。
    /// 使用右侧的 &apos;↙&apos; 按钮来使窗口回到原先的容器里。
    /// 直接关闭此窗口会导致窗口被彻底关闭。
    /// ')
    /// </summary>
    public static string MultiWindowView_DockPrompt_Android => $"你可能需要把此窗口设置为小窗模式来让他和应用程序同时显示。{Environment.NewLine}使用右侧的 '↙' 按钮来使窗口回到原先的容器里。{Environment.NewLine}直接关闭此窗口会导致窗口被彻底关闭。";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_DockPrompt_iPadOS => MultiWindowView_DockPrompt_iPadOS;
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_iPadOS in zh-CN (like '
    /// 点击窗口顶上的&apos;···&apos;，然后选择‘关闭’来使窗口回到原先的容器里。
    /// ')
    /// </summary>
    public static string MultiWindowView_DockPrompt_iPadOS => $"点击窗口顶上的'···'，然后选择‘关闭’来使窗口回到原先的容器里。";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_DockPrompt_NotPromptAgain => MultiWindowView_DockPrompt_NotPromptAgain;
    /// <summary>
    /// Get the localized string for MultiWindowView_DockPrompt_NotPromptAgain in zh-CN (like '
    /// 不再提示我
    /// ')
    /// </summary>
    public static string MultiWindowView_DockPrompt_NotPromptAgain => $"不再提示我";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_GoBack => MultiWindowView_GoBack;
    /// <summary>
    /// Get the localized string for MultiWindowView_GoBack in zh-CN (like '
    /// 向后导航
    /// ')
    /// </summary>
    public static string MultiWindowView_GoBack => $"向后导航";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_GoForward => MultiWindowView_GoForward;
    /// <summary>
    /// Get the localized string for MultiWindowView_GoForward in zh-CN (like '
    /// 向前导航
    /// ')
    /// </summary>
    public static string MultiWindowView_GoForward => $"向前导航";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Maximize => MultiWindowView_Maximize;
    /// <summary>
    /// Get the localized string for MultiWindowView_Maximize in zh-CN (like '
    /// 最大化
    /// ')
    /// </summary>
    public static string MultiWindowView_Maximize => $"最大化";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_Minimize => MultiWindowView_Minimize;
    /// <summary>
    /// Get the localized string for MultiWindowView_Minimize in zh-CN (like '
    /// 最小化
    /// ')
    /// </summary>
    public static string MultiWindowView_Minimize => $"最小化";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_PopOut => MultiWindowView_PopOut;
    /// <summary>
    /// Get the localized string for MultiWindowView_PopOut in zh-CN (like '
    /// 作为独立窗口
    /// ')
    /// </summary>
    public static string MultiWindowView_PopOut => $"作为独立窗口";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_PopOut_NotSupport => MultiWindowView_PopOut_NotSupport;
    /// <summary>
    /// Get the localized string for MultiWindowView_PopOut_NotSupport in zh-CN (like '
    /// 你的设备不支持多窗口功能。
    /// 此功能在支持台前调度的iPad和大部分安卓平板上，以及电脑上可用。
    /// ')
    /// </summary>
    public static string MultiWindowView_PopOut_NotSupport => $"你的设备不支持多窗口功能。{Environment.NewLine}此功能在支持台前调度的iPad和大部分安卓平板上，以及电脑上可用。";
    
    string ApplicationAPIBaseLocalizerBase.MultiWindowView_StageManagerUnsupportedWarn => MultiWindowView_StageManagerUnsupportedWarn;
    /// <summary>
    /// Get the localized string for MultiWindowView_StageManagerUnsupportedWarn in zh-CN (like '
    /// 你的iPad似乎不支持台前调度，多窗口体验可能受影响。
    /// ')
    /// </summary>
    public static string MultiWindowView_StageManagerUnsupportedWarn => $"你的iPad似乎不支持台前调度，多窗口体验可能受影响。";
    
    string ApplicationAPIBaseLocalizerBase.TabView_Error(string tab) => TabView_Error(tab);
    /// <summary>
    /// Get the localized string for TabView_Error in zh-CN (like '
    /// 很抱歉，由于一个异常，我们无法显示标签页「{tab}」的内容。
    /// 你可以再试一次，或者向我们反馈这个问题。
    /// ')
    /// </summary>
    public static string TabView_Error(string tab) => $"很抱歉，由于一个异常，我们无法显示标签页「{tab}」的内容。{Environment.NewLine}你可以再试一次，或者向我们反馈这个问题。";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_CategoryPicker_Any => FontPicker_CategoryPicker_Any;
    /// <summary>
    /// Get the localized string for FontPicker_CategoryPicker_Any in zh-CN (like '
    /// 所有
    /// ')
    /// </summary>
    public static string FontPicker_CategoryPicker_Any => $"所有";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Regular => FontPicker_FontStyle_Regular;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Regular in zh-CN (like '
    /// 常规
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Regular => $"常规";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Bold => FontPicker_FontStyle_Bold;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Bold in zh-CN (like '
    /// 粗体
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Bold => $"粗体";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Italic => FontPicker_FontStyle_Italic;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Italic in zh-CN (like '
    /// 斜体
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Italic => $"斜体";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Light => FontPicker_FontStyle_Light;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Light in zh-CN (like '
    /// 细体
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Light => $"细体";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Medium => FontPicker_FontStyle_Medium;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Medium in zh-CN (like '
    /// 中等
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Medium => $"中等";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_SemiBold => FontPicker_FontStyle_SemiBold;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_SemiBold in zh-CN (like '
    /// 半粗
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_SemiBold => $"半粗";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_ExtraBold => FontPicker_FontStyle_ExtraBold;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_ExtraBold in zh-CN (like '
    /// 特粗
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_ExtraBold => $"特粗";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Thin => FontPicker_FontStyle_Thin;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Thin in zh-CN (like '
    /// 极细
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Thin => $"极细";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_ExtraLight => FontPicker_FontStyle_ExtraLight;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_ExtraLight in zh-CN (like '
    /// 特细
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_ExtraLight => $"特细";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Heavy => FontPicker_FontStyle_Heavy;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Heavy in zh-CN (like '
    /// 特黑
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Heavy => $"特黑";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Book => FontPicker_FontStyle_Book;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Book in zh-CN (like '
    /// 标准
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Book => $"标准";
    
    string ApplicationAPIBaseLocalizerBase.FontPicker_FontStyle_Normal => FontPicker_FontStyle_Normal;
    /// <summary>
    /// Get the localized string for FontPicker_FontStyle_Normal in zh-CN (like '
    /// 标准
    /// ')
    /// </summary>
    public static string FontPicker_FontStyle_Normal => $"标准";
    
    /// <summary>
    /// Get the current locale's Id (like 'z')
    /// </summary>
    string ApplicationAPIBaseLocalizerBase._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-CN";
    
}

#endregion
namespace projectFrameCut.ApplicationAPIBase.Localize
{
    public static class APIBaseLocalizedResources
    {
        /// <summary>
        /// Get the default localizer instance.
        /// </summary>
        /// <remarks>
        /// You need to initialize this property before using it.
        /// </remarks>
        public static ApplicationAPIBaseLocalizerBase Localized { get; set; } = null!;
    }
    
}
