<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AssemblyVersion>1.4.1.0</AssemblyVersion>
		<FileVersion>1.4.1.0</FileVersion>
		<Authors>hexadecimal0x12e</Authors>
		<Product>codename 'projectFrameCut'</Product>
		<AssemblyDescription>projectFrameCut universal shared library</AssemblyDescription>
		<Description>projectFrameCut shared library</Description>
		<Copyright>Copyright (c) hexadecimal0x12e 2025-2026</Copyright>
		<PackageProjectUrl>hexadecimal0x12e.com</PackageProjectUrl>
		<Title>codename 'projectFrameCut'</Title>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\projectFrameCut.Drawing\projectFrameCut.Drawing.Base\projectFrameCut.Drawing.Base.csproj" />
		<ProjectReference Include="..\..\projectFrameCut.Drawing\projectFrameCut.Drawing.Processing\projectFrameCut.Drawing.Processing.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
		<PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
		<PackageReference Include="System.IO.Hashing" Version="10.0.*" />
	</ItemGroup>
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="dotnet restore ..\projectFrameCut.sln" StdOutEncoding="UTF-8" StdErrEncoding="UTF-8" IgnoreExitCode="false" />
	</Target>

</Project>
