// <auto-generated>
// This comment can avoid the 'Sync namespace' command modify this file to avoid being overwritten.
// in MAUI, if the namespace for WinUI's base is not '$(RootNamespace).WinUI', it will let whole App not working.
#nullable enable

using Microsoft.UI;
using Microsoft.UI.Windowing;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Media;
using projectFrameCut.Platforms.Windows;
using projectFrameCut.Setting.SettingManager;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using WinRT.Interop;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace projectFrameCut.WinUI
{
    /// <summary>
    /// Provides application-specific behavior to supplement the default Application class.
    /// </summary>
    public partial class App : MauiWinUIApplication
    {
        /// <summary>
        /// Initializes the singleton application object.  This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public App()
        {
            this.InitializeComponent();
            Instance = this;
            UnhandledException += App_UnhandledException;
        }

        public static App? Instance;

        private void App_UnhandledException(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e)
        {
            try
            {
                if (SettingsManager.Settings is not null)
                {
                    if (SettingsManager.IsSettingExists("DontPanicOnUnhandledException"))
                    {
                        if (bool.TryParse(SettingsManager.GetSetting("DontPanicOnUnhandledException", "False"), out var p) ? p : false)
                        {
                            e.Handled = true;
                            Log(e.Exception, "Global unhandled exception", this);
                            AppShell.instance.CurrentPage?.DisplayAlertAsync("Global unhandled exception", Localized._ExceptionTemplate(e.Exception), "ok");
                            return;
                        }
                    }
                }
            }
            catch { }
            Crash(e.Exception);
        }

        public static void Crash(Exception ex) => Program.Crash(ex);

        protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();

        [DllImport("kernel32.dll")]
        public static extern IntPtr GetLastError();

        [DllImport("user32.dll")]
        public static extern bool SetForegroundWindow(IntPtr hWnd);

        [DllImport("user32.dll")]
        public static extern IntPtr SetFocus(IntPtr hWnd);

        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        public static extern int MessageBox(IntPtr hWnd, String text, String caption, uint type);

        [DllImport("user32.dll")]
        public static extern bool MessageBeep(uint uType);

        [DllImport("user32.dll")]
        public static extern IntPtr FlashWindow(IntPtr hWnd, bool bInvert);

        [DllImport("user32.dll")]
        public static extern IntPtr ExitWindowsEx(uint uFlags, uint dwReason);

        [DllImport("Powrprof.dll", SetLastError = true)]
        public static extern bool SetSuspendState(bool bHibernate, bool bForceCritical, bool bDisableWakeEvent);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, ExactSpelling = true)]
        public static extern int GetPackageFullName(IntPtr hProcess, ref int packageFullNameLength, StringBuilder packageFullName);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, ExactSpelling = true)]
        public static extern int GetPackageFamilyName(IntPtr hProcess, ref int packageFamilyNameLength, StringBuilder packageFamilyName);

        [DllImport("kernel32.dll")]
        public static extern IntPtr GetCurrentProcess();

        private const int APPMODEL_ERROR_NO_PACKAGE = 15700;

        public static bool IsPackaged()
        {
            try
            {
                IntPtr h = GetCurrentProcess();
                int length = 0;
                int rc = GetPackageFullName(h, ref length, null);
                if (rc == APPMODEL_ERROR_NO_PACKAGE)
                    return false;
                if (length <= 0)
                    return false;

                var sb = new StringBuilder(length);
                rc = GetPackageFullName(h, ref length, sb);
                return rc == 0 && sb.Length > 0;
            }
            catch
            {
                return false;
            }


        }

        public static string GetPackageFullName()
        {
            try
            {
                IntPtr h = GetCurrentProcess();
                int length = 0;
                int rc = GetPackageFullName(h, ref length, null);
                if (rc == APPMODEL_ERROR_NO_PACKAGE)
                    return "Not running in AppContainer.";
                if (length <= 0)
                    return string.Empty;
                var sb = new StringBuilder(length);
                rc = GetPackageFullName(h, ref length, sb);
                if (rc == 0 && sb.Length > 0)
                {
                    return sb.ToString();
                }
                else
                {
                    return "Not running in AppContainer.";
                }
            }
            catch
            {
                return string.Empty;
            }
        }
        public static string GetPackageFamilyName()
        {
            try
            {
                IntPtr h = GetCurrentProcess();
                int length = 0;
                int rc = GetPackageFamilyName(h, ref length, null);
                if (rc == APPMODEL_ERROR_NO_PACKAGE)
                    return "Not running in AppContainer.";
                if (length <= 0)
                    return string.Empty;
                var sb = new StringBuilder(length);
                rc = GetPackageFamilyName(h, ref length, sb);
                if (rc == 0 && sb.Length > 0)
                {
                    return sb.ToString();
                }
                else
                {
                    return "Not running in AppContainer.";
                }
            }
            catch
            {
                return string.Empty;
            }
        }

        public static async Task BringToForeground()
        {
            await MainThread.InvokeOnMainThreadAsync(() =>
            {
                var window = Microsoft.Maui.Controls.Application.Current?.Windows[0];
                if (window?.Handler?.PlatformView is Microsoft.UI.Xaml.Window nativeWindow)
                {
                    var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(nativeWindow);
                    SetForegroundWindow(hwnd);
                    SetFocus(hwnd);
                }
            });

        }


    }


}
