<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management.Automation" Version="7.6.5" PrivateAssets="all" IncludeAssets="compile" />
    <ProjectReference Include="..\..\projectFrameCut.Render.Contracts\projectFrameCut.Render.Contracts.csproj" />
    <None Update="projectFrameCut.PowerShell.psd1" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="README.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="FilterModulePublish" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Filename)' != 'projectFrameCut.PowerShell' and '%(ResolvedFileToPublish.Filename)' != 'projectFrameCut.Render.Contracts' and '%(ResolvedFileToPublish.Filename)' != 'projectFrameCut.Render.RPCProtocol' and '%(ResolvedFileToPublish.Filename)' != 'protobuf-net' and '%(ResolvedFileToPublish.Filename)' != 'protobuf-net.Core' and '%(ResolvedFileToPublish.Filename)' != 'README'" />
    </ItemGroup>
  </Target>
</Project>
