using projectFrameCut.Render.RenderAPIBase.ClipAndTrack;
using projectFrameCut.Render.RenderAPIBase.EffectAndMixture;
using projectFrameCut.Shared;
using System;
using System.Collections.Generic;
using System.Text;

namespace projectFrameCut.ApplicationAPIBase.DynamicPreviewProvider
{
    public interface IClipDynamicPreviewProvider
    {
        public string TypeName { get; }
        /// <summary>
        /// Indicate whether the source generation of the dynamic preview and the MAUI View generation can be separately handled. If the implementation returns true, the application will first call <see cref="Generate(IClip, Drawing.Base.IPicture, int, int, int, int, uint)"/> to get a source preview, and then call <see cref="IEffectDynamicPreviewProvider.Generate(IEffect, View, Type, int, int, uint, float)"/> to get the final preview. If the implementation returns false, the application will directly use the result of <see cref="Generate(IClip, Drawing.Base.IPicture, int, int, int, int, uint)"/> as the final preview without calling any effect provider.
        /// </summary>
        public bool IsPrepareGenerateDispatchable { get; }

        /// <summary>
        /// Check whether the dynamic preview can be generated for the target clip. The implementation should return false if the dynamic preview cannot be generated, and the application will use the default static preview instead. Note that this method may be called multiple times, so it should not contain heavy computations or operations that may cause side effects.
        /// </summary>
        /// <param name="target"></param>
        /// <returns></returns>
        public bool IsAvailable(IClip target);

        /// <summary>
        /// Generate a preview asynchronously from source Clip. The implementation should generate the preview based on the content of the clip at the specified frame. If the dynamic preview's source cannot be generated for any reason, set <see cref="IsPrepareGenerateDispatchable"/> to false and throw a <see cref="NotImplementedException"/> in this method, and return the view in <see cref="Generate(IClip, Drawing.Base.IPicture, int, int, int, int, uint)"/>
        /// </summary>
        /// <param name="target"></param>
        /// <param name="canvasWidth"></param>
        /// <param name="canvasHeight"></param>
        /// <param name="targetWidth"></param>
        /// <param name="targetHeight"></param>
        /// <param name="targetFrame"></param>
        /// <returns></returns>
        public Task<Drawing.Base.IPicture> PrepareSource(IClip target, int canvasWidth, int canvasHeight, int targetWidth, int targetHeight, uint targetFrame, CancellationToken cancellationToken);

        /// <summary>
        /// Generate the final preview from the source generated by <see cref="PrepareSource"/>. The implementation should generate the preview based on the content of the clip at the specified frame. If <see cref="IsPrepareGenerateDispatchable"/> is false, this method will not be called and the application will directly use the result of <see cref="PrepareSource"/> as the final preview.
        /// </summary>
        /// <remarks>
        /// Note that this method will be called on UI thread, so it should not contain heavy computations or operations that may cause side effects. 
        /// </remarks>
        /// <returns></returns>
        public View Generate(IClip target, Drawing.Base.IPicture? preparedSource, int canvasWidth, int canvasHeight, int targetWidth, int targetHeight, uint targetFrame);
    }
    public interface IEffectDynamicPreviewProvider
    {
        public string TypeName { get; }
        /// <summary>
        /// Check whether the dynamic preview can be generated for the target effect's dynamic view generated by <see cref="IClipDynamicPreviewProvider"/>. The implementation should return false if the dynamic preview cannot be generated, and the application will use the default static preview instead. Note that this method may be called multiple times, so it should not contain heavy computations or operations that may cause side effects.
        /// </summary>
        /// <param name="target"></param>
        /// <returns></returns>
        public bool IsAvailable(IEffect target, Type typeOfInput);
        /// <summary>
        /// Modify the <paramref name="input"/> view to meet the requirement of the target effect, and return the modified preview.
        /// </summary>
        /// <param name="target"></param>
        /// <param name="input"></param>
        /// <param name="canvasWidth"></param>
        /// <param name="canvasHeight"></param>
        /// <param name="targetFrame"></param>
        /// <param name="progress">A value between 0 and 1 indicating the current progress of the effect.</param>
        /// <returns></returns>
        public View Generate(IEffect target, View input, Type typeOfInput, int canvasWidth, int canvasHeight, uint targetFrame, float progress);
    }
}
