//This file contains the plugin loader code for projectFrameCut. Paste it to your plugin project and replace the class.
//TODO: Replace the namespace and class name below with your own plugin's full namespace and class name. The class must implement IPluginBase.
using MyPluginType = SomePublisher.MyPlugin;

//DO NOT EDIT BELOW THIS LINE. IT IS FIXED CODE GENERATED BY projectFrameCut.PluginPackageUtility. 
//change may cause the plugin to fail to load in projectFrameCut.

#region Loader code

using System;
using System.Collections.Generic;
using System.Text;
using System.CodeDom.Compiler;
using projectFrameCut.Render.RenderAPIBase.Plugins;

namespace projectFrameCut.Plugin
{
    [GeneratedCode("projectFrameCut.PluginPackageUtility", null)]
    public partial class AppLevelPluginLoader
    {
        public static int PluginAPIVersion => IPluginBase.CurrentPluginAPIVersion;
        public static string LocaleId = "en-US";
        public static string PluginRoot = string.Empty;

        public static IPluginBase CreateInstance(string currentLocale, string pluginRoot)
        {
            LocaleId = currentLocale;
            PluginRoot = pluginRoot;
            var instance = new MyPluginType();
            projectFrameCut.Shared.Logger.LogDiagnostic(string.Format("PluginLoader for plugin '{0}' invoked.", instance.Name));
            return (IPluginBase)instance;
        }
    }
}
#endregion