<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<AssemblyName>SomePublisher.MyPlugin</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\projectFrameCut.PluginBasePackage\projectFrameCut.PluginBasePackage.csproj" />
  </ItemGroup>

</Project>
