<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Description>projectFrameCut AI provider contracts</Description>
    <Title>projectFrameCut AI provider contracts</Title>
  </PropertyGroup>

	<ItemGroup>
		<Using Remove="projectFrameCut.Shared.Logger"/>
		<Using Remove="projectFrameCut.Drawing.Base.IPicture"/>
		<Using Remove="projectFrameCut.Drawing.Base.PictureExtensions"/>
	</ItemGroup>

</Project>
