// <auto-generated>
// This comment can avoid the 'Sync namespace' command modify this file to avoid being overwritten.
// in MAUI, if the namespace for WinUI's base is not '$(RootNamespace).WinUI', it will let whole App not working.
#nullable enable

using Microsoft.Win32;
using projectFrameCut.ApplicationAPIBase.Plugins;
using projectFrameCut.Platforms.Windows;
using projectFrameCut.Render.RenderAPIBase.Plugins;
using projectFrameCut.ScriptEngine;
using projectFrameCut.Services;
using projectFrameCut.Shared;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;

namespace projectFrameCut.WinUI
{
    public static class Program
    {
        public static bool LogWindowShowing = false;

        public static string? BasicDataPathOverride { get; private set; } = null;
        public static string? UserDataPathOverride { get; private set; } = null;

        public static bool IsStoreModeEnabled { get; private set; } = false;
        public static string? ChannelId { get; private set; } = "Global";
        public static string PackageFamilyName { get; private set; } = "Portable";

        [STAThread] //avoid failed to initialize COM library error, cause a lot of issue like IME not work at all...
        public static int Main(string[] args)
        {
            System.Threading.Thread.CurrentThread.Name = "App Main thread";
            Debug.WriteLine($"projectFrameCut {Assembly.GetExecutingAssembly().GetName().Version}");
            Debug.WriteLine($"Copyright (c) hexadecimal0x12e 2025-2026.");
            try
            {
                if (args.Contains("--consoleLog"))
                {
                    MyLoggerExtensions.OnLog += (msg, level) =>
                    {
                        Console.WriteLine($"[{level}] {msg}");
                    };
                }
                if (args.Contains("--log"))
                {
                    Thread logThread = new Thread(Helper.HelperProgram.LogMain);
                    logThread.Priority = ThreadPriority.Highest;
                    logThread.Name = "LogWindow thread";
                    logThread.IsBackground = false;
                    logThread.Start();
                    LogWindowShowing = true;
                    Log($"Logger window started.");
                }
                if (args.Contains("--logDiagnostic"))
                {
                    MyLoggerExtensions.LoggingDiagnosticInfo = true;
                }
                if (args.Contains("--waitDebugger"))
                {
                    Console.WriteLine("Waiting for debugger to attach...");
                    while (!Debugger.IsAttached)
                    {
                        Thread.Sleep(100);
                    }
                    Debugger.Break();
                }
                string processName = Process.GetCurrentProcess().ProcessName.ToLowerInvariant();
                if (processName != "projectframecut" && processName != "projectframecut.exe")
                {
                    if (!OperatingSystem.IsWindowsVersionAtLeast(10, 0, 19041, 0))
                    {
                        Console.Error.WriteLine("Sorry, projectFrameCut requires Windows 10 2004 / LTSC 2021 (build 19041) or higher to run.\r\nConsider upgrade your Windows system.");
                        return 255;
                    }
                    if (!args.Contains("--quiet"))
                    {
                        Console.WriteLine($"{Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyTitleAttribute>()?.Title ?? "projectFrameCut"} {Assembly.GetExecutingAssembly().GetName().Version}");
                        Console.WriteLine($"Copyright (c) hexadecimal0x12e 2025-2026.");
                    }

                    if (args.Any() && args.First() == "gui")
                    {
                        args = args.Skip(1).ToArray();
                        Console.WriteLine($"Launching GUI with parameters: '{string.Join(" ", args)}', press Ctrl+C to exit.");
                    }
                    else
                    {
                        return CLIProgram.CLIMain(args);
                    }

                }
            }
            catch { }

            try
            {
                try
                {
                    SimpleLocalizerBaseGeneratedHelper.Localized = SimpleLocalizer_Helper.Init();
                }
                catch { }
                if (!OperatingSystem.IsWindowsVersionAtLeast(10, 0, 19041, 0))
                {
                    var opt = MessageBox(IntPtr.Zero,
                          SimpleLocalizerBaseGeneratedHelper.Localized?.UnsupportedOSPrompt() ?? "Sorry, projectFrameCut requires Windows 10 2004 / LTSC 2021 (build 19041) or higher to run.\r\nConsider upgrade your Windows system.",
                        "projectFrameCut",
                        0x10 | 0x4);
                    if (opt == 6)
                    {
                        Process.Start(new ProcessStartInfo
                        {
                            FileName = "https://www.microsoft.com/en-us/software-download/windows11",
                            UseShellExecute = true
                        });
                    }
                    return 255;
                }
                if (Services.AdminServices.IsRunningAsAdministrator())
                {

                    _ = MessageBox(IntPtr.Zero,
                        SimpleLocalizerBaseGeneratedHelper.Localized.AdminPrompt() ?? "Sorry, projectFrameCut does not support running with administrator privileges. Reboot the app in a context which is without administrator privileges.",
                        "projectFrameCut",
                        0x10);
                    Environment.Exit(-1);
                    return 65535;
                }
                if (args.Length >= 1 && args[0].StartsWith("pjfc:runtimeConfig", StringComparison.InvariantCultureIgnoreCase))
                {
                    ConfigHandler.ConfigureMain(args.Skip(1).ToArray());
                    return 0;
                }

                try
                {
                    string pfn = "Portable";
                    bool packaged = WinUI.App.IsPackaged();
                    if (packaged)
                    {
                        pfn = WinUI.App.GetPackageFamilyName();
                        PackageFamilyName = pfn;
                        projectFrameCut.Helper.HelperProgram.AppChannel = pfn switch
                        {
                            "hexadecimal0x12e.projectFrameCutCommunity_f91nmrsqwpk6y" => "Community",
                            "0xeeeeeeeeeeee.projectFrameCutCommunity_f91nmrsqwpk6y" => "Community MS Store",
                            "hexadecimal0x12e.projectFrameCut_f91nmrsqwpk6y" => "Standard",
                            "0xeeeeeeeeeeee.projectFrameCut_f91nmrsqwpk6y" => "MS Store",
                            _ => "Non-official build"
                        };
                    }
                    else
                    {
                        projectFrameCut.Helper.HelperProgram.AppChannel = "Portable";
                    }
                    projectFrameCut.Helper.HelperProgram.AppVersion = Assembly.GetExecutingAssembly()?.GetName()?.Version?.ToString() ?? "Unknown";

                    try
                    {

                        using (RegistryKey baseKey = RegistryKey.OpenBaseKey(RegistryHive.CurrentUser, RegistryView.Registry64))
                        {
                            RegistryKey? key = null!;
                            if ((key = baseKey?.OpenSubKey(@$"SOFTWARE\hexadecimal0x12e\projectFrameCut\Instances\{pfn}")) is not null)
                            {
                                try
                                {
                                    var isStore = key.GetValue("IsStoreMode", 0) as int?;
                                    IsStoreModeEnabled = isStore != 0;
                                    ChannelId = (key.GetValue("ChannelId", "Global") as string) ?? "Global";
                                }
                                catch (Exception ex)
                                {
                                    Log(ex, "Read config");
                                    IsStoreModeEnabled = true; //if failed to read registry, assume it's in store mode to avoid potential issue, since store mode is more restricted.
                                }
                            }
                            else
                            {
                                try
                                {
                                    baseKey?.CreateSubKey(@$"SOFTWARE\hexadecimal0x12e");
                                    baseKey?.CreateSubKey(@$"SOFTWARE\hexadecimal0x12e\projectFrameCut");
                                    baseKey?.CreateSubKey(@$"SOFTWARE\hexadecimal0x12e\projectFrameCut\Instances");
                                    baseKey?.CreateSubKey(@$"SOFTWARE\hexadecimal0x12e\projectFrameCut\Instances\{pfn}");
                                    if ((key = baseKey?.OpenSubKey(@$"SOFTWARE\hexadecimal0x12e\projectFrameCut\Instances\{pfn}", true)) is not null)
                                    {
                                        key.SetValue("IsStoreMode", pfn.Equals("0xeeeeeeeeeeee.projectFrameCut_f91nmrsqwpk6y", StringComparison.InvariantCultureIgnoreCase) ? 1 : 0);
                                        key.SetValue("ChannelId", "Global");
                                    }
                                }
                                catch (Exception ex)
                                {
                                    Log(ex, "Create per-instance config");
                                }

                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        Log(ex, "Read option from Registry");
                        IsStoreModeEnabled = true; //if failed to read registry, assume it's in store mode to avoid potential issue, since store mode is more restricted.
                    }


                }
                catch (Exception ex)
                {
                    Log(ex, "Read channel");
                }
                if (args.Length > 0 && args[0].StartsWith("pjfc:", StringComparison.OrdinalIgnoreCase))
                {
                    args = ParseProtocolArgs(args);
                }
                if (args.Any(c => c.StartsWith("--overrideCulture")))
                {
                    var overrideCulture = args.First(c => c.StartsWith("--overrideCulture")).Split('=')[1];
                    var culture = new System.Globalization.CultureInfo(overrideCulture);
                    System.Globalization.CultureInfo.DefaultThreadCurrentCulture = culture;
                    System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = culture;
                    System.Threading.Thread.CurrentThread.CurrentCulture = culture;
                    System.Threading.Thread.CurrentThread.CurrentUICulture = culture;
                    MauiProgram.NoOverrideCulture = true;
                }
                if (!args.Any(c => c.StartsWith("--noSplash")))
                {
                    var splash = new Thread(projectFrameCut.Helper.HelperProgram.SplashMain);
                    splash.Priority = ThreadPriority.Highest;
                    splash.IsBackground = false;
                    splash.Start();
                }
                if (args.Any(c => c.StartsWith("--basicUserData")))
                {
                    var userDataPath = args.First(c => c.StartsWith("--basicUserData")).Split('=', 2)[1];
                    BasicDataPathOverride = userDataPath;
                }
                if (args.Any(c => c.StartsWith("--userData")))
                {
                    var userDataPath = args.First(c => c.StartsWith("--userData")).Split('=', 2)[1];
                    UserDataPathOverride = userDataPath;
                }
                if (args.FirstOrDefault(c => c.StartsWith("--scripting")) == "--scripting=enableWithHostingPipe")
                {
                    Console.WriteLine($"WARNNING: Enable scripting with hosting pipe is a dangerous option, it it allows arbitrary code execution from a remote process.");
                    Console.WriteLine($"Only use this option if you know what you are doing, and you trust everything on this computer.");
                    Console.WriteLine($"Press Y to continue:");
                    if (Console.ReadKey().Key != ConsoleKey.Y)
                    {
                        Console.WriteLine($"Aborted.");
                        return 1;
                    }
                    Environment.SetEnvironmentVariable(
                        "POWERSHELL_DISABLE_NAMED_PIPE",
                        "false",
                        EnvironmentVariableTarget.Process
                    );
                    Console.WriteLine($"Connect to the hosting pipe by using the PowerShell command: Enter-PSHostProcess -Id {Environment.ProcessId}");
                }
                else
                {
                    if (args.FirstOrDefault(c => c.StartsWith("--scripting")) == "--scripting=disable")
                    {
                        ScriptCore.Enabled = false;
                    }
                    Environment.SetEnvironmentVariable(
                        "POWERSHELL_DISABLE_NAMED_PIPE",
                        "true",
                        EnvironmentVariableTarget.Process
                    );
                }
                MauiProgram.CmdlineArgs = args;
            }
            catch
            {

            }
            try
            {
                Log("Initializing application...");
                WinRT.ComWrappersSupport.InitializeComWrappers();
                Microsoft.UI.Xaml.Application.Start((p) =>
                {
                    var context = new Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
                    SynchronizationContext.SetSynchronizationContext(context);
                    new App();
                });
                RenderRpcBootstrap.DisposeAsync().AsTask().GetAwaiter().GetResult();
                Helper.CrashHandler.Handler?.Kill(true);
                _ = SettingsManager.FlushAndStopAsync();
                Helper.HelperProgram.Cleanup();
                try
                {
                    foreach (var item in Render.Plugin.PluginManager.LoadedPlugins)
                    {
                        try
                        {
                            item.Value.OnClosing();
                        }
                        catch { }
                    }
                }
                catch { }
                Log("Application exited.");
                MauiProgram.LogWriter.Flush();
                Environment.Exit(0);
                return 0;
            }
            catch (Exception ex)
            {
                _ = MessageBox(IntPtr.Zero,
                    $"Oh no! projectFrameCut have to stop now because a unrecoverable {ex.GetType().Name} exception happens.\r\nFor more information, please see the crash report popped up later.\r\n\r\n({ex})",
                    "Fatal error",
                    0x10);
                Crash(ex);
            }

            return -1;
        }

        private static string[] ParseProtocolArgs(string[] args)
        {
            var protocolPayload = args[0].Substring(5);

            if (TryParseFileProtocolPayload(protocolPayload, out var filePath, out var queryArgs))
            {
                var parsedArgs = new List<string> { filePath };
                parsedArgs.AddRange(queryArgs);
                parsedArgs.AddRange(args.Skip(1));

                Log("Params read from protocol URI: " + string.Join(' ', parsedArgs.Select(c => $"'{c}'")));
                return parsedArgs.ToArray();
            }

            // Keep legacy behavior for protocol payloads like "pjfc:--log --noSplash".
            var fallbackArgs = protocolPayload
                .Split(' ', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
                .Concat(args.Skip(1))
                .ToArray();
            Log("Params read from protocol: " + string.Join(' ', fallbackArgs.Select(c => $"'{c}'")));
            return fallbackArgs;
        }

        private static bool TryParseFileProtocolPayload(string payload, out string filePath, out string[] queryArgs)
        {
            filePath = string.Empty;
            queryArgs = Array.Empty<string>();

            if (!payload.StartsWith("file:", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            var queryStartIndex = payload.IndexOf('?');
            var fileUriText = queryStartIndex >= 0 ? payload[..queryStartIndex] : payload;
            var query = queryStartIndex >= 0 ? payload[(queryStartIndex + 1)..] : string.Empty;

            if (!Uri.TryCreate(fileUriText, UriKind.Absolute, out var fileUri) ||
                !string.Equals(fileUri.Scheme, Uri.UriSchemeFile, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            filePath = fileUri.LocalPath;
            if (OperatingSystem.IsWindows() && filePath.Length >= 3 && filePath[0] == '/' && char.IsLetter(filePath[1]) && filePath[2] == ':')
            {
                filePath = filePath[1..];
            }

            if (string.IsNullOrWhiteSpace(filePath))
            {
                return false;
            }

            queryArgs = ParseQueryArguments(query).ToArray();
            return true;
        }

        private static IEnumerable<string> ParseQueryArguments(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                yield break;
            }

            foreach (var segment in query.Split('&', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var equalsIndex = segment.IndexOf('=');
                if (equalsIndex < 0)
                {
                    var decodedSingle = Uri.UnescapeDataString(segment.Replace('+', ' '));
                    if (!string.IsNullOrWhiteSpace(decodedSingle))
                    {
                        yield return decodedSingle;
                    }
                    continue;
                }

                var keyPart = segment[..equalsIndex];
                if (string.IsNullOrWhiteSpace(keyPart))
                {
                    continue;
                }

                var valuePart = segment[(equalsIndex + 1)..];
                var decodedKey = Uri.UnescapeDataString(keyPart.Replace('+', ' '));
                var decodedValue = Uri.UnescapeDataString(valuePart.Replace('+', ' '));
                yield return $"{decodedKey}={decodedValue}";
            }
        }

        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        public static extern int MessageBox(IntPtr hWnd, String text, String caption, uint type);

        [DoesNotReturn]
        public static void Crash(Exception ex)
        {
            MauiProgram.LogWriter?.Flush();

            try
            {
                MauiProgram.LogWriter?.WriteLine("*** FATAL: CRASH");
                Log(ex, "", "Application");
                Log($"Crash() is invoked by:{Environment.StackTrace}.", "fatal");
                MauiProgram.LogWriter?.Flush();

            }
            catch (Exception) { }

#if DEBUG
            if (Debugger.IsAttached)
            {
                Debugger.BreakForUserUnhandledException(ex);
                Environment.Exit(ex.HResult);
            }
#endif


            string innerExceptionInfo = "None";
            if (ex.InnerException != null)
            {
                innerExceptionInfo =
$"""
ClipType: {ex.InnerException.GetType().Name}                        
Message: {ex.InnerException.Message}
StackTrace:
{ex.InnerException.StackTrace}

""";
            }

            string header =
"""
Sorry, the application has encountered an unhandled exception and needs to close now.
Your works have been saved automatically when you make any change on the UI, so you won't lose your work.
If you want to help the development of this application, please consider to submit an issue or send this report to me.
""";
            try
            {
                if (Localized is not null) header = Localized.AppCrashed;
            }
            catch { }
            string appInfo = $"Application: {Assembly.GetExecutingAssembly().GetName().FullName}";
            try
            {
                appInfo = Setting.SettingPages.DiagnosticSettingPage.GetAppInfo(false, false);
            }
            catch
            {
                appInfo =
$"""
{Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyTitleAttribute>()?.Title ?? "unknown"}: {Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyConfigurationAttribute>()?.Configuration ?? "unknown config"}@{new string((Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion ?? "0.1.2+unknown commit").Skip(6).ToArray())}  
Assembly: {AppInfo.PackageName},{AppInfo.VersionString} on {AppContext.TargetFrameworkName} Packaged:{WinUI.App.IsPackaged()}
IPluginBase API: v{IPluginBase.CurrentPluginAPIVersion} | IApplicationPluginBase API: v{IApplicationPluginBase.CurrentAppLevelPluginAPIVersion}

OS version: {Environment.OSVersion}
CLR Version:{Environment.Version}
Command line: {Environment.CommandLine}
Current directory: {Environment.CurrentDirectory}
""";
            }
            var content =
$"""
Exception type: {ex.GetType().Name}
Message: {ex.Message}
StackTrace:
{ex.StackTrace}

From:{(ex.TargetSite is not null ? ex.TargetSite.ToString() : "unknown")}
InnerException:
{innerExceptionInfo}

Exception data:
{string.Join("\r\n", ex.Data.Cast<System.Collections.DictionaryEntry>().Select(k => $"{k.Key} : {k.Value}"))}

Environment:
{appInfo}

(report ended here)
""";
            string logPath, logMessage;

            try
            {
                Directory.CreateDirectory(Path.Combine(MauiProgram.DataPath, "Crashlogs"));
                logPath = Path.Combine(MauiProgram.DataPath, "Crashlogs", $"Crashlog-{DateTime.Now:yyyy-MM-dd-hh-mm-ss}.log");
                logMessage = $"{header}\r\nthis log is in: {logPath}\r\n\r\n{content}";
                File.WriteAllText(logPath, logMessage);
            }
            catch (Exception)
            {
                logPath = Path.Combine(Directory.CreateTempSubdirectory("projectFrameCut_").FullName, "crash.log");
                logMessage = $"{header}\r\nthis log is in: {logPath}\r\n\r\n{content}";
                File.WriteAllText(logPath, logMessage);
            }
            Thread.Sleep(100);

            try
            {
                if (!Helper.CrashHandler.Handler?.HasExited ?? false) //let handler handle it
                {
                    Environment.Exit(ex.HResult);
                }
                string processName = Process.GetCurrentProcess().ProcessName.ToLowerInvariant();
                if (processName != "projectframecut" && processName != "projectframecut.exe")
                {
                    Console.Error.WriteLine("********************");
                    Console.Error.WriteLine("*** FATAL: CRASH ***");
                    Console.Error.WriteLine("********************");
                    Console.Error.WriteLine();
                    Console.Error.WriteLine(logMessage);
                    Environment.Exit(ex.HResult);
                }
            }
            catch { }

            if (File.Exists(Path.Combine(AppContext.BaseDirectory, "projectFrameCut.Helper.dll")))
            {
                try
                {

                    string bootArgs = $"\"{Path.Combine(AppContext.BaseDirectory, "projectFrameCut.Helper.dll")}\" crashForm \"{logPath}\" \"{MauiProgram.LogPath}\"";
                    Log($"CrashForm boot args: {bootArgs}", "fatal");
                    var p = Process.Start(new ProcessStartInfo
                    {
                        FileName = "dotnet.exe",
                        Arguments = bootArgs,
                        UseShellExecute = false,
                        CreateNoWindow = true
                    });
                    p.WaitForExit(5000);
                    if (p.HasExited && p.ExitCode != 0)
                    {
                        Process.Start(new ProcessStartInfo { FileName = logPath, UseShellExecute = true });
                    }
                }
                catch (Exception)
                {
                    Process.Start(new ProcessStartInfo { FileName = logPath, UseShellExecute = true });
                }
            }
            else
            {
                Process.Start(new ProcessStartInfo { FileName = logPath, UseShellExecute = true });
            }

            MauiProgram.LogWriter?.Flush();
            Helper.HelperProgram.Cleanup();

            Environment.FailFast(logMessage, ex);
            Environment.Exit(ex.HResult);

        }

        public static void RebootApp()
        {
            if (!WinUI.App.IsPackaged())
            {
                Environment.Exit(0);
            }
            else
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = "explorer.exe",
                    Arguments = $"shell:AppsFolder\\{PackageFamilyName}!App",
                    UseShellExecute = true
                });
            }
        }

    }
}
