// <auto-generated>
// Generated in 2025/12/20 15:30:02
// These code are generated by SimpleLocalizer. Don't modify it directly; modify the 'localized.json' file and regenerate code to apply changes.
// </auto-generated>

#nullable enable
#region usings
using System;
using System.Collections.Concurrent;
using System.CodeDom.Compiler;
using System.Diagnostics;
#endregion

#region base interface
/// <summary>
/// This is the base interface for all localizers.
/// </summary>
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
public interface ISimpleLocalizerBase_PropertyPanel
{
    /// <summary>
    /// Get the localized string for _Apply (like '
    /// 应用
    ///')
    /// </summary>
    public string _Apply { get; }
    
    /// <summary>
    /// Get the localized string for _Enabled (like '
    /// 启用
    ///')
    /// </summary>
    public string _Enabled { get; }
    
    /// <summary>
    /// Get the localized string for _EnabledSomething (like '
    /// 启用 {something}
    ///')
    /// </summary>
    public string _EnabledSomething(string something);
    
    /// <summary>
    /// Get the localized string for _Height (like '
    /// 高度
    ///')
    /// </summary>
    public string _Height { get; }
    
    /// <summary>
    /// Get the localized string for _PluginBase_Description_ (like '
    /// 作为 projectFrameCut 的一部分，提供 projectFrameCut 的基本功能
    ///')
    /// </summary>
    /// <remarks>
    /// 不要翻译“projectFrameCut ”，这是应用程序的名字
    /// </remarks>
    public string _PluginBase_Description_ { get; }
    
    /// <summary>
    /// Get the localized string for _PluginBase_Name_ (like '
    /// projectFrameCut 基础组件插件
    ///')
    /// </summary>
    public string _PluginBase_Name_ { get; }
    
    /// <summary>
    /// Get the localized string for _StartX (like '
    /// 起始 X 轴坐标
    ///')
    /// </summary>
    public string _StartX { get; }
    
    /// <summary>
    /// Get the localized string for _StartY (like '
    /// 起始 Y 轴坐标
    ///')
    /// </summary>
    public string _StartY { get; }
    
    /// <summary>
    /// Get the localized string for _Width (like '
    /// 宽度
    ///')
    /// </summary>
    public string _Width { get; }
    
    /// <summary>
    /// Get the localized string for Add_Effect (like '
    /// 添加一个效果...
    ///')
    /// </summary>
    public string Add_Effect { get; }
    
    /// <summary>
    /// Get the localized string for Add_Effect_Select (like '
    /// 选择一个效果
    ///')
    /// </summary>
    public string Add_Effect_Select { get; }
    
    /// <summary>
    /// Get the localized string for EffectProp_Index (like '
    /// 渲染顺序
    ///')
    /// </summary>
    public string EffectProp_Index { get; }
    
    /// <summary>
    /// Get the localized string for EffectProp_Remove (like '
    /// 移除这个效果...
    ///')
    /// </summary>
    public string EffectProp_Remove { get; }
    
    /// <summary>
    /// Get the localized string for PropertyPanel (like '
    /// 属性面板
    ///')
    /// </summary>
    public string PropertyPanel { get; }
    
    /// <summary>
    /// Get the current Locale's ID (like 'zh-CN')
    /// </summary>
    public string _LocaleId_ { get; }
    
    public static Dictionary<string, ISimpleLocalizerBase_PropertyPanel> GetMapping()
    {
        return new Dictionary<string, ISimpleLocalizerBase_PropertyPanel>()
        {
            { "zh-CN", new  __ISimpleLocalizerBase_PropertyPanel_zh_CN__() },
            { "en-US", new  __ISimpleLocalizerBase_PropertyPanel_en_US__() },
            { "zh-TW", new  __ISimpleLocalizerBase_PropertyPanel_zh_TW__() },
            { "ja-JP", new  __ISimpleLocalizerBase_PropertyPanel_ja_JP__() },
            { "ko-KR", new  __ISimpleLocalizerBase_PropertyPanel_ko_KR__() },
            { "fr-FR", new  __ISimpleLocalizerBase_PropertyPanel_fr_FR__() },
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="fallbackValue">The fallback value when the localized string isn't found.</param>
    /// <returns>The localized string you want.</returns>
    public string DynamicLookup(string id, string? fallbackValue = null)
    {
        return id switch
        {
            "_Apply" => _Apply,
            "_Enabled" => _Enabled,
            "_Height" => _Height,
            "_PluginBase_Description_" => _PluginBase_Description_,
            "_PluginBase_Name_" => _PluginBase_Name_,
            "_StartX" => _StartX,
            "_StartY" => _StartY,
            "_Width" => _Width,
            "Add_Effect" => Add_Effect,
            "Add_Effect_Select" => Add_Effect_Select,
            "EffectProp_Index" => EffectProp_Index,
            "EffectProp_Remove" => EffectProp_Remove,
            "PropertyPanel" => PropertyPanel,
            _ => fallbackValue ?? $"Can't find the localized string for id '{id}'"
        };
    }
    /// <summary>
    /// Dynamically lookup the localized string by the given id with some arguments.
    /// </summary>
    /// <param name="id">The key of the localized item you want.</param>
    /// <param name="args">The arguments to format the localized string.</param>
    /// <returns>The localized string with arguments applied.</returns>
    /// <exception cref="KeyNotFoundException">The localized string you want with arguments isn't found.</exception>
    /// <exception cref="IndexOutOfRangeException">The number of arguments provided does not match the expected number for the localized string.</exception>
    public string DynamicLookupWithArgs(string id, params object[] args)
    {
        return id switch
        {
            "_EnabledSomething" => _EnabledSomething((string)args[0]),
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}' with any argument")
        };
    }
}

#endregion

#region zh_CN
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_PropertyPanel_zh_CN__ : ISimpleLocalizerBase_PropertyPanel
{
    /// <summary>
    /// Get the localized string for _Apply in zh-CN (like '
    /// 应用
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Apply => _Apply;
    public const string _Apply = @"应用";
    
    /// <summary>
    /// Get the localized string for _Enabled in zh-CN (like '
    /// 启用
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Enabled => _Enabled;
    public const string _Enabled = @"启用";
    
    /// <summary>
    /// Get the localized string for _EnabledSomething in zh-CN (like '
    /// 启用 {something}
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._EnabledSomething(string something) => _EnabledSomething(something);
    public string _EnabledSomething(string something) => @$"启用 {something}";
    
    /// <summary>
    /// Get the localized string for _Height in zh-CN (like '
    /// 高度
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Height => _Height;
    public const string _Height = @"高度";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Description_ in zh-CN (like '
    /// 作为 projectFrameCut 的一部分，提供 projectFrameCut 的基本功能
    /// ')
    /// </summary>
    /// <remarks>
    /// 不要翻译“projectFrameCut ”，这是应用程序的名字
    /// </remarks>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Description_ => _PluginBase_Description_;
    public const string _PluginBase_Description_ = @"作为 projectFrameCut 的一部分，提供 projectFrameCut 的基本功能";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Name_ in zh-CN (like '
    /// projectFrameCut 基础组件插件
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Name_ => _PluginBase_Name_;
    public const string _PluginBase_Name_ = @"projectFrameCut 基础组件插件";
    
    /// <summary>
    /// Get the localized string for _StartX in zh-CN (like '
    /// 起始 X 轴坐标
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartX => _StartX;
    public const string _StartX = @"起始 X 轴坐标";
    
    /// <summary>
    /// Get the localized string for _StartY in zh-CN (like '
    /// 起始 Y 轴坐标
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartY => _StartY;
    public const string _StartY = @"起始 Y 轴坐标";
    
    /// <summary>
    /// Get the localized string for _Width in zh-CN (like '
    /// 宽度
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Width => _Width;
    public const string _Width = @"宽度";
    
    /// <summary>
    /// Get the localized string for Add_Effect in zh-CN (like '
    /// 添加一个效果...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect => Add_Effect;
    public const string Add_Effect = @"添加一个效果...";
    
    /// <summary>
    /// Get the localized string for Add_Effect_Select in zh-CN (like '
    /// 选择一个效果
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect_Select => Add_Effect_Select;
    public const string Add_Effect_Select = @"选择一个效果";
    
    /// <summary>
    /// Get the localized string for EffectProp_Index in zh-CN (like '
    /// 渲染顺序
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Index => EffectProp_Index;
    public const string EffectProp_Index = @"渲染顺序";
    
    /// <summary>
    /// Get the localized string for EffectProp_Remove in zh-CN (like '
    /// 移除这个效果...
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Remove => EffectProp_Remove;
    public const string EffectProp_Remove = @"移除这个效果...";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in zh-CN (like '
    /// 属性面板
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.PropertyPanel => PropertyPanel;
    public const string PropertyPanel = @"属性面板";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-CN";
    
    
}

#endregion

#region en_US
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_PropertyPanel_en_US__ : ISimpleLocalizerBase_PropertyPanel
{
    /// <summary>
    /// Get the localized string for _Apply in en-US (like '
    /// Apply
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Apply => _Apply;
    public const string _Apply = @"Apply";
    
    /// <summary>
    /// Get the localized string for _Enabled in en-US (like '
    /// Enabled
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Enabled => _Enabled;
    public const string _Enabled = @"Enabled";
    
    /// <summary>
    /// Get the localized string for _EnabledSomething in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._EnabledSomething(string something) => _EnabledSomething(something);
    public string _EnabledSomething(string something) => @$"";
    
    /// <summary>
    /// Get the localized string for _Height in en-US (like '
    /// Height
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Height => _Height;
    public const string _Height = @"Height";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Description_ in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Description_ => _PluginBase_Description_;
    public const string _PluginBase_Description_ = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Name_ in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Name_ => _PluginBase_Name_;
    public const string _PluginBase_Name_ = @"";
    
    /// <summary>
    /// Get the localized string for _StartX in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartX => _StartX;
    public const string _StartX = @"";
    
    /// <summary>
    /// Get the localized string for _StartY in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartY => _StartY;
    public const string _StartY = @"";
    
    /// <summary>
    /// Get the localized string for _Width in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Width => _Width;
    public const string _Width = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect => Add_Effect;
    public const string Add_Effect = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect_Select in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect_Select => Add_Effect_Select;
    public const string Add_Effect_Select = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Index in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Index => EffectProp_Index;
    public const string EffectProp_Index = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Remove in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Remove => EffectProp_Remove;
    public const string EffectProp_Remove = @"";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in en-US (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.PropertyPanel => PropertyPanel;
    public const string PropertyPanel = @"";
    
    /// <summary>
    /// Get the current localized Id (like 'e')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"en-US";
    
    
}

#endregion

#region zh_TW
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_PropertyPanel_zh_TW__ : ISimpleLocalizerBase_PropertyPanel
{
    /// <summary>
    /// Get the localized string for _Apply in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Apply => _Apply;
    public const string _Apply = @"";
    
    /// <summary>
    /// Get the localized string for _Enabled in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Enabled => _Enabled;
    public const string _Enabled = @"";
    
    /// <summary>
    /// Get the localized string for _EnabledSomething in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._EnabledSomething(string something) => _EnabledSomething(something);
    public string _EnabledSomething(string something) => @$"";
    
    /// <summary>
    /// Get the localized string for _Height in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Height => _Height;
    public const string _Height = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Description_ in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Description_ => _PluginBase_Description_;
    public const string _PluginBase_Description_ = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Name_ in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Name_ => _PluginBase_Name_;
    public const string _PluginBase_Name_ = @"";
    
    /// <summary>
    /// Get the localized string for _StartX in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartX => _StartX;
    public const string _StartX = @"";
    
    /// <summary>
    /// Get the localized string for _StartY in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartY => _StartY;
    public const string _StartY = @"";
    
    /// <summary>
    /// Get the localized string for _Width in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Width => _Width;
    public const string _Width = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect => Add_Effect;
    public const string Add_Effect = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect_Select in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect_Select => Add_Effect_Select;
    public const string Add_Effect_Select = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Index in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Index => EffectProp_Index;
    public const string EffectProp_Index = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Remove in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Remove => EffectProp_Remove;
    public const string EffectProp_Remove = @"";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in zh-TW (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.PropertyPanel => PropertyPanel;
    public const string PropertyPanel = @"";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-TW";
    
    
}

#endregion

#region ja_JP
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_PropertyPanel_ja_JP__ : ISimpleLocalizerBase_PropertyPanel
{
    /// <summary>
    /// Get the localized string for _Apply in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Apply => _Apply;
    public const string _Apply = @"";
    
    /// <summary>
    /// Get the localized string for _Enabled in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Enabled => _Enabled;
    public const string _Enabled = @"";
    
    /// <summary>
    /// Get the localized string for _EnabledSomething in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._EnabledSomething(string something) => _EnabledSomething(something);
    public string _EnabledSomething(string something) => @$"";
    
    /// <summary>
    /// Get the localized string for _Height in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Height => _Height;
    public const string _Height = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Description_ in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Description_ => _PluginBase_Description_;
    public const string _PluginBase_Description_ = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Name_ in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Name_ => _PluginBase_Name_;
    public const string _PluginBase_Name_ = @"";
    
    /// <summary>
    /// Get the localized string for _StartX in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartX => _StartX;
    public const string _StartX = @"";
    
    /// <summary>
    /// Get the localized string for _StartY in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartY => _StartY;
    public const string _StartY = @"";
    
    /// <summary>
    /// Get the localized string for _Width in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Width => _Width;
    public const string _Width = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect => Add_Effect;
    public const string Add_Effect = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect_Select in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect_Select => Add_Effect_Select;
    public const string Add_Effect_Select = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Index in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Index => EffectProp_Index;
    public const string EffectProp_Index = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Remove in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Remove => EffectProp_Remove;
    public const string EffectProp_Remove = @"";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in ja-JP (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.PropertyPanel => PropertyPanel;
    public const string PropertyPanel = @"";
    
    /// <summary>
    /// Get the current localized Id (like 'j')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"ja-JP";
    
    
}

#endregion

#region ko_KR
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_PropertyPanel_ko_KR__ : ISimpleLocalizerBase_PropertyPanel
{
    /// <summary>
    /// Get the localized string for _Apply in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Apply => _Apply;
    public const string _Apply = @"";
    
    /// <summary>
    /// Get the localized string for _Enabled in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Enabled => _Enabled;
    public const string _Enabled = @"";
    
    /// <summary>
    /// Get the localized string for _EnabledSomething in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._EnabledSomething(string something) => _EnabledSomething(something);
    public string _EnabledSomething(string something) => @$"";
    
    /// <summary>
    /// Get the localized string for _Height in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Height => _Height;
    public const string _Height = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Description_ in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Description_ => _PluginBase_Description_;
    public const string _PluginBase_Description_ = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Name_ in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Name_ => _PluginBase_Name_;
    public const string _PluginBase_Name_ = @"";
    
    /// <summary>
    /// Get the localized string for _StartX in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartX => _StartX;
    public const string _StartX = @"";
    
    /// <summary>
    /// Get the localized string for _StartY in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartY => _StartY;
    public const string _StartY = @"";
    
    /// <summary>
    /// Get the localized string for _Width in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Width => _Width;
    public const string _Width = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect => Add_Effect;
    public const string Add_Effect = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect_Select in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect_Select => Add_Effect_Select;
    public const string Add_Effect_Select = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Index in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Index => EffectProp_Index;
    public const string EffectProp_Index = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Remove in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Remove => EffectProp_Remove;
    public const string EffectProp_Remove = @"";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in ko-KR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.PropertyPanel => PropertyPanel;
    public const string PropertyPanel = @"";
    
    /// <summary>
    /// Get the current localized Id (like 'k')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"ko-KR";
    
    
}

#endregion

#region fr_FR
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __ISimpleLocalizerBase_PropertyPanel_fr_FR__ : ISimpleLocalizerBase_PropertyPanel
{
    /// <summary>
    /// Get the localized string for _Apply in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Apply => _Apply;
    public const string _Apply = @"";
    
    /// <summary>
    /// Get the localized string for _Enabled in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Enabled => _Enabled;
    public const string _Enabled = @"";
    
    /// <summary>
    /// Get the localized string for _EnabledSomething in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._EnabledSomething(string something) => _EnabledSomething(something);
    public string _EnabledSomething(string something) => @$"";
    
    /// <summary>
    /// Get the localized string for _Height in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Height => _Height;
    public const string _Height = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Description_ in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Description_ => _PluginBase_Description_;
    public const string _PluginBase_Description_ = @"";
    
    /// <summary>
    /// Get the localized string for _PluginBase_Name_ in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._PluginBase_Name_ => _PluginBase_Name_;
    public const string _PluginBase_Name_ = @"";
    
    /// <summary>
    /// Get the localized string for _StartX in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartX => _StartX;
    public const string _StartX = @"";
    
    /// <summary>
    /// Get the localized string for _StartY in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._StartY => _StartY;
    public const string _StartY = @"";
    
    /// <summary>
    /// Get the localized string for _Width in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._Width => _Width;
    public const string _Width = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect => Add_Effect;
    public const string Add_Effect = @"";
    
    /// <summary>
    /// Get the localized string for Add_Effect_Select in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.Add_Effect_Select => Add_Effect_Select;
    public const string Add_Effect_Select = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Index in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Index => EffectProp_Index;
    public const string EffectProp_Index = @"";
    
    /// <summary>
    /// Get the localized string for EffectProp_Remove in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.EffectProp_Remove => EffectProp_Remove;
    public const string EffectProp_Remove = @"";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in fr-FR (like '
    /// ')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel.PropertyPanel => PropertyPanel;
    public const string PropertyPanel = @"";
    
    /// <summary>
    /// Get the current localized Id (like 'f')
    /// </summary>
    string ISimpleLocalizerBase_PropertyPanel._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"fr-FR";
    
    
}

#endregion
namespace LocalizedResources
{
    public static class SimpleLocalizerBaseGeneratedHelper_PropertyPanel
    {
        /// <summary>
        /// Get the default localizer instance.
        /// </summary>
        /// <remarks>
        /// You need to initialize this property before using it.
        /// </remarks>
        public static ISimpleLocalizerBase_PropertyPanel PPLocalizedResources { get; set; } = null!;
    }
    
}
