// <auto-generated/>
// Generated in 2025/11/10 23:54:26
// These code are generated by SimpleLocalizer. Don't modify it directly; modify the 'localized.json' file and regenerate to apply changes.
// <auto-generated/>

using System;
using System.Collections.Concurrent;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;

/// <summary>
/// This is the base interface for all localizers.
/// </summary>
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
public interface ISimpleLocalizerBase
{
    /// <summary>
    /// Get the localized string for _Cancel (like '取消')
    /// </summary>
    public string _Cancel { get; }
    
    /// <summary>
    /// Get the localized string for _ExceptionTemplate (like '一个未被处理的 {ex.GetType().Name} 异常发生 ({ex.Message})')
    /// </summary>
    /// <param name="ex">异常</param>
    public string _ExceptionTemplate(Exception ex);
    
    /// <summary>
    /// Get the localized string for _Info (like '提示')
    /// </summary>
    public string _Info { get; }
    
    /// <summary>
    /// Get the localized string for _LocateDisplayName (like '简体中文 / Simplified Chinese')
    /// </summary>
    /// <remarks>
    /// 翻译时，请按照下列格式输出结果：
    /// 目标语言在目标语言的名字 / 目标语言在英语（英国）的名字，
    /// 比如当TargetLanguage是&quot;ja-JP&quot;时输出 “日本語 / Japanese”
    /// </remarks>
    public string _LocateDisplayName { get; }
    
    /// <summary>
    /// Get the localized string for _OK (like '好的')
    /// </summary>
    public string _OK { get; }
    
    /// <summary>
    /// Get the localized string for _Options (like '选项')
    /// </summary>
    public string _Options { get; }
    
    /// <summary>
    /// Get the localized string for _Processing (like '处理中...')
    /// </summary>
    public string _Processing { get; }
    
    /// <summary>
    /// Get the localized string for _Warn (like '警告')
    /// </summary>
    public string _Warn { get; }
    
    /// <summary>
    /// Get the localized string for AppBrand (like 'projectFrameCut(仮)')
    /// </summary>
    /// <remarks>
    /// 不要翻译，这是软件的名字
    /// </remarks>
    public string AppBrand { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_AddOneAsset (like '松手来添加「{name ?? "未知名称"}」 ')
    /// </summary>
    /// <param name="name">素材的名字</param>
    public string DraftPage_AddOneAsset(string? name);
    
    /// <summary>
    /// Get the localized string for DraftPage_ApplyingChanges (like '正在应用更改...')
    /// </summary>
    public string DraftPage_ApplyingChanges { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_AssetAdded (like '成功添加素材「{name}」')
    /// </summary>
    public string DraftPage_AssetAdded(string name);
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus (like '后端延迟{lantency.ToString("n2")}ms, 内存占用{menUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (后端/此电脑)')
    /// </summary>
    public string DraftPage_BackendStatus(double lantency, double menUsed, double menTotalUsed);
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_MemoryOnly (like '程序已使用内存: {menUsed}')
    /// </summary>
    public string DraftPage_BackendStatus_MemoryOnly(double menUsed);
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_NotRespond (like '后端未响应， 内存占用{menTotalUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (后端/此电脑)')
    /// </summary>
    public string DraftPage_BackendStatus_NotRespond(double menUsed, double menTotalUsed);
    
    /// <summary>
    /// Get the localized string for DraftPage_CannotMoveBecauseOfOverlap (like '操作未被应用，因为此操作会导致重叠')
    /// </summary>
    public string DraftPage_CannotMoveBecauseOfOverlap { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_ChangesApplied (like '更改已被应用')
    /// </summary>
    public string DraftPage_ChangesApplied { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset (like '素材{newAsset}似乎和{existed}重复了{Environment.NewLine}你想要做什么？')
    /// </summary>
    public string DraftPage_DuplicatedAsset(string newAsset, string existed);
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Relpace (like '使用新的替换旧的')
    /// </summary>
    public string DraftPage_DuplicatedAsset_Relpace { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Skip (like '保留旧的')
    /// </summary>
    public string DraftPage_DuplicatedAsset_Skip { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Together (like '同时保留')
    /// </summary>
    public string DraftPage_DuplicatedAsset_Together { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_EverythingFine (like '就绪')
    /// </summary>
    public string DraftPage_EverythingFine { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_GoRender (like '去渲染')
    /// </summary>
    public string DraftPage_GoRender { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_ImportAssetNotFinished (like '松手来导入素材...')
    /// </summary>
    public string DraftPage_ImportAssetNotFinished { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_JobRunning (like '{count} 任务正在执行')
    /// </summary>
    public string DraftPage_JobRunning(int count);
    
    /// <summary>
    /// Get the localized string for DraftPage_NoJobRunning (like '没有正在执行的任务')
    /// </summary>
    public string DraftPage_NoJobRunning { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_PrepareAsset (like '准备素材...')
    /// </summary>
    public string DraftPage_PrepareAsset { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Processing (like '处理中...')
    /// </summary>
    public string DraftPage_Processing { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_ReachLimit (like '达到片段的长度限制({length})')
    /// </summary>
    public string DraftPage_ReachLimit(string length);
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToCancel (like '松手来取消操作...')
    /// </summary>
    public string DraftPage_ReleaseToCancel { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToRemove (like '松手来移除此片段...')
    /// </summary>
    public string DraftPage_ReleaseToRemove { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Removed (like '已移除')
    /// </summary>
    public string DraftPage_Removed { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderDone (like '渲染已完成')
    /// </summary>
    public string DraftPage_RenderDone { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderOneFrame (like '渲染第{frameIndex}帧 ({playheadSeconds.ToString("mm\\:ss\\.ff")})...')
    /// </summary>
    public string DraftPage_RenderOneFrame(int frameIndex, TimeSpan playheadSeconds);
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderTimeout (like '错误：渲染超时')
    /// </summary>
    public string DraftPage_RenderTimeout { get; }
    
    /// <summary>
    /// Get the localized string for DraftPage_Selected (like '已选中「{clipName}」')
    /// </summary>
    public string DraftPage_Selected(string clipName);
    
    /// <summary>
    /// Get the localized string for DraftPage_Track (like '轨道 #{trackId}')
    /// </summary>
    public string DraftPage_Track(int trackId);
    
    /// <summary>
    /// Get the localized string for DraftPage_WaitForUser (like '等待操作完成...')
    /// </summary>
    public string DraftPage_WaitForUser { get; }
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_MemoryNotEnough (like '你的设备内存不足，程序可能会遇到一些问题。请尽快保存所有的数据以避免闪退造成的数据丢失。')
    /// </summary>
    /// <remarks>
    /// 内存指运行内存
    /// </remarks>
    public string iDevicesAPI_MemoryNotEnough { get; }
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_TooHot (like '你的设备过热。请尽快保存所有的数据，并且在设备冷却之后继续使用，以避免对硬件造成损害或者数据丢失。')
    /// </summary>
    public string iDevicesAPI_TooHot { get; }
    
    /// <summary>
    /// Get the localized string for LandingPage_BackToContent (like '点击这里回到主界面')
    /// </summary>
    public string LandingPage_BackToContent { get; }
    
    /// <summary>
    /// Get the localized string for LandingPage_Loading (like '加载中...')
    /// </summary>
    public string LandingPage_Loading { get; }
    
    /// <summary>
    /// Get the localized string for LandingPage_TakingToDraft (like '请稍后，正在打开草稿 「{name}」')
    /// </summary>
    public string LandingPage_TakingToDraft(string name);
    
    /// <summary>
    /// Get the localized string for PropertyPanel (like '属性面板')
    /// </summary>
    public string PropertyPanel { get; }
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General (like '通用')
    /// </summary>
    public string PropertyPanel_General { get; }
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_DisplayName (like '显示名称')
    /// </summary>
    public string PropertyPanel_General_DisplayName { get; }
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_SpeedRatio (like '倍速')
    /// </summary>
    public string PropertyPanel_General_SpeedRatio { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender (like '取消渲染')
    /// </summary>
    public string RenderPage_CancelRender { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender_Warn (like '你确定药取消渲染吗?')
    /// </summary>
    public string RenderPage_CancelRender_Warn { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_CustomOption (like '自定义')
    /// </summary>
    public string RenderPage_CustomOption { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_Done (like '渲染完成！')
    /// </summary>
    public string RenderPage_Done { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_ExportTitle (like '导出项目「{name}」')
    /// </summary>
    public string RenderPage_ExportTitle(string name);
    
    /// <summary>
    /// Get the localized string for RenderPage_LoggingLabel (like '输出日志')
    /// </summary>
    public string RenderPage_LoggingLabel { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_MaxParallelThreadsCount (like '并发数: {num}')
    /// </summary>
    public string RenderPage_MaxParallelThreadsCount(int num);
    
    /// <summary>
    /// Get the localized string for RenderPage_NoDraft (like '你需要先打开一个草稿才能进行渲染')
    /// </summary>
    public string RenderPage_NoDraft { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_PreviewLabel (like '预览')
    /// </summary>
    public string RenderPage_PreviewLabel { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_RenderMoreOptions (like '更多选项')
    /// </summary>
    public string RenderPage_RenderMoreOptions { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectEncoding (like '选择编码')
    /// </summary>
    public string RenderPage_SelectEncoding { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectFrameRate (like '选择帧率')
    /// </summary>
    public string RenderPage_SelectFrameRate { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectResolution (like '选择一个分辨率')
    /// </summary>
    public string RenderPage_SelectResolution { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_StartRender (like '开始渲染')
    /// </summary>
    public string RenderPage_StartRender { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_FinalEncoding (like '编码媒体')
    /// </summary>
    public string RenderPage_SubProg_FinalEncoding { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Init (like '初始化')
    /// </summary>
    public string RenderPage_SubProg_Init { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_None (like '子过程进度')
    /// </summary>
    public string RenderPage_SubProg_None { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_PrepareDraft (like '准备项目')
    /// </summary>
    public string RenderPage_SubProg_PrepareDraft { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Render (like '渲染')
    /// </summary>
    public string RenderPage_SubProg_Render { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_WriteVideo (like '写视频')
    /// </summary>
    public string RenderPage_SubProg_WriteVideo { get; }
    
    /// <summary>
    /// Get the localized string for RenderPage_TotalProg (like '总进度')
    /// </summary>
    public string RenderPage_TotalProg { get; }
    
    /// <summary>
    /// Get the localized string for WelcomeMessage (like '欢迎来到projectFrameCut beta!')
    /// </summary>
    /// <remarks>
    /// 不要翻译“projectFrameCut ”，这是软件的名字
    /// </remarks>
    public string WelcomeMessage { get; }
    
    /// <summary>
    /// Get the current Locale's ID (like 'zh-CN')
    /// </summary>
    public string _LocaleId_ { get; }
    
    public static Dictionary<string, ISimpleLocalizerBase> GetMapping()
    {
        return new Dictionary<string, ISimpleLocalizerBase>()
        {
            { "zh-CN", new  __SimpleLocalizer_zh_CN__() },
            { "en-US", new  __SimpleLocalizer_en_US__() },
            { "zh-TW", new  __SimpleLocalizer_zh_TW__() },
        };
    }
    /// <summary>
/// Dynamically lookup the localized string by the given id.
/// </summary>
/// <param name="id">The key of the localized item you want.</param>
/// <returns>The localized string you want.</returns>
/// <exception cref="KeyNotFoundException">The localized string you want with no argument isn't found.</exception>
    public string DynamicLookup(string id)
    {
        return id switch
        {
            "_Cancel" => _Cancel,
            "_Info" => _Info,
            "_LocateDisplayName" => _LocateDisplayName,
            "_OK" => _OK,
            "_Options" => _Options,
            "_Processing" => _Processing,
            "_Warn" => _Warn,
            "AppBrand" => AppBrand,
            "DraftPage_ApplyingChanges" => DraftPage_ApplyingChanges,
            "DraftPage_CannotMoveBecauseOfOverlap" => DraftPage_CannotMoveBecauseOfOverlap,
            "DraftPage_ChangesApplied" => DraftPage_ChangesApplied,
            "DraftPage_DuplicatedAsset_Relpace" => DraftPage_DuplicatedAsset_Relpace,
            "DraftPage_DuplicatedAsset_Skip" => DraftPage_DuplicatedAsset_Skip,
            "DraftPage_DuplicatedAsset_Together" => DraftPage_DuplicatedAsset_Together,
            "DraftPage_EverythingFine" => DraftPage_EverythingFine,
            "DraftPage_GoRender" => DraftPage_GoRender,
            "DraftPage_ImportAssetNotFinished" => DraftPage_ImportAssetNotFinished,
            "DraftPage_NoJobRunning" => DraftPage_NoJobRunning,
            "DraftPage_PrepareAsset" => DraftPage_PrepareAsset,
            "DraftPage_Processing" => DraftPage_Processing,
            "DraftPage_ReleaseToCancel" => DraftPage_ReleaseToCancel,
            "DraftPage_ReleaseToRemove" => DraftPage_ReleaseToRemove,
            "DraftPage_Removed" => DraftPage_Removed,
            "DraftPage_RenderDone" => DraftPage_RenderDone,
            "DraftPage_RenderTimeout" => DraftPage_RenderTimeout,
            "DraftPage_WaitForUser" => DraftPage_WaitForUser,
            "iDevicesAPI_MemoryNotEnough" => iDevicesAPI_MemoryNotEnough,
            "iDevicesAPI_TooHot" => iDevicesAPI_TooHot,
            "LandingPage_BackToContent" => LandingPage_BackToContent,
            "LandingPage_Loading" => LandingPage_Loading,
            "PropertyPanel" => PropertyPanel,
            "PropertyPanel_General" => PropertyPanel_General,
            "PropertyPanel_General_DisplayName" => PropertyPanel_General_DisplayName,
            "PropertyPanel_General_SpeedRatio" => PropertyPanel_General_SpeedRatio,
            "RenderPage_CancelRender" => RenderPage_CancelRender,
            "RenderPage_CancelRender_Warn" => RenderPage_CancelRender_Warn,
            "RenderPage_CustomOption" => RenderPage_CustomOption,
            "RenderPage_Done" => RenderPage_Done,
            "RenderPage_LoggingLabel" => RenderPage_LoggingLabel,
            "RenderPage_NoDraft" => RenderPage_NoDraft,
            "RenderPage_PreviewLabel" => RenderPage_PreviewLabel,
            "RenderPage_RenderMoreOptions" => RenderPage_RenderMoreOptions,
            "RenderPage_SelectEncoding" => RenderPage_SelectEncoding,
            "RenderPage_SelectFrameRate" => RenderPage_SelectFrameRate,
            "RenderPage_SelectResolution" => RenderPage_SelectResolution,
            "RenderPage_StartRender" => RenderPage_StartRender,
            "RenderPage_SubProg_FinalEncoding" => RenderPage_SubProg_FinalEncoding,
            "RenderPage_SubProg_Init" => RenderPage_SubProg_Init,
            "RenderPage_SubProg_None" => RenderPage_SubProg_None,
            "RenderPage_SubProg_PrepareDraft" => RenderPage_SubProg_PrepareDraft,
            "RenderPage_SubProg_Render" => RenderPage_SubProg_Render,
            "RenderPage_SubProg_WriteVideo" => RenderPage_SubProg_WriteVideo,
            "RenderPage_TotalProg" => RenderPage_TotalProg,
            "WelcomeMessage" => WelcomeMessage,
            _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}'")
            };
        }
        /// <summary>
/// Dynamically lookup the localized string by the given id with some arguments.
/// </summary>
/// <param name="id">The key of the localized item you want.</param>
/// <param name="args">The arguments to format the localized string.</param>
/// <returns>The localized string with arguments applied.</returns>
/// <exception cref="KeyNotFoundException">The localized string you want with arguments isn't found.</exception>
/// <exception cref="IndexOutOfRangeException">The number of arguments provided does not match the expected number for the localized string.</exception>
        public string DynamicLookupWithArgs(string id, params object[] args)
        {
            return id switch
            {
                "_ExceptionTemplate" => _ExceptionTemplate((Exception)args[0]),
                "DraftPage_AddOneAsset" => DraftPage_AddOneAsset((string?)args[0]),
                "DraftPage_AssetAdded" => DraftPage_AssetAdded((string)args[0]),
                "DraftPage_BackendStatus" => DraftPage_BackendStatus((double)args[0], (double)args[1], (double)args[2]),
                "DraftPage_BackendStatus_MemoryOnly" => DraftPage_BackendStatus_MemoryOnly((double)args[0]),
                "DraftPage_BackendStatus_NotRespond" => DraftPage_BackendStatus_NotRespond((double)args[0], (double)args[1]),
                "DraftPage_DuplicatedAsset" => DraftPage_DuplicatedAsset((string)args[0], (string)args[1]),
                "DraftPage_JobRunning" => DraftPage_JobRunning((int)args[0]),
                "DraftPage_ReachLimit" => DraftPage_ReachLimit((string)args[0]),
                "DraftPage_RenderOneFrame" => DraftPage_RenderOneFrame((int)args[0], (TimeSpan)args[1]),
                "DraftPage_Selected" => DraftPage_Selected((string)args[0]),
                "DraftPage_Track" => DraftPage_Track((int)args[0]),
                "LandingPage_TakingToDraft" => LandingPage_TakingToDraft((string)args[0]),
                "RenderPage_ExportTitle" => RenderPage_ExportTitle((string)args[0]),
                "RenderPage_MaxParallelThreadsCount" => RenderPage_MaxParallelThreadsCount((int)args[0]),
                _ => throw new KeyNotFoundException($"Can't find the localized string for id '{id}' with any argument")
            };
        }
    }
    
[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __SimpleLocalizer_zh_CN__ : ISimpleLocalizerBase
{
    /// <summary>
    /// Get the localized string for _Cancel in zh-CN
    /// </summary>
    string ISimpleLocalizerBase._Cancel => _Cancel;
    public readonly string _Cancel = @"取消";
    
    /// <summary>
    /// Get the localized string for _ExceptionTemplate in zh-CN
    /// </summary>
    string ISimpleLocalizerBase._ExceptionTemplate(Exception ex) => _ExceptionTemplate(ex);
    public string _ExceptionTemplate(Exception ex) => @$"一个未被处理的 {ex.GetType().Name} 异常发生 ({ex.Message})";
    
    /// <summary>
    /// Get the localized string for _Info in zh-CN
    /// </summary>
    string ISimpleLocalizerBase._Info => _Info;
    public readonly string _Info = @"提示";
    
    /// <summary>
    /// Get the localized string for _LocateDisplayName in zh-CN
    /// </summary>
    /// <remarks>
    /// 翻译时，请按照下列格式输出结果：
    /// 目标语言在目标语言的名字 / 目标语言在英语（英国）的名字，
    /// 比如当TargetLanguage是&quot;ja-JP&quot;时输出 “日本語 / Japanese”
    /// </remarks>
    string ISimpleLocalizerBase._LocateDisplayName => _LocateDisplayName;
    public readonly string _LocateDisplayName = @"简体中文 / Simplified Chinese";
    
    /// <summary>
    /// Get the localized string for _OK in zh-CN
    /// </summary>
    string ISimpleLocalizerBase._OK => _OK;
    public readonly string _OK = @"好的";
    
    /// <summary>
    /// Get the localized string for _Options in zh-CN
    /// </summary>
    string ISimpleLocalizerBase._Options => _Options;
    public readonly string _Options = @"选项";
    
    /// <summary>
    /// Get the localized string for _Processing in zh-CN
    /// </summary>
    string ISimpleLocalizerBase._Processing => _Processing;
    public readonly string _Processing = @"处理中...";
    
    /// <summary>
    /// Get the localized string for _Warn in zh-CN
    /// </summary>
    string ISimpleLocalizerBase._Warn => _Warn;
    public readonly string _Warn = @"警告";
    
    /// <summary>
    /// Get the localized string for AppBrand in zh-CN
    /// </summary>
    /// <remarks>
    /// 不要翻译，这是软件的名字
    /// </remarks>
    string ISimpleLocalizerBase.AppBrand => AppBrand;
    public readonly string AppBrand = @"projectFrameCut(仮)";
    
    /// <summary>
    /// Get the localized string for DraftPage_AddOneAsset in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_AddOneAsset(string? name) => DraftPage_AddOneAsset(name);
    public string DraftPage_AddOneAsset(string? name) => 
$""""
松手来添加「{name ?? "未知名称"}」 
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_ApplyingChanges in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ApplyingChanges => DraftPage_ApplyingChanges;
    public readonly string DraftPage_ApplyingChanges = @"正在应用更改...";
    
    /// <summary>
    /// Get the localized string for DraftPage_AssetAdded in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_AssetAdded(string name) => DraftPage_AssetAdded(name);
    public string DraftPage_AssetAdded(string name) => @$"成功添加素材「{name}」";
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_BackendStatus(double lantency, double menUsed, double menTotalUsed) => DraftPage_BackendStatus(lantency,menUsed,menTotalUsed);
    public string DraftPage_BackendStatus(double lantency, double menUsed, double menTotalUsed) => 
$""""
后端延迟{lantency.ToString("n2")}ms, 内存占用{menUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (后端/此电脑)
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_MemoryOnly in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_BackendStatus_MemoryOnly(double menUsed) => DraftPage_BackendStatus_MemoryOnly(menUsed);
    public string DraftPage_BackendStatus_MemoryOnly(double menUsed) => @$"程序已使用内存: {menUsed}";
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_NotRespond in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_BackendStatus_NotRespond(double menUsed, double menTotalUsed) => DraftPage_BackendStatus_NotRespond(menUsed,menTotalUsed);
    public string DraftPage_BackendStatus_NotRespond(double menUsed, double menTotalUsed) => 
$""""
后端未响应， 内存占用{menTotalUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (后端/此电脑)
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_CannotMoveBecauseOfOverlap in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_CannotMoveBecauseOfOverlap => DraftPage_CannotMoveBecauseOfOverlap;
    public readonly string DraftPage_CannotMoveBecauseOfOverlap = @"操作未被应用，因为此操作会导致重叠";
    
    /// <summary>
    /// Get the localized string for DraftPage_ChangesApplied in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ChangesApplied => DraftPage_ChangesApplied;
    public readonly string DraftPage_ChangesApplied = @"更改已被应用";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset(string newAsset, string existed) => DraftPage_DuplicatedAsset(newAsset,existed);
    public string DraftPage_DuplicatedAsset(string newAsset, string existed) => @$"素材{newAsset}似乎和{existed}重复了{Environment.NewLine}你想要做什么？";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Relpace in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Relpace => DraftPage_DuplicatedAsset_Relpace;
    public readonly string DraftPage_DuplicatedAsset_Relpace = @"使用新的替换旧的";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Skip in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Skip => DraftPage_DuplicatedAsset_Skip;
    public readonly string DraftPage_DuplicatedAsset_Skip = @"保留旧的";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Together in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Together => DraftPage_DuplicatedAsset_Together;
    public readonly string DraftPage_DuplicatedAsset_Together = @"同时保留";
    
    /// <summary>
    /// Get the localized string for DraftPage_EverythingFine in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_EverythingFine => DraftPage_EverythingFine;
    public readonly string DraftPage_EverythingFine = @"就绪";
    
    /// <summary>
    /// Get the localized string for DraftPage_GoRender in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_GoRender => DraftPage_GoRender;
    public readonly string DraftPage_GoRender = @"去渲染";
    
    /// <summary>
    /// Get the localized string for DraftPage_ImportAssetNotFinished in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ImportAssetNotFinished => DraftPage_ImportAssetNotFinished;
    public readonly string DraftPage_ImportAssetNotFinished = @"松手来导入素材...";
    
    /// <summary>
    /// Get the localized string for DraftPage_JobRunning in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_JobRunning(int count) => DraftPage_JobRunning(count);
    public string DraftPage_JobRunning(int count) => @$"{count} 任务正在执行";
    
    /// <summary>
    /// Get the localized string for DraftPage_NoJobRunning in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_NoJobRunning => DraftPage_NoJobRunning;
    public readonly string DraftPage_NoJobRunning = @"没有正在执行的任务";
    
    /// <summary>
    /// Get the localized string for DraftPage_PrepareAsset in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_PrepareAsset => DraftPage_PrepareAsset;
    public readonly string DraftPage_PrepareAsset = @"准备素材...";
    
    /// <summary>
    /// Get the localized string for DraftPage_Processing in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Processing => DraftPage_Processing;
    public readonly string DraftPage_Processing = @"处理中...";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReachLimit in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ReachLimit(string length) => DraftPage_ReachLimit(length);
    public string DraftPage_ReachLimit(string length) => @$"达到片段的长度限制({length})";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToCancel in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ReleaseToCancel => DraftPage_ReleaseToCancel;
    public readonly string DraftPage_ReleaseToCancel = @"松手来取消操作...";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToRemove in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ReleaseToRemove => DraftPage_ReleaseToRemove;
    public readonly string DraftPage_ReleaseToRemove = @"松手来移除此片段...";
    
    /// <summary>
    /// Get the localized string for DraftPage_Removed in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Removed => DraftPage_Removed;
    public readonly string DraftPage_Removed = @"已移除";
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderDone in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderDone => DraftPage_RenderDone;
    public readonly string DraftPage_RenderDone = @"渲染已完成";
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderOneFrame in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderOneFrame(int frameIndex, TimeSpan playheadSeconds) => DraftPage_RenderOneFrame(frameIndex,playheadSeconds);
    public string DraftPage_RenderOneFrame(int frameIndex, TimeSpan playheadSeconds) => 
$""""
渲染第{frameIndex}帧 ({playheadSeconds.ToString("mm\\:ss\\.ff")})...
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_RenderTimeout in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderTimeout => DraftPage_RenderTimeout;
    public readonly string DraftPage_RenderTimeout = @"错误：渲染超时";
    
    /// <summary>
    /// Get the localized string for DraftPage_Selected in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Selected(string clipName) => DraftPage_Selected(clipName);
    public string DraftPage_Selected(string clipName) => @$"已选中「{clipName}」";
    
    /// <summary>
    /// Get the localized string for DraftPage_Track in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Track(int trackId) => DraftPage_Track(trackId);
    public string DraftPage_Track(int trackId) => @$"轨道 #{trackId}";
    
    /// <summary>
    /// Get the localized string for DraftPage_WaitForUser in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_WaitForUser => DraftPage_WaitForUser;
    public readonly string DraftPage_WaitForUser = @"等待操作完成...";
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_MemoryNotEnough in zh-CN
    /// </summary>
    /// <remarks>
    /// 内存指运行内存
    /// </remarks>
    string ISimpleLocalizerBase.iDevicesAPI_MemoryNotEnough => iDevicesAPI_MemoryNotEnough;
    public readonly string iDevicesAPI_MemoryNotEnough = @"你的设备内存不足，程序可能会遇到一些问题。请尽快保存所有的数据以避免闪退造成的数据丢失。";
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_TooHot in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.iDevicesAPI_TooHot => iDevicesAPI_TooHot;
    public readonly string iDevicesAPI_TooHot = @"你的设备过热。请尽快保存所有的数据，并且在设备冷却之后继续使用，以避免对硬件造成损害或者数据丢失。";
    
    /// <summary>
    /// Get the localized string for LandingPage_BackToContent in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_BackToContent => LandingPage_BackToContent;
    public readonly string LandingPage_BackToContent = @"点击这里回到主界面";
    
    /// <summary>
    /// Get the localized string for LandingPage_Loading in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_Loading => LandingPage_Loading;
    public readonly string LandingPage_Loading = @"加载中...";
    
    /// <summary>
    /// Get the localized string for LandingPage_TakingToDraft in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_TakingToDraft(string name) => LandingPage_TakingToDraft(name);
    public string LandingPage_TakingToDraft(string name) => @$"请稍后，正在打开草稿 「{name}」";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel => PropertyPanel;
    public readonly string PropertyPanel = @"属性面板";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General => PropertyPanel_General;
    public readonly string PropertyPanel_General = @"通用";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_DisplayName in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General_DisplayName => PropertyPanel_General_DisplayName;
    public readonly string PropertyPanel_General_DisplayName = @"显示名称";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_SpeedRatio in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General_SpeedRatio => PropertyPanel_General_SpeedRatio;
    public readonly string PropertyPanel_General_SpeedRatio = @"倍速";
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_CancelRender => RenderPage_CancelRender;
    public readonly string RenderPage_CancelRender = @"取消渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender_Warn in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_CancelRender_Warn => RenderPage_CancelRender_Warn;
    public readonly string RenderPage_CancelRender_Warn = @"你确定药取消渲染吗?";
    
    /// <summary>
    /// Get the localized string for RenderPage_CustomOption in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_CustomOption => RenderPage_CustomOption;
    public readonly string RenderPage_CustomOption = @"自定义";
    
    /// <summary>
    /// Get the localized string for RenderPage_Done in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_Done => RenderPage_Done;
    public readonly string RenderPage_Done = @"渲染完成！";
    
    /// <summary>
    /// Get the localized string for RenderPage_ExportTitle in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_ExportTitle(string name) => RenderPage_ExportTitle(name);
    public string RenderPage_ExportTitle(string name) => @$"导出项目「{name}」";
    
    /// <summary>
    /// Get the localized string for RenderPage_LoggingLabel in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_LoggingLabel => RenderPage_LoggingLabel;
    public readonly string RenderPage_LoggingLabel = @"输出日志";
    
    /// <summary>
    /// Get the localized string for RenderPage_MaxParallelThreadsCount in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_MaxParallelThreadsCount(int num) => RenderPage_MaxParallelThreadsCount(num);
    public string RenderPage_MaxParallelThreadsCount(int num) => @$"并发数: {num}";
    
    /// <summary>
    /// Get the localized string for RenderPage_NoDraft in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_NoDraft => RenderPage_NoDraft;
    public readonly string RenderPage_NoDraft = @"你需要先打开一个草稿才能进行渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_PreviewLabel in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_PreviewLabel => RenderPage_PreviewLabel;
    public readonly string RenderPage_PreviewLabel = @"预览";
    
    /// <summary>
    /// Get the localized string for RenderPage_RenderMoreOptions in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_RenderMoreOptions => RenderPage_RenderMoreOptions;
    public readonly string RenderPage_RenderMoreOptions = @"更多选项";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectEncoding in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectEncoding => RenderPage_SelectEncoding;
    public readonly string RenderPage_SelectEncoding = @"选择编码";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectFrameRate in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectFrameRate => RenderPage_SelectFrameRate;
    public readonly string RenderPage_SelectFrameRate = @"选择帧率";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectResolution in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectResolution => RenderPage_SelectResolution;
    public readonly string RenderPage_SelectResolution = @"选择一个分辨率";
    
    /// <summary>
    /// Get the localized string for RenderPage_StartRender in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_StartRender => RenderPage_StartRender;
    public readonly string RenderPage_StartRender = @"开始渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_FinalEncoding in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_FinalEncoding => RenderPage_SubProg_FinalEncoding;
    public readonly string RenderPage_SubProg_FinalEncoding = @"编码媒体";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Init in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_Init => RenderPage_SubProg_Init;
    public readonly string RenderPage_SubProg_Init = @"初始化";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_None in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_None => RenderPage_SubProg_None;
    public readonly string RenderPage_SubProg_None = @"子过程进度";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_PrepareDraft in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_PrepareDraft => RenderPage_SubProg_PrepareDraft;
    public readonly string RenderPage_SubProg_PrepareDraft = @"准备项目";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Render in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_Render => RenderPage_SubProg_Render;
    public readonly string RenderPage_SubProg_Render = @"渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_WriteVideo in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_WriteVideo => RenderPage_SubProg_WriteVideo;
    public readonly string RenderPage_SubProg_WriteVideo = @"写视频";
    
    /// <summary>
    /// Get the localized string for RenderPage_TotalProg in zh-CN
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_TotalProg => RenderPage_TotalProg;
    public readonly string RenderPage_TotalProg = @"总进度";
    
    /// <summary>
    /// Get the localized string for WelcomeMessage in zh-CN
    /// </summary>
    /// <remarks>
    /// 不要翻译“projectFrameCut ”，这是软件的名字
    /// </remarks>
    string ISimpleLocalizerBase.WelcomeMessage => WelcomeMessage;
    public readonly string WelcomeMessage = @"欢迎来到projectFrameCut beta!";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-CN";
    
    
}

[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __SimpleLocalizer_en_US__ : ISimpleLocalizerBase
{
    /// <summary>
    /// Get the localized string for _Cancel in en-US
    /// </summary>
    string ISimpleLocalizerBase._Cancel => _Cancel;
    public readonly string _Cancel = @"Cancel";
    
    /// <summary>
    /// Get the localized string for _ExceptionTemplate in en-US
    /// </summary>
    /// <remarks>
    /// Exception message template
    /// </remarks>
    string ISimpleLocalizerBase._ExceptionTemplate(Exception ex) => _ExceptionTemplate(ex);
    public string _ExceptionTemplate(Exception ex) => @$"An unhandled {ex.GetType().Name} exception occurred ({ex.Message})";
    
    /// <summary>
    /// Get the localized string for _Info in en-US
    /// </summary>
    string ISimpleLocalizerBase._Info => _Info;
    public readonly string _Info = @"Information";
    
    /// <summary>
    /// Get the localized string for _OK in en-US
    /// </summary>
    /// <remarks>
    /// Confirmation or agreement response
    /// </remarks>
    string ISimpleLocalizerBase._OK => _OK;
    public readonly string _OK = @"OK";
    
    /// <summary>
    /// Get the localized string for _Options in en-US
    /// </summary>
    string ISimpleLocalizerBase._Options => _Options;
    public readonly string _Options = @"Options";
    
    /// <summary>
    /// Get the localized string for _Processing in en-US
    /// </summary>
    string ISimpleLocalizerBase._Processing => _Processing;
    public readonly string _Processing = @"Processing...";
    
    /// <summary>
    /// Get the localized string for _Warn in en-US
    /// </summary>
    string ISimpleLocalizerBase._Warn => _Warn;
    public readonly string _Warn = @"Warning";
    
    /// <summary>
    /// Get the localized string for AppBrand in en-US
    /// </summary>
    /// <remarks>
    /// Not translated as per @DontTranslate directive
    /// </remarks>
    string ISimpleLocalizerBase.AppBrand => AppBrand;
    public readonly string AppBrand = @"projectFrameCut(仮)";
    
    /// <summary>
    /// Get the localized string for DraftPage_AddOneAsset in en-US
    /// </summary>
    /// <remarks>
    /// Prompt shown when user releases drag to add an asset
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_AddOneAsset(string? name) => DraftPage_AddOneAsset(name);
    public string DraftPage_AddOneAsset(string? name) => 
$""""
Release to add "{name ?? "Unknown Name"}"
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_ApplyingChanges in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ApplyingChanges => DraftPage_ApplyingChanges;
    public readonly string DraftPage_ApplyingChanges = @"Applying changes...";
    
    /// <summary>
    /// Get the localized string for DraftPage_AssetAdded in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_AssetAdded(string name) => DraftPage_AssetAdded(name);
    public string DraftPage_AssetAdded(string name) => @$"Successfully added asset '{name}'";
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus in en-US
    /// </summary>
    /// <remarks>
    /// Backend status information showing latency and memory usage
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_BackendStatus(double lantency, double menUsed, double menTotalUsed) => DraftPage_BackendStatus(lantency,menUsed,menTotalUsed);
    public string DraftPage_BackendStatus(double lantency, double menUsed, double menTotalUsed) => 
$""""
Backend latency {lantency.ToString("n2")}ms, Memory usage {menUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (Backend/This PC)
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_MemoryOnly in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_BackendStatus_MemoryOnly(double menUsed) => DraftPage_BackendStatus_MemoryOnly(menUsed);
    public string DraftPage_BackendStatus_MemoryOnly(double menUsed) => @$"Program has used memory: {menUsed}";
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_NotRespond in en-US
    /// </summary>
    /// <remarks>
    /// Display backend status with memory usage information
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_BackendStatus_NotRespond(double menUsed, double menTotalUsed) => DraftPage_BackendStatus_NotRespond(menUsed,menTotalUsed);
    public string DraftPage_BackendStatus_NotRespond(double menUsed, double menTotalUsed) => 
$""""
Backend not responding, memory usage {menUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (Backend/This PC)
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_CannotMoveBecauseOfOverlap in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_CannotMoveBecauseOfOverlap => DraftPage_CannotMoveBecauseOfOverlap;
    public readonly string DraftPage_CannotMoveBecauseOfOverlap = @"Operation was not applied because it would cause overlap";
    
    /// <summary>
    /// Get the localized string for DraftPage_ChangesApplied in en-US
    /// </summary>
    /// <remarks>
    /// Shorter and more natural for UI display
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_ChangesApplied => DraftPage_ChangesApplied;
    public readonly string DraftPage_ChangesApplied = @"Changes applied";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset(string newAsset, string existed) => DraftPage_DuplicatedAsset(newAsset,existed);
    public string DraftPage_DuplicatedAsset(string newAsset, string existed) => @$"Asset {newAsset} appears to be a duplicate of {existed}.{Environment.NewLine}What would you like to do?";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Relpace in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Relpace => DraftPage_DuplicatedAsset_Relpace;
    public readonly string DraftPage_DuplicatedAsset_Relpace = @"Replace old with new";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Skip in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Skip => DraftPage_DuplicatedAsset_Skip;
    public readonly string DraftPage_DuplicatedAsset_Skip = @"Keep old";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Together in en-US
    /// </summary>
    /// <remarks>
    /// Option to retain both items when dealing with duplicated assets
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Together => DraftPage_DuplicatedAsset_Together;
    public readonly string DraftPage_DuplicatedAsset_Together = @"Keep Both";
    
    /// <summary>
    /// Get the localized string for DraftPage_EverythingFine in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_EverythingFine => DraftPage_EverythingFine;
    public readonly string DraftPage_EverythingFine = @"Ready";
    
    /// <summary>
    /// Get the localized string for DraftPage_GoRender in en-US
    /// </summary>
    /// <remarks>
    /// Navigation command to access rendering functionality
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_GoRender => DraftPage_GoRender;
    public readonly string DraftPage_GoRender = @"Go to Render";
    
    /// <summary>
    /// Get the localized string for DraftPage_ImportAssetNotFinished in en-US
    /// </summary>
    /// <remarks>
    /// Prompt text indicating that releasing the mouse/finger will trigger asset import
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_ImportAssetNotFinished => DraftPage_ImportAssetNotFinished;
    public readonly string DraftPage_ImportAssetNotFinished = @"Release to import asset...";
    
    /// <summary>
    /// Get the localized string for DraftPage_JobRunning in en-US
    /// </summary>
    /// <remarks>
    /// Indicates the number of background jobs currently in progress
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_JobRunning(int count) => DraftPage_JobRunning(count);
    public string DraftPage_JobRunning(int count) => @$"{count} jobs running";
    
    /// <summary>
    /// Get the localized string for DraftPage_NoJobRunning in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_NoJobRunning => DraftPage_NoJobRunning;
    public readonly string DraftPage_NoJobRunning = @"No running tasks";
    
    /// <summary>
    /// Get the localized string for DraftPage_PrepareAsset in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_PrepareAsset => DraftPage_PrepareAsset;
    public readonly string DraftPage_PrepareAsset = @"Preparing assets...";
    
    /// <summary>
    /// Get the localized string for DraftPage_Processing in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Processing => DraftPage_Processing;
    public readonly string DraftPage_Processing = @"Processing...";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReachLimit in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ReachLimit(string length) => DraftPage_ReachLimit(length);
    public string DraftPage_ReachLimit(string length) => @$"Reached the fragment length limit ({length})";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToCancel in en-US
    /// </summary>
    /// <remarks>
    /// Instruction prompt indicating that releasing the finger/mouse will cancel the current operation
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_ReleaseToCancel => DraftPage_ReleaseToCancel;
    public readonly string DraftPage_ReleaseToCancel = @"Release to cancel operation...";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToRemove in en-US
    /// </summary>
    /// <remarks>
    /// Operation hint in drag-and-drop interface
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_ReleaseToRemove => DraftPage_ReleaseToRemove;
    public readonly string DraftPage_ReleaseToRemove = @"Release to remove this segment...";
    
    /// <summary>
    /// Get the localized string for DraftPage_Removed in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Removed => DraftPage_Removed;
    public readonly string DraftPage_Removed = @"Removed";
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderDone in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderDone => DraftPage_RenderDone;
    public readonly string DraftPage_RenderDone = @"Rendering completed";
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderOneFrame in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderOneFrame(int frameIndex, TimeSpan playheadSeconds) => DraftPage_RenderOneFrame(frameIndex,playheadSeconds);
    public string DraftPage_RenderOneFrame(int frameIndex, TimeSpan playheadSeconds) => @$"Rendering frame {frameIndex} ({playheadSeconds:mm\\:ss\.ff})...";
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderTimeout in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderTimeout => DraftPage_RenderTimeout;
    public readonly string DraftPage_RenderTimeout = @"Error: Render timeout";
    
    /// <summary>
    /// Get the localized string for DraftPage_Selected in en-US
    /// </summary>
    /// <remarks>
    /// Indicates that a specific clip has been selected
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_Selected(string clipName) => DraftPage_Selected(clipName);
    public string DraftPage_Selected(string clipName) => 
$""""
"{clipName}" selected
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_Track in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Track(int trackId) => DraftPage_Track(trackId);
    public string DraftPage_Track(int trackId) => @$"Track #{trackId}";
    
    /// <summary>
    /// Get the localized string for DraftPage_WaitForUser in en-US
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_WaitForUser => DraftPage_WaitForUser;
    public readonly string DraftPage_WaitForUser = @"Waiting for operation to complete...";
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_MemoryNotEnough in en-US
    /// </summary>
    /// <remarks>
    /// Memory refers to running memory
    /// </remarks>
    string ISimpleLocalizerBase.iDevicesAPI_MemoryNotEnough => iDevicesAPI_MemoryNotEnough;
    public readonly string iDevicesAPI_MemoryNotEnough = @"Your device has insufficient memory, which may cause the program to encounter issues. Please save all data as soon as possible to avoid data loss due to flash crashes.";
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_TooHot in en-US
    /// </summary>
    string ISimpleLocalizerBase.iDevicesAPI_TooHot => iDevicesAPI_TooHot;
    public readonly string iDevicesAPI_TooHot = @"Your device is overheating. Please save all data immediately and resume use after it cools down to prevent hardware damage or data loss.";
    
    /// <summary>
    /// Get the localized string for LandingPage_BackToContent in en-US
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_BackToContent => LandingPage_BackToContent;
    public readonly string LandingPage_BackToContent = @"Click here to return to the main interface";
    
    /// <summary>
    /// Get the localized string for LandingPage_Loading in en-US
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_Loading => LandingPage_Loading;
    public readonly string LandingPage_Loading = @"Loading...";
    
    /// <summary>
    /// Get the localized string for LandingPage_TakingToDraft in en-US
    /// </summary>
    /// <remarks>
    /// Notification message indicating that a draft file is being opened
    /// </remarks>
    string ISimpleLocalizerBase.LandingPage_TakingToDraft(string name) => LandingPage_TakingToDraft(name);
    public string LandingPage_TakingToDraft(string name) => 
$""""
Please wait, opening draft "{name}"
"""";

    
    /// <summary>
    /// Get the localized string for PropertyPanel in en-US
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel => PropertyPanel;
    public readonly string PropertyPanel = @"Property Panel";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General in en-US
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General => PropertyPanel_General;
    public readonly string PropertyPanel_General = @"General";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_DisplayName in en-US
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General_DisplayName => PropertyPanel_General_DisplayName;
    public readonly string PropertyPanel_General_DisplayName = @"Display Name";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_SpeedRatio in en-US
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General_SpeedRatio => PropertyPanel_General_SpeedRatio;
    public readonly string PropertyPanel_General_SpeedRatio = @"Speed";
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_CancelRender => RenderPage_CancelRender;
    public readonly string RenderPage_CancelRender = @"Cancel Rendering";
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender_Warn in en-US
    /// </summary>
    /// <remarks>
    /// Warning message when user attempts to cancel rendering process
    /// </remarks>
    string ISimpleLocalizerBase.RenderPage_CancelRender_Warn => RenderPage_CancelRender_Warn;
    public readonly string RenderPage_CancelRender_Warn = @"Are you sure you want to cancel rendering?";
    
    /// <summary>
    /// Get the localized string for RenderPage_CustomOption in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_CustomOption => RenderPage_CustomOption;
    public readonly string RenderPage_CustomOption = @"Custom";
    
    /// <summary>
    /// Get the localized string for RenderPage_Done in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_Done => RenderPage_Done;
    public readonly string RenderPage_Done = @"Rendering completed!";
    
    /// <summary>
    /// Get the localized string for RenderPage_ExportTitle in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_ExportTitle(string name) => RenderPage_ExportTitle(name);
    public string RenderPage_ExportTitle(string name) => @$"Export Project {name}";
    
    /// <summary>
    /// Get the localized string for RenderPage_LoggingLabel in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_LoggingLabel => RenderPage_LoggingLabel;
    public readonly string RenderPage_LoggingLabel = @"Output Log";
    
    /// <summary>
    /// Get the localized string for RenderPage_MaxParallelThreadsCount in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_MaxParallelThreadsCount(int num) => RenderPage_MaxParallelThreadsCount(num);
    public string RenderPage_MaxParallelThreadsCount(int num) => @$"Parallel threads: {num}";
    
    /// <summary>
    /// Get the localized string for RenderPage_NoDraft in en-US
    /// </summary>
    /// <remarks>
    /// Instructional message about prerequisite for rendering operation
    /// </remarks>
    string ISimpleLocalizerBase.RenderPage_NoDraft => RenderPage_NoDraft;
    public readonly string RenderPage_NoDraft = @"You need to open a draft first to proceed with rendering";
    
    /// <summary>
    /// Get the localized string for RenderPage_PreviewLabel in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_PreviewLabel => RenderPage_PreviewLabel;
    public readonly string RenderPage_PreviewLabel = @"Preview";
    
    /// <summary>
    /// Get the localized string for RenderPage_RenderMoreOptions in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_RenderMoreOptions => RenderPage_RenderMoreOptions;
    public readonly string RenderPage_RenderMoreOptions = @"More options";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectEncoding in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectEncoding => RenderPage_SelectEncoding;
    public readonly string RenderPage_SelectEncoding = @"Select Encoding";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectFrameRate in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectFrameRate => RenderPage_SelectFrameRate;
    public readonly string RenderPage_SelectFrameRate = @"Select frame rate";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectResolution in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectResolution => RenderPage_SelectResolution;
    public readonly string RenderPage_SelectResolution = @"Select a resolution";
    
    /// <summary>
    /// Get the localized string for RenderPage_StartRender in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_StartRender => RenderPage_StartRender;
    public readonly string RenderPage_StartRender = @"Start rendering";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_FinalEncoding in en-US
    /// </summary>
    /// <remarks>
    /// Refers to the process of encoding media files in the final rendering stage
    /// </remarks>
    string ISimpleLocalizerBase.RenderPage_SubProg_FinalEncoding => RenderPage_SubProg_FinalEncoding;
    public readonly string RenderPage_SubProg_FinalEncoding = @"Encoding Media";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Init in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_Init => RenderPage_SubProg_Init;
    public readonly string RenderPage_SubProg_Init = @"Initializing";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_None in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_None => RenderPage_SubProg_None;
    public readonly string RenderPage_SubProg_None = @"Subprocess Progress";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_PrepareDraft in en-US
    /// </summary>
    /// <remarks>
    /// Indicates the action of preparing a project draft
    /// </remarks>
    string ISimpleLocalizerBase.RenderPage_SubProg_PrepareDraft => RenderPage_SubProg_PrepareDraft;
    public readonly string RenderPage_SubProg_PrepareDraft = @"Prepare Project";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Render in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_Render => RenderPage_SubProg_Render;
    public readonly string RenderPage_SubProg_Render = @"Render";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_WriteVideo in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_WriteVideo => RenderPage_SubProg_WriteVideo;
    public readonly string RenderPage_SubProg_WriteVideo = @"Write Video";
    
    /// <summary>
    /// Get the localized string for RenderPage_TotalProg in en-US
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_TotalProg => RenderPage_TotalProg;
    public readonly string RenderPage_TotalProg = @"Total Progress";
    
    /// <summary>
    /// Get the localized string for WelcomeMessage in en-US
    /// </summary>
    string ISimpleLocalizerBase.WelcomeMessage => WelcomeMessage;
    public readonly string WelcomeMessage = @"Welcome to projectFrameCut beta!";
    
    /// <summary>
    /// Get the localized string for _LocateDisplayName in en-US
    /// </summary>
    string ISimpleLocalizerBase._LocateDisplayName => _LocateDisplayName;
    public readonly string _LocateDisplayName = @"English (US)";
    
    /// <summary>
    /// Get the current localized Id (like 'e')
    /// </summary>
    string ISimpleLocalizerBase._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"en-US";
    
    
}

[GeneratedCodeAttribute("SimpleLocalizer", "1.0.0.0")]
[DebuggerNonUserCode()]
public class __SimpleLocalizer_zh_TW__ : ISimpleLocalizerBase
{
    /// <summary>
    /// Get the localized string for _Cancel in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._Cancel => _Cancel;
    public readonly string _Cancel = @"取消";
    
    /// <summary>
    /// Get the localized string for _ExceptionTemplate in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._ExceptionTemplate(Exception ex) => _ExceptionTemplate(ex);
    public string _ExceptionTemplate(Exception ex) => @$"一個未處理的 {ex.GetType().Name} 異常發生 ({ex.Message})";
    
    /// <summary>
    /// Get the localized string for _Info in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._Info => _Info;
    public readonly string _Info = @"提示";
    
    /// <summary>
    /// Get the localized string for _OK in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._OK => _OK;
    public readonly string _OK = @"好的";
    
    /// <summary>
    /// Get the localized string for _Options in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._Options => _Options;
    public readonly string _Options = @"選項";
    
    /// <summary>
    /// Get the localized string for _Processing in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._Processing => _Processing;
    public readonly string _Processing = @"處理中...";
    
    /// <summary>
    /// Get the localized string for _Warn in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._Warn => _Warn;
    public readonly string _Warn = @"警告";
    
    /// <summary>
    /// Get the localized string for AppBrand in zh-TW
    /// </summary>
    /// <remarks>
    /// Original technical term preserved as per DontTranslate instruction
    /// </remarks>
    string ISimpleLocalizerBase.AppBrand => AppBrand;
    public readonly string AppBrand = @"projectFrameCut(仮)";
    
    /// <summary>
    /// Get the localized string for DraftPage_AddOneAsset in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_AddOneAsset(string? name) => DraftPage_AddOneAsset(name);
    public string DraftPage_AddOneAsset(string? name) => 
$""""
放開以新增『{name ?? "未知名稱"}』
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_ApplyingChanges in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ApplyingChanges => DraftPage_ApplyingChanges;
    public readonly string DraftPage_ApplyingChanges = @"正在套用變更...";
    
    /// <summary>
    /// Get the localized string for DraftPage_AssetAdded in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_AssetAdded(string name) => DraftPage_AssetAdded(name);
    public string DraftPage_AssetAdded(string name) => @$"成功添加素材「{name}」";
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_BackendStatus(double lantency, double menUsed, double menTotalUsed) => DraftPage_BackendStatus(lantency,menUsed,menTotalUsed);
    public string DraftPage_BackendStatus(double lantency, double menUsed, double menTotalUsed) => 
$""""
後端延遲{lantency.ToString("n2")}ms, 記憶體佔用{menUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (後端/此電腦)
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_MemoryOnly in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_BackendStatus_MemoryOnly(double menUsed) => DraftPage_BackendStatus_MemoryOnly(menUsed);
    public string DraftPage_BackendStatus_MemoryOnly(double menUsed) => @$"程式已使用記憶體: {menUsed}";
    
    /// <summary>
    /// Get the localized string for DraftPage_BackendStatus_NotRespond in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_BackendStatus_NotRespond(double menUsed, double menTotalUsed) => DraftPage_BackendStatus_NotRespond(menUsed,menTotalUsed);
    public string DraftPage_BackendStatus_NotRespond(double menUsed, double menTotalUsed) => 
$""""
後端未響應，記憶體佔用{menUsed.ToString("n2").Replace(',', '\0')}/{menTotalUsed.ToString("n2").Replace(',', '\0')} MB (後端/此電腦)
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_CannotMoveBecauseOfOverlap in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_CannotMoveBecauseOfOverlap => DraftPage_CannotMoveBecauseOfOverlap;
    public readonly string DraftPage_CannotMoveBecauseOfOverlap = @"操作未執行，因為此操作會導致重疊";
    
    /// <summary>
    /// Get the localized string for DraftPage_ChangesApplied in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ChangesApplied => DraftPage_ChangesApplied;
    public readonly string DraftPage_ChangesApplied = @"變更已套用";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset(string newAsset, string existed) => DraftPage_DuplicatedAsset(newAsset,existed);
    public string DraftPage_DuplicatedAsset(string newAsset, string existed) => @$"素材{newAsset}似乎和{existed}重複了{Environment.NewLine}你想要做什麼？";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Relpace in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Relpace => DraftPage_DuplicatedAsset_Relpace;
    public readonly string DraftPage_DuplicatedAsset_Relpace = @"以新檔案取代舊檔案";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Skip in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Skip => DraftPage_DuplicatedAsset_Skip;
    public readonly string DraftPage_DuplicatedAsset_Skip = @"保留舊的";
    
    /// <summary>
    /// Get the localized string for DraftPage_DuplicatedAsset_Together in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_DuplicatedAsset_Together => DraftPage_DuplicatedAsset_Together;
    public readonly string DraftPage_DuplicatedAsset_Together = @"同時保留";
    
    /// <summary>
    /// Get the localized string for DraftPage_EverythingFine in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_EverythingFine => DraftPage_EverythingFine;
    public readonly string DraftPage_EverythingFine = @"就緒";
    
    /// <summary>
    /// Get the localized string for DraftPage_GoRender in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_GoRender => DraftPage_GoRender;
    public readonly string DraftPage_GoRender = @"去渲染";
    
    /// <summary>
    /// Get the localized string for DraftPage_ImportAssetNotFinished in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ImportAssetNotFinished => DraftPage_ImportAssetNotFinished;
    public readonly string DraftPage_ImportAssetNotFinished = @"鬆手來導入素材...";
    
    /// <summary>
    /// Get the localized string for DraftPage_JobRunning in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_JobRunning(int count) => DraftPage_JobRunning(count);
    public string DraftPage_JobRunning(int count) => @$"{count} 項任務執行中";
    
    /// <summary>
    /// Get the localized string for DraftPage_NoJobRunning in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_NoJobRunning => DraftPage_NoJobRunning;
    public readonly string DraftPage_NoJobRunning = @"沒有正在執行的工作";
    
    /// <summary>
    /// Get the localized string for DraftPage_PrepareAsset in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_PrepareAsset => DraftPage_PrepareAsset;
    public readonly string DraftPage_PrepareAsset = @"準備素材...";
    
    /// <summary>
    /// Get the localized string for DraftPage_Processing in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Processing => DraftPage_Processing;
    public readonly string DraftPage_Processing = @"處理中...";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReachLimit in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ReachLimit(string length) => DraftPage_ReachLimit(length);
    public string DraftPage_ReachLimit(string length) => @$"達到段落長度上限({length})";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToCancel in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_ReleaseToCancel => DraftPage_ReleaseToCancel;
    public readonly string DraftPage_ReleaseToCancel = @"鬆手來取消...";
    
    /// <summary>
    /// Get the localized string for DraftPage_ReleaseToRemove in zh-TW
    /// </summary>
    /// <remarks>
    /// 操作提示：用戶需要放開手指來完成刪除片段的操作
    /// </remarks>
    string ISimpleLocalizerBase.DraftPage_ReleaseToRemove => DraftPage_ReleaseToRemove;
    public readonly string DraftPage_ReleaseToRemove = @"放開以刪除此片段...";
    
    /// <summary>
    /// Get the localized string for DraftPage_Removed in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Removed => DraftPage_Removed;
    public readonly string DraftPage_Removed = @"已移除";
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderDone in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderDone => DraftPage_RenderDone;
    public readonly string DraftPage_RenderDone = @"渲染完成";
    
    /// <summary>
    /// Get the localized string for DraftPage_RenderOneFrame in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderOneFrame(int frameIndex, TimeSpan playheadSeconds) => DraftPage_RenderOneFrame(frameIndex,playheadSeconds);
    public string DraftPage_RenderOneFrame(int frameIndex, TimeSpan playheadSeconds) => 
$""""
渲染第{frameIndex}幀 ({playheadSeconds.ToString("mm\\:ss\\.ff")})...
"""";

    
    /// <summary>
    /// Get the localized string for DraftPage_RenderTimeout in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_RenderTimeout => DraftPage_RenderTimeout;
    public readonly string DraftPage_RenderTimeout = @"錯誤：渲染逾時";
    
    /// <summary>
    /// Get the localized string for DraftPage_Selected in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Selected(string clipName) => DraftPage_Selected(clipName);
    public string DraftPage_Selected(string clipName) => @$"已選取「{clipName}」";
    
    /// <summary>
    /// Get the localized string for DraftPage_Track in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_Track(int trackId) => DraftPage_Track(trackId);
    public string DraftPage_Track(int trackId) => @$"軌道 #{trackId}";
    
    /// <summary>
    /// Get the localized string for DraftPage_WaitForUser in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.DraftPage_WaitForUser => DraftPage_WaitForUser;
    public readonly string DraftPage_WaitForUser = @"等待作業完成...";
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_MemoryNotEnough in zh-TW
    /// </summary>
    /// <remarks>
    /// 記憶體指運行記憶體
    /// </remarks>
    string ISimpleLocalizerBase.iDevicesAPI_MemoryNotEnough => iDevicesAPI_MemoryNotEnough;
    public readonly string iDevicesAPI_MemoryNotEnough = @"你的設備記憶體不足，程式可能會遇到一些問題。請盡快儲存所有的資料以避免閃退造成的資料遺失。";
    
    /// <summary>
    /// Get the localized string for iDevicesAPI_TooHot in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.iDevicesAPI_TooHot => iDevicesAPI_TooHot;
    public readonly string iDevicesAPI_TooHot = @"你的裝置過熱。請盡快儲存所有的資料，並且在裝置冷卻之後繼續使用，以避免對硬體造成損害或者資料遺失。";
    
    /// <summary>
    /// Get the localized string for LandingPage_BackToContent in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_BackToContent => LandingPage_BackToContent;
    public readonly string LandingPage_BackToContent = @"點擊這裡回到主介面";
    
    /// <summary>
    /// Get the localized string for LandingPage_Loading in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_Loading => LandingPage_Loading;
    public readonly string LandingPage_Loading = @"載入中...";
    
    /// <summary>
    /// Get the localized string for LandingPage_TakingToDraft in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.LandingPage_TakingToDraft(string name) => LandingPage_TakingToDraft(name);
    public string LandingPage_TakingToDraft(string name) => @$"請稍候，正在開啟草稿「{name}」";
    
    /// <summary>
    /// Get the localized string for PropertyPanel in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel => PropertyPanel;
    public readonly string PropertyPanel = @"屬性面板";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General => PropertyPanel_General;
    public readonly string PropertyPanel_General = @"通用";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_DisplayName in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General_DisplayName => PropertyPanel_General_DisplayName;
    public readonly string PropertyPanel_General_DisplayName = @"顯示名稱";
    
    /// <summary>
    /// Get the localized string for PropertyPanel_General_SpeedRatio in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.PropertyPanel_General_SpeedRatio => PropertyPanel_General_SpeedRatio;
    public readonly string PropertyPanel_General_SpeedRatio = @"倍速";
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_CancelRender => RenderPage_CancelRender;
    public readonly string RenderPage_CancelRender = @"取消渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_CancelRender_Warn in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_CancelRender_Warn => RenderPage_CancelRender_Warn;
    public readonly string RenderPage_CancelRender_Warn = @"您確定要取消渲染嗎？";
    
    /// <summary>
    /// Get the localized string for RenderPage_CustomOption in zh-TW
    /// </summary>
    /// <remarks>
    /// Custom option translation for Traditional Chinese interface
    /// </remarks>
    string ISimpleLocalizerBase.RenderPage_CustomOption => RenderPage_CustomOption;
    public readonly string RenderPage_CustomOption = @"自訂";
    
    /// <summary>
    /// Get the localized string for RenderPage_Done in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_Done => RenderPage_Done;
    public readonly string RenderPage_Done = @"渲染完成！";
    
    /// <summary>
    /// Get the localized string for RenderPage_ExportTitle in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_ExportTitle(string name) => RenderPage_ExportTitle(name);
    public string RenderPage_ExportTitle(string name) => @$"匯出專案『{name}』";
    
    /// <summary>
    /// Get the localized string for RenderPage_LoggingLabel in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_LoggingLabel => RenderPage_LoggingLabel;
    public readonly string RenderPage_LoggingLabel = @"輸出日誌";
    
    /// <summary>
    /// Get the localized string for RenderPage_MaxParallelThreadsCount in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_MaxParallelThreadsCount(int num) => RenderPage_MaxParallelThreadsCount(num);
    public string RenderPage_MaxParallelThreadsCount(int num) => @$"並行數: {num}";
    
    /// <summary>
    /// Get the localized string for RenderPage_NoDraft in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_NoDraft => RenderPage_NoDraft;
    public readonly string RenderPage_NoDraft = @"你需要先開啟一個草稿才能進行渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_PreviewLabel in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_PreviewLabel => RenderPage_PreviewLabel;
    public readonly string RenderPage_PreviewLabel = @"預覽";
    
    /// <summary>
    /// Get the localized string for RenderPage_RenderMoreOptions in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_RenderMoreOptions => RenderPage_RenderMoreOptions;
    public readonly string RenderPage_RenderMoreOptions = @"更多選項";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectEncoding in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectEncoding => RenderPage_SelectEncoding;
    public readonly string RenderPage_SelectEncoding = @"選擇編碼";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectFrameRate in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectFrameRate => RenderPage_SelectFrameRate;
    public readonly string RenderPage_SelectFrameRate = @"選擇影格率";
    
    /// <summary>
    /// Get the localized string for RenderPage_SelectResolution in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SelectResolution => RenderPage_SelectResolution;
    public readonly string RenderPage_SelectResolution = @"選擇解析度";
    
    /// <summary>
    /// Get the localized string for RenderPage_StartRender in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_StartRender => RenderPage_StartRender;
    public readonly string RenderPage_StartRender = @"開始渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_FinalEncoding in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_FinalEncoding => RenderPage_SubProg_FinalEncoding;
    public readonly string RenderPage_SubProg_FinalEncoding = @"編碼媒體";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Init in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_Init => RenderPage_SubProg_Init;
    public readonly string RenderPage_SubProg_Init = @"初始化";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_None in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_None => RenderPage_SubProg_None;
    public readonly string RenderPage_SubProg_None = @"子程序進度";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_PrepareDraft in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_PrepareDraft => RenderPage_SubProg_PrepareDraft;
    public readonly string RenderPage_SubProg_PrepareDraft = @"準備專案";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_Render in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_Render => RenderPage_SubProg_Render;
    public readonly string RenderPage_SubProg_Render = @"渲染";
    
    /// <summary>
    /// Get the localized string for RenderPage_SubProg_WriteVideo in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_SubProg_WriteVideo => RenderPage_SubProg_WriteVideo;
    public readonly string RenderPage_SubProg_WriteVideo = @"寫入視訊";
    
    /// <summary>
    /// Get the localized string for RenderPage_TotalProg in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.RenderPage_TotalProg => RenderPage_TotalProg;
    public readonly string RenderPage_TotalProg = @"總進度";
    
    /// <summary>
    /// Get the localized string for WelcomeMessage in zh-TW
    /// </summary>
    string ISimpleLocalizerBase.WelcomeMessage => WelcomeMessage;
    public readonly string WelcomeMessage = @"歡迎來到projectFrameCut beta！";
    
    /// <summary>
    /// Get the localized string for _LocateDisplayName in zh-TW
    /// </summary>
    string ISimpleLocalizerBase._LocateDisplayName => _LocateDisplayName;
    public readonly string _LocateDisplayName = @"繁體中文 / Traditional Chinese";
    
    /// <summary>
    /// Get the current localized Id (like 'z')
    /// </summary>
    string ISimpleLocalizerBase._LocaleId_ => _LocaleId_;
    public readonly string _LocaleId_ = @"zh-TW";
    
    
}

namespace LocalizedResources
{
    public static class SimpleLocalizerBaseGeneratedHelper 
{
    /// <summary>
    /// Get the default localizer instance.
    /// </summary>
    /// <remarks>
    /// You need to initialize this property before using it.
    /// </remarks>
    public static ISimpleLocalizerBase Localized { get; set; } = null!;
}
}
